---
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /local/card-mod.js

lovelace:
  resources:
    - url: /local/mushroom.js
      type: module

homeassistant:
  packages: !include_dir_named packages/
  auth_mfa_modules:
    - type: totp

recorder:
  purge_keep_days: 90
  db_url: !secret hass_db_url

automation: !include_dir_merge_list automations
input_text: !include input_text.yaml
input_boolean: !include input_boolean.yaml
group: !include group.yaml
notify: !include notification.yaml
scene: !include scenes.yaml
script: !include_dir_merge_named scripts

http:
  use_x_forwarded_for: true
  trusted_proxies:
    # - !secret nginx_docker_ip
    # - !secret nginx_alternate_docker_ip
    - !secret cloudflare_tunnel_ip
  ip_ban_enabled: true
  login_attempts_threshold: 10

logger:
  default: info
  logs:
    reolink_aio.api: warning
