---
- alias: "Turn on kids hallway lights on motion"
  id: kids_hallway_turn_lights_on_basement_on_motion
  initial_state: true
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.kids_hallway_01_occupancy
        - binary_sensor.kids_hallway_02_occupancy
        - binary_sensor.occupancy_sensor_a206_occupancy
      to: 'on'
    - platform: homeassistant
      event: start

  # Only allow this automation to proceed if we are:
  #   BEFORE sunrise OR AFTER sunset
  condition:
    - condition: or
      conditions:
        - condition: sun
          before: sunrise
        - condition: sun
          after: sunset
          after_offset: "-01:00:00"

    # Also require that at least one sensor is on
    - condition: or
      conditions:
        - condition: state
          entity_id: binary_sensor.kids_hallway_01_occupancy
          state: 'on'
        - condition: state
          entity_id: binary_sensor.kids_hallway_02_occupancy
          state: 'on'
        - condition: state
          entity_id: binary_sensor.occupancy_sensor_a206_occupancy
          state: 'on'

  action:
    - choose:
        # CASE 1: After midnight but before sunrise => Dimmer only
        - conditions:
            - condition: sun
              before: sunrise
            - condition: time
              after: '00:00:00'
          sequence:
            - service: light.turn_on
              target:
                entity_id: light.shellydimmer2_34945478921b
              data:
                brightness_pct: 35

        # CASE 2: After sunset but before midnight => All three switches + Dimmer
        - conditions:
            - condition: sun
              after: sunset
            - condition: time
              before: '00:00:00'
          sequence:
            - service: homeassistant.turn_on
              target:
                entity_id:
                  - switch.shelly1pmminig3_dcda0cafe368_switch_0  # kids rooms spots
                  - switch.shelly1pmminig3_dcda0cead100_switch_0  # master bathroom spots
            - service: light.turn_on
              target:
                entity_id: light.shellydimmer2_34945478921b
              data:
                brightness_pct: 35

      default: []

- alias: "Turn off kids hallway light when no motion detected"
  id: kids_hallway_turn_lights_off_when_no_motion_detected
  initial_state: true
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.kids_hallway_01_occupancy
        - binary_sensor.kids_hallway_02_occupancy
        - binary_sensor.occupancy_sensor_a206_occupancy
      to: 'off'
    - platform: homeassistant
      event: start

  condition:
    - condition: state
      entity_id: binary_sensor.kids_hallway_01_occupancy
      state: 'off'
    - condition: state
      entity_id: binary_sensor.kids_hallway_02_occupancy
      state: 'off'
    - condition: state
      entity_id: binary_sensor.occupancy_sensor_a206_occupancy
      state: 'off'

  action:
    - action: homeassistant.turn_off
      entity_id:
        - switch.shelly1pmminig3_dcda0cafe368_switch_0
        - light.shellydimmer2_34945478921b
        - switch.shelly1pmminig3_dcda0cead100_switch_0


- alias: "Kids hallway - Turn off lights in the night"
  id: kids_hallway_turn_off_light_in_the_night
  initial_state: true
  trigger:
    - platform: time
      at: "23:00:00"

  action:
    - action: homeassistant.turn_off
      entity_id:
        - switch.shelly1pmminig3_34b7da92c7a4_switch_0  # book shelves hallway light


- alias: Hallway smoke detection on
  id: hallway_smoke_detection_on
  initial_state: true
  trigger:
    - entity_id: binary_sensor.hallway_ceiling_smoke
      platform: state
      from: 'off'
      to: 'on'
  action:
    - action: notify.ohad_telegram
      data_template:
        message: "Smoke has been detected in the hallway"
    - action: notify.mobile_app_ohadbenita
      data_template:
        title: "Hazards"
        message: "Smoke has been detected in the hallway, density is {{states('sensor.hallway_ceiling_smoke_density')}}%"

- alias: Hallway smoke detection off
  id: hallway_smoke_detection_off
  initial_state: true
  trigger:
    - entity_id: binary_sensor.hallway_ceiling_smoke
      platform: state
      from: 'on'
      to: 'off'
  action:
    - action: notify.ohad_telegram
      data_template:
        message: "Smoke in the hallway is not detected anymore"
    - action: notify.mobile_app_ohadbenita
      data_template:
        title: "Hazards"
        message: "Smoke is not detected in the hallway, density is {{states('sensor.hallway_ceiling_smoke_density')}}%"


- alias: Toggle book shelf light by entrance button
  id: hallway_toggle_bookshelf_light_by_button
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.main_hallway_book_shelf_01_action
      to: 'single'

  action:
    - action: switch.toggle
      entity_id: switch.shelly1pmminig3_34b7da92c7a4_switch_0
