---
- alias: "Turn on kids hallway lights on motion"
  id: kids_hallway_turn_lights_on_basement_on_motion
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.kids_hallway_01_occupancy
      to: 'on'
    - platform: state
      entity_id: binary_sensor.kids_hallway_02_occupancy
      to: 'on'
    - platform: homeassistant
      event: start

  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: binary_sensor.kids_hallway_01_occupancy
          state: 'on'
        - condition: state
          entity_id: binary_sensor.kids_hallway_02_occupancy
          state: 'on'

  action:
    - choose:
        - conditions:
          - condition: or  # yamllint disable-line rule:indentation
            conditions:
              - condition: sun
                before: sunrise
                before_offset: "01:00:00"
              - condition: sun
                after: sunset
                after_offset: "-01:00:00"
          sequence:
            - action: light.turn_on
              target:
                entity_id: light.shellydimmer2_34945478921b
              data:
                brightness_pct: 35

      default:
        - action: homeassistant.turn_on
          entity_id: switch.shelly1pmminig3_dcda0cafe368_switch_0


- alias: "Turn off kids hallway light when no motion detected"
  id: kids_hallway_turn_lights_off_when_no_motion_detected
  initial_state: true
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.kids_hallway_01_occupancy
      to: 'off'
    - platform: state
      entity_id:
        - binary_sensor.kids_hallway_02_occupancy
      to: 'off'
    - platform: homeassistant
      event: start

  condition:
    - condition: state
      entity_id: binary_sensor.kids_hallway_01_occupancy
      state: 'off'
    - condition: state
      entity_id: binary_sensor.kids_hallway_02_occupancy
      state: 'off'

  action:
    - action: homeassistant.turn_off
      entity_id:
        - switch.shelly1pmminig3_dcda0cafe368_switch_0
        - light.shellydimmer2_34945478921b


- alias: "Kids hallway - Turn off lights in the night"
  id: kids_hallway_turn_off_light_in_the_night
  initial_state: true
  trigger:
    - platform: time
      at: "23:00:00"

  action:
    - action: homeassistant.turn_off
      entity_id:
        - switch.shelly1pmminig3_34b7da8f8b78_switch_0  # book shelves hallway light
