---
- alias: Lock doors at night
  id: nuki_doors_lock_at_night
  initial_state: true
  mode: single
  trigger:
    - platform: time
      at: "23:00:00"
    - platform: time
      at: "00:00:00"
  action:
    - alias: "Lock entrance door with retry"
      repeat:
        sequence:
          - action: lock.lock
            target:
              entity_id: lock.entrance_door
          - delay: "00:00:05"
        until:
          - condition: state
            entity_id: lock.entrance_door
            state: locked

    - alias: "Lock kitchen door with retry"
      repeat:
        sequence:
          - action: lock.lock
            target:
              entity_id: lock.kitchen_door
          - delay: "00:00:05"
        until:
          - condition: state
            entity_id: lock.kitchen_door
            state: locked

    - alias: "Lock bathroom door with retry"
      repeat:
        sequence:
          - action: lock.lock
            target:
              entity_id: lock.kids_bathroom_door
          - delay: "00:00:05"
        until:
          - condition: state
            entity_id: lock.kids_bathroom_door
            state: locked

    - alias: "Lock bathroom door with retry"
      repeat:
        sequence:
          - action: lock.lock
            target:
              entity_id: lock.clinic_door
          - delay: "00:00:05"
        until:
          - condition: state
            entity_id: lock.clinic_door
            state: locked


- alias: Close everything when away mode is turned on
  id: security_set_all_covers_to_5_on_away_mode
  initial_state: true
  trigger:
    - platform: state
      entity_id: input_boolean.away_mode
      to: 'on'

  action:
    - action: cover.set_cover_position
      data:
        position: 15
      target:
        entity_id: >
          {{ states.cover | map(attribute='entity_id') | list }}
    - action: lock.lock
      target:
        entity_id: lock.home_only_doors


- alias: Open covers when away mode is turned off
  id: security_open_covers_away_mode_off
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: input_boolean.away_mode
      to: 'off'
  condition:
    - condition: state
      entity_id: person.ohad_benita
      state: 'home'
    - condition: state
      entity_id: sensor.ohadbenita_ssid
      state: 'Benita'
  action:
    - action: cover.set_cover_position
      data:
        position: 90
      target:
        entity_id: >
          {{ states.cover | map(attribute='entity_id') | list }}
