---
- alias: "Turn on upper hallway light on motion"
  id: stair_light_turn_on_upper_on_motion
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.upstairs_floor_stairs_01_occupancy
        - binary_sensor.upstairs_floor_stairs_02_occupancy
        - binary_sensor.upstairs_floor_stairs_03_occupancy
      to: 'on'
    - platform: homeassistant
      event: start

  condition:
    condition: and
    conditions:
      - condition: or
        conditions:
          - condition: sun
            before: sunrise
            before_offset: "01:00:00"
          - condition: sun
            after: sunset
            after_offset: "-01:00:00"
      - condition: or
        conditions:
          - condition: state
            entity_id: binary_sensor.upstairs_floor_stairs_01_occupancy
            state: 'on'
          - condition: state
            entity_id: binary_sensor.upstairs_floor_stairs_02_occupancy
            state: 'on'
          - condition: state
            entity_id: binary_sensor.upstairs_floor_stairs_03_occupancy
            state: 'on'

  action:
    - action: homeassistant.turn_on
      entity_id: switch.shelly1pmminig3_34b7da8f85bc_switch_0


- alias: "Turn off upper hallway light when no motion is detected"
  id: stair_light_turn_off_upper_when_no_motion
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.upstairs_floor_stairs_01_occupancy
        - binary_sensor.upstairs_floor_stairs_02_occupancy
        - binary_sensor.upstairs_floor_stairs_03_occupancy
      to: 'off'
    - platform: homeassistant
      event: start

  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.upstairs_floor_stairs_01_occupancy
        state: 'off'
      - condition: state
        entity_id: binary_sensor.upstairs_floor_stairs_02_occupancy
        state: 'off'
      - condition: state
        entity_id: binary_sensor.upstairs_floor_stairs_03_occupancy
        state: 'off'

  action:
    - action: homeassistant.turn_off
      entity_id: switch.shelly1pmminig3_34b7da8f85bc_switch_0


- alias: "Turn on basement stairs light on motion"
  id: stair_light_turn_on_basement_on_motion
  initial_state: true
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.basement_stairs_01_occupancy
        - binary_sensor.basement_stairs_02_occupancy
      to: 'on'
    - platform: homeassistant
      event: start

  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: binary_sensor.basement_stairs_01_occupancy
          state: 'on'
        - condition: state
          entity_id: binary_sensor.basement_stairs_02_occupancy
          state: 'on'

  action:
    - action: homeassistant.turn_on
      entity_id: switch.shelly1pmminig3_54320451ae98_switch_0


- alias: "Turn off basement stairs light when no motion detected"
  id: stair_light_turn_off_basement_when_no_motion_detected
  initial_state: true
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.basement_stairs_01_occupancy
        - binary_sensor.basement_stairs_02_occupancy
      to: 'off'
    - platform: homeassistant
      event: start

  condition:
    - condition: state
      entity_id: binary_sensor.basement_stairs_01_occupancy
      state: 'off'
    - condition: state
      entity_id: binary_sensor.basement_stairs_02_occupancy
      state: 'off'

  action:
    - action: homeassistant.turn_off
      entity_id: switch.shelly1pmminig3_54320451ae98_switch_0
