---
sensor:
  - platform: history_stats
    name: "3D Print Active Time"
    entity_id: sensor.creality_ender_v3_ke_current_print_state
    state: "printing"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"


template:
  - sensor:
      - name: "3D Print Estimated Completion Time"
        unit_of_measurement: "hours"
        state: >
          {% set current_progress = states('sensor.creality_ender_v3_ke_progress') | float %}
          {% set active_time = states('sensor.3d_print_active_time') | float %}
          {% if current_progress > 0 and active_time > 0 %}
            {{ (100 - current_progress) / (current_progress / active_time) }}
          {% else %}
            unknown
          {% endif %}

automation:
  - alias: "Send picture once printing is done"
    id: 3d_printer_send_snapshot_when_done
    initial_state: true
    trigger:
      - platform: state
        entity_id: sensor.creality_ender_v3_ke_current_print_state
        from: printing
        to: complete

    action:
      - action: camera.snapshot
        data:
          entity_id: camera.creality_ender_v3_ke
          filename: "/config/www/snapshots/3d_printer_snapshot.jpg"

      - delay: '00:00:02'

      - action: homeassistant.turn_off
        entity_id: switch.creality_printer

      - action: notify.ohad_telegram
        data:
          message: "The 3D print has completed & the printer has been turned off"
          data:
            photo:
              - file: "/config/www/snapshots/3d_printer_snapshot.jpg"
                caption: "The 3D print has completed & the printer has been turned off"

  - alias: "Send picture once printing is in error"
    id: 3d_printer_send_snapshot_when_in_error
    initial_state: true
    trigger:
      - platform: state
        entity_id: sensor.creality_ender_v3_ke_current_print_state
        to: error

    action:
      - action: camera.snapshot
        data:
          entity_id: camera.creality_ender_v3_ke
          filename: "/config/www/snapshots/3d_printer_snapshot_error.jpg"
      - delay: '00:00:02'

      - action: notify.ohad_telegram
        data:
          message: "The 3D print has come to an error. Here's a snapshot"
          data:
            photo:
              - file: "/config/www/snapshots/3d_printer_snapshot_error.jpg"
                caption: "The 3D print has come to an error. Here's a snapshot"
