---
template:
  - sensor:
      - name: "Adi Room AC Temperature"
        unit_of_measurement: "°C"
        state: "{{ state_attr('climate.adi_room_ac', 'current_temperature') }}"
        availability: "{{ state_attr('climate.adi_room_ac', 'current_temperature') is not none }}"
        device_class: temperature
        icon: mdi:thermometer


automation:
  - alias: "Adi Room - Set AC to night mode (summer)"
    id: adi_room_ac_night_automation
    initial_state: true
    trigger:
      - platform: time
        at: "00:30:00"
      - platform: time
        at: "01:30:00"

    condition:
      condition: and
      conditions:
        - condition: template
          value_template: >-
            {{ not (
                is_state_attr('climate.adi_room_ac', 'preset_mode', 'sleep') and
                is_state_attr('climate.adi_room_ac', 'temperature', 24) and
                is_state_attr('climate.adi_room_ac', 'fan_mode', 'silent') and
                is_state_attr('climate.adi_room_ac', 'swing_mode', 'both')
              )
            }}
        - condition: state
          entity_id: climate.adi_room_ac
          state: 'cool'

    action:
      - action: switch.turn_off
        entity_id: switch.adi_room_ac_beeper

      - action: climate.set_preset_mode
        data:
          entity_id: climate.adi_room_ac
          preset_mode: sleep
      - action: climate.set_temperature
        data:
          entity_id: climate.adi_room_ac
          temperature: 24
      - action: climate.set_fan_mode
        data:
          entity_id: climate.adi_room_ac
          fan_mode: silent
      - action: climate.set_swing_mode
        data:
          swing_mode: both
          entity_id: climate.adi_room_ac

      - action: switch.turn_on
        entity_id: switch.adi_room_ac_beeper


  - alias: "Turn on Adi room light on motion"
    id: adi_room_turn_light_on_motion
    initial_state: false
    trigger:
      - platform: state
        entity_id: binary_sensor.apollo_msr_1_cb6db4_radar_target
        to: 'on'

      - platform: homeassistant
        event: start

    condition:
      - condition: state
        entity_id: binary_sensor.apollo_msr_1_cb6db4_radar_target
        state: 'on'
      - condition: time
        before: '23:00:00'
        after: '08:00:00'

    action:
      - action: homeassistant.turn_on
        entity_id:
          - switch.shellyplus2pm_fcb467a580a8_switch_0  # light
          - switch.shellyplus2pm_fcb467a580a8_switch_1  # fan


  - alias: "Turn off Adi room light when no motion is detected"
    id: adi_room_turn_light_off_no_motion_detected
    initial_state: false
    trigger:
      - platform: state
        entity_id: binary_sensor.apollo_msr_1_cb6db4_radar_target
        to: 'off'
        for:
          minutes: 5

      - platform: homeassistant
        event: start

    condition:
      - condition: state
        entity_id: binary_sensor.apollo_msr_1_cb6db4_radar_target
        state: 'off'
      - condition: time
        before: '23:00:00'
        after: '08:00:00'

    action:
      - action: homeassistant.turn_off
        entity_id:
          - switch.shellyplus2pm_fcb467a580a8_switch_0  # light
          - switch.shellyplus2pm_fcb467a580a8_switch_1  # fan

  - alias: 'Adi room - Handle Bedside button actions'
    id: adi_room_bedside_button_actions
    initial_state: true
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.adi_bedside_action

    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: sensor.adi_bedside_action
                state: 'single'
            sequence:
              - action: switch.toggle
                target:
                  entity_id: switch.shellyplus2pm_fcb467a580a8_switch_1

          - conditions:
              - condition: state
                entity_id: sensor.adi_bedside_action
                state: 'double'
            sequence:
              - action: switch.toggle
                target:
                  entity_id: switch.shellyplus2pm_fcb467a580a8_switch_0

          - conditions:
              - condition: state
                entity_id: sensor.adi_bedside_action
                state: 'hold'
            sequence:
              - action: climate.toggle
                target:
                  entity_id: climate.adi_room_ac
