---
template:
  - sensor:
      - name: "Adi Room AC Temperature"
        unit_of_measurement: "°C"
        state: "{{ state_attr('climate.adi_room_ac', 'current_temperature') }}"
        availability: "{{ state_attr('climate.adi_room_ac', 'current_temperature') is not none }}"
        device_class: temperature
        icon: mdi:thermometer

  - binary_sensor:
      - name: "Adi Room Occupancy"
        unique_id: adi_room_occupancy
        device_class: occupancy
        state: >
          {{
            is_state('binary_sensor.occupancy_sensor_3012_occupancy', 'on')
            or is_state('binary_sensor.occupancy_sensor_5775_occupancy', 'on')
          }}

sensor:
  - platform: derivative
    source: sensor.adi_room_temperature
    name: Adi room temp difference change per 10 minutes
    round: 1
    unit_time: min
    time_window: 10


automation:
  - alias: "Adi Room - Set AC to night mode (summer)"
    id: adi_room_ac_night_automation
    initial_state: true
    trigger:
      - platform: time
        at: "00:30:00"
      - platform: time
        at: "01:30:00"

    condition:
      condition: and
      conditions:
        - condition: template
          value_template: >-
            {{ not (
                is_state_attr('climate.adi_room_ac', 'preset_mode', 'sleep') and
                is_state_attr('climate.adi_room_ac', 'temperature', 24) and
                is_state_attr('climate.adi_room_ac', 'fan_mode', 'silent') and
                is_state_attr('climate.adi_room_ac', 'swing_mode', 'both')
              )
            }}
        - condition: state
          entity_id: climate.adi_room_ac
          state: 'cool'

    action:
      - action: switch.turn_off
        entity_id: switch.adi_room_ac_beeper

      - action: climate.set_preset_mode
        data:
          entity_id: climate.adi_room_ac
          preset_mode: sleep
      - action: climate.set_temperature
        data:
          entity_id: climate.adi_room_ac
          temperature: 24
      - action: climate.set_fan_mode
        data:
          entity_id: climate.adi_room_ac
          fan_mode: silent
      - action: climate.set_swing_mode
        data:
          swing_mode: both
          entity_id: climate.adi_room_ac

      - action: switch.turn_on
        entity_id: switch.adi_room_ac_beeper


  - alias: "Turn on Adi room light on motion"
    id: adi_room_turn_light_on_motion
    initial_state: false
    trigger:
      - platform: state
        entity_id: binary_sensor.adi_room_occupancy
        to: 'on'

      - platform: homeassistant
        event: start

    condition:
      - condition: state
        entity_id: binary_sensor.adi_room_occupancy
        state: 'on'

    action:
      - action: homeassistant.turn_on
        entity_id:
          - switch.shellyplus2pm_fcb467a580a8_switch_0    # light
          - switch.shelly1pmminig3_34b7da9275f0_switch_0  # Night light


  - alias: "Turn off Adi room appliances when no motion is detected"
    id: adi_room_turn_light_off_no_motion_detected
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.adi_room_occupancy
        from: 'on'
        to: 'off'
        for:
          minutes: 10

      - platform: homeassistant
        event: start

    condition:
      - condition: state
        entity_id: binary_sensor.adi_room_occupancy
        state: 'off'
      - condition: template
        value_template: >
          {{ not (
              is_state('switch.shellyplus2pm_fcb467a580a8_switch_0', 'off')
              and is_state('switch.shellyplus2pm_fcb467a580a8_switch_1', 'off')
              and is_state('switch.shelly1pmminig3_34b7da9275f0_switch_0', 'off')
              and is_state('climate.adi_room_ac', 'off')
            )
          }}

    action:
      - action: homeassistant.turn_off
        entity_id:
          - switch.shellyplus2pm_fcb467a580a8_switch_0    # light
          - switch.shellyplus2pm_fcb467a580a8_switch_1    # fan
          - switch.shelly1pmminig3_34b7da9275f0_switch_0  # Night light
          - climate.adi_room_ac


  - alias: "Adi room entrance switch fan control"
    id: adi_room_entrance_switch_fan_control
    initial_state: true
    trigger:
      - platform: state
        entity_id: switch.adi_room_fan_entrance_switch_switch_0

    action:
      - action: switch.toggle
        entity_id: switch.shellyplus2pm_fcb467a580a8_switch_1    # fan


  - alias: 'Adi room - Handle Bedside button actions'
    id: adi_room_bedside_button_actions
    initial_state: true
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.adi_bedside_action

    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: sensor.adi_bedside_action
                state: 'single'
            sequence:
              - action: switch.toggle
                target:
                  entity_id: switch.shellyplus2pm_fcb467a580a8_switch_1

          - conditions:
              - condition: state
                entity_id: sensor.adi_bedside_action
                state: 'double'
            sequence:
              - action: switch.toggle
                target:
                  entity_id: switch.shellyplus2pm_fcb467a580a8_switch_0

          - conditions:
              - condition: state
                entity_id: sensor.adi_bedside_action
                state: 'hold'
            sequence:
              - choose:
                  - conditions:
                      - condition: state
                        entity_id: climate.adi_room_ac
                        state: 'off'
                    sequence:
                      - choose:
                          - conditions:
                              - condition: numeric_state
                                entity_id: sensor.openweathermap_feels_like_temperature
                                above: 23
                            sequence:
                              - service: climate.set_hvac_mode
                                target:
                                  entity_id: climate.adi_room_ac
                                data:
                                  hvac_mode: 'cool'
                        default:
                          - service: climate.set_hvac_mode
                            target:
                              entity_id: climate.adi_room_ac
                            data:
                              hvac_mode: 'heat'
                default:
                  - service: climate.turn_off
                    target:
                      entity_id: climate.adi_room_ac


  - alias: "Sync Adi night light with fan light"
    id: adi_room_sync_night_light_with_fan_light
    initial_state: true
    trigger:
      - platform: state
        entity_id: switch.shellyplus2pm_fcb467a580a8_switch_0
      - platform: homeassistant
        event: start
    action:
      - action: >
          {% if trigger.platform == 'homeassistant' %}
            {% if states('switch.shellyplus2pm_fcb467a580a8_switch_0') == 'on' %}
              switch.turn_on
            {% else %}
              switch.turn_off
            {% endif %}
          {% elif trigger.to_state.state == 'on' %}
            switch.turn_on
          {% elif trigger.to_state.state == 'off' %}
            switch.turn_off
          {% endif %}
        entity_id: switch.shelly1pmminig3_34b7da9275f0_switch_0


  - alias: Shutdown Adi room AC 1 hour after target temperature has been reached
    id: adi_room_shutdown_ac_target_temp_reached
    initial_state: true
    trigger:
      - platform: numeric_state
        entity_id: sensor.adi_room_temp_difference_change_per_10_minutes
        above: -1
        below: 1
        for:
          hours: 1
      - platform: template
        value_template: >-
          {{
            states('climate.adi_room_ac') != 'off' and
            (now() - states.climate.adi_room_ac.last_changed).total_seconds() > 3600
          }}

    condition:
      - condition: template
        value_template: >
          {{
            states('climate.adi_room_ac') != 'off' and
            (now() - states.climate.adi_room_ac.last_changed).total_seconds() > 3600
          }}
      - condition: numeric_state
        entity_id: sensor.adi_room_temp_difference_change_per_10_minutes
        above: -1
        below: 1

    action:
      - action: climate.turn_off
        entity_id: climate.adi_room_ac
