---
#  Awtrix documentation - https://blueforcer.github.io/awtrix3/
input_number:
  awtrix_transition_speed:
    name: Awtrix Transition Speed
    min: 500
    max: 5000
    step: 100
    unit_of_measurement: milliseconds
    icon: mdi:timer

  awtrix_app_time:
    name: Awtrix App Time
    min: 10
    max: 120
    step: 1
    unit_of_measurement: seconds
    icon: mdi:timer


automation:
  - alias: Awtrix Spotify Now Playing
    id: awtrix_spotify_now_playing
    description: Awtrix now playing automation
    trigger:
      - platform: state
        entity_id: media_player.spotify_ohad_benita
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: media_player.spotify_ohad_benita
                state: playing
              - condition: state
                entity_id: media_player.spotify_ohad_benita
                attribute: media_content_type
                state: music
              - condition: state
                entity_id: person.ohad_benita
                state: 'home'
            sequence:
              - service: mqtt.publish
                data:
                  qos: 0
                  retain: false
                  payload: |-
                    {
                      "text": "{{ state_attr('media_player.spotify_ohad_benita', 'media_artist') }} - {{ state_attr('media_player.spotify_ohad_benita', 'media_title') }}",
                      "icon": "18207",
                      "rainbow": true,
                      "repeat": 2,
                      "pushIcon": 0,
                      "textCase": 0,
                      "textOffset": 15,
                      "progress": {{ ( states.media_player.spotify_ohad_benita.attributes.media_position / states.media_player.spotify_ohad_benita.attributes.media_duration * 100 ) | round() }},
                      "progressC": "18B04C"
                    }
                  topic: awtrix/custom/spotify
          - conditions:
              - condition: template
                value_template: >-
                  {{ not states.media_player.spotify_ohad_benita.state == 'playing' }}
            sequence:
              - service: mqtt.publish
                data:
                  qos: 0
                  retain: false
                  topic: awtrix/custom/spotify


  - alias: Awtrix Night Clock
    id: awtrix_night_clock
    use_blueprint:
      path: RDG88/nightclock_awtrix.yaml
      input:
        sleep_time: '21:00:00'
        awtrix:
          - 225674118643627b363d074e5fc83256
        sleep_weekday_bar: true
        wakeup_settings_abri: true
        wakeup_settings_calendar_color:
          - 0
          - 85
          - 255


  - alias: "Awtrix Transition Speed"
    id: awtrix_transition_speed
    trigger:
      - platform: state
        entity_id: input_number.awtrix_transition_speed
    action:
      - service: mqtt.publish
        data:
          topic: "awtrix/settings"
          payload: '{"TSPEED": {{ (states("input_number.awtrix_transition_speed") | int) }}}'


  - alias: "Awtrix App time"
    id: awtrix_app_time
    trigger:
      - platform: state
        entity_id: input_number.awtrix_app_time
    action:
      - service: mqtt.publish
        data:
          topic: "awtrix/settings"
          payload: '{"ATIME": {{ (states("input_number.awtrix_app_time") | int) }}}'
