---
#  Awtrix documentation - https://blueforcer.github.io/awtrix3/
input_number:
  awtrix_transition_speed:
    name: Awtrix Transition Speed
    min: 500
    max: 5000
    step: 100
    unit_of_measurement: milliseconds
    icon: mdi:timer

  awtrix_app_time:
    name: Awtrix App Time
    min: 10
    max: 120
    step: 1
    unit_of_measurement: seconds
    icon: mdi:timer


automation:
  - alias: Awtrix Spotify Now Playing
    id: awtrix_spotify_now_playing
    description: Awtrix now playing automation
    trigger:
      - platform: state
        entity_id: media_player.spotify_ohad_benita
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: media_player.spotify_ohad_benita
                state: playing
              - condition: state
                entity_id: media_player.spotify_ohad_benita
                attribute: media_content_type
                state: music
              - condition: state
                entity_id: person.ohad_benita
                state: 'home'
              - condition: state
                entity_id: sensor.ohad_ble
                state: 'study'
            sequence:
              - action: mqtt.publish
                data:
                  qos: 0
                  retain: false
                  payload: |-
                    {
                      "text": "{{ state_attr('media_player.spotify_ohad_benita', 'media_artist') }} - {{ state_attr('media_player.spotify_ohad_benita', 'media_title') }}",
                      "icon": "18207",
                      "rainbow": true,
                      "repeat": 2,
                      "pushIcon": 0,
                      "textCase": 0,
                      "textOffset": 15,
                      "progress": {{ ( states.media_player.spotify_ohad_benita.attributes.media_position / states.media_player.spotify_ohad_benita.attributes.media_duration * 100 ) | round() }},
                      "progressC": "18B04C"
                    }
                  topic: awtrix/custom/spotify
          - conditions:
              - condition: template
                value_template: >-
                  {{ not states.media_player.spotify_ohad_benita.state == 'playing' }}
            sequence:
              - action: mqtt.publish
                data:
                  qos: 0
                  retain: false
                  topic: awtrix/custom/spotify


  - alias: Awtrix ohad@lightricks.com calendar event notification
    id: awtrix_ohad_lightricks_com_calendar_event_notification
    initial_state: true
    description: "Awtrix ohad@lightricks.com calendar event notification"
    trigger:
      - platform: calendar
        entity_id: calendar.ohad_lightricks_com
        offset: "-00:05:00"
        event: start
      - platform: calendar
        entity_id: calendar.ohad_lightricks_com
        offset: "00:10:00"
        event: start
    action:
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ trigger.event == 'start' and trigger.offset.total_seconds() == -300 }}"
              - condition: state
                entity_id: person.ohad_benita
                state: 'home'
              - condition: time
                weekday:
                  - "sun"
                  - "mon"
                  - "tue"
                  - "wed"
                  - "thu"
              - condition: template
                value_template: "{{ 'no interviews' not in state_attr('calendar.ohad_lightricks_com', 'message') | lower }}"
            sequence:
              - action: mqtt.publish
                data:
                  qos: 0
                  retain: false
                  payload: |-
                    {
                      "text": "{{ state_attr('calendar.ohad_lightricks_com', 'message') }}",
                      "icon": "18207",
                      "repeat": 2,
                      "pushIcon": 0,
                      "textCase": 0,
                      "textOffset": 15,
                      "progress": "{{ ((as_timestamp(now()) - as_timestamp(state_attr('calendar.ohad_lightricks_com', 'start_time'))) / (as_timestamp(state_attr('calendar.ohad_lightricks_com', 'end_time')) - as_timestamp(state_attr('calendar.ohad_lightricks_com', 'start_time'))) * 100) | round() }}",
                      "progressC": "18B04C",
                      "location": "{{ state_attr('calendar.ohad_lightricks_com', 'location') }}",
                      "description": "{{ state_attr('calendar.ohad_lightricks_com', 'description') }}"
                    }
                  topic: awtrix/custom/calendar

          - conditions:
              - condition: template
                value_template: "{{ trigger.event == 'start' and trigger.offset.total_seconds() == 600 }}"
            sequence:
              - action: mqtt.publish
                data:
                  qos: 0
                  retain: false
                  topic: awtrix/custom/calendar


  - alias: Awtrix Night Clock
    id: awtrix_night_clock
    use_blueprint:
      path: RDG88/nightclock_awtrix.yaml
      input:
        sleep_time: '21:00:00'
        awtrix:
          - 225674118643627b363d074e5fc83256
        sleep_weekday_bar: true
        wakeup_settings_abri: true
        wakeup_settings_calendar_color:
          - 0
          - 85
          - 255


  - alias: "Awtrix set transition Speed"
    id: awtrix_transition_speed
    trigger:
      - platform: state
        entity_id: input_number.awtrix_transition_speed
    action:
      - action: mqtt.publish
        data:
          topic: "awtrix/settings"
          payload: '{"TSPEED": {{ (states("input_number.awtrix_transition_speed") | int) }}}'


  - alias: "Awtrix set app time"
    id: awtrix_app_time
    trigger:
      - platform: state
        entity_id: input_number.awtrix_app_time
    action:
      - action: mqtt.publish
        data:
          topic: "awtrix/settings"
          payload: '{"ATIME": {{ (states("input_number.awtrix_app_time") | int) }}}'


  - alias: "Awtrix Weather and forecast"
    initial_state: false
    use_blueprint:
      path: jeeftor/awtrix_weatherflow.yaml
      input:
        awtrix:
          - 225674118643627b363d074e5fc83256
        forecast_var: weather.openweathermap
        temp_suffix: °C
        current_temp_var: sensor.openweathermap_current_feels_like_temperature
        moon_rise_set: sensor.ip_geo_location
        moon: sensor.moon_phase
        message_duration_forecast: 60
        message_duration_riseset: 60
