---
light:
  - platform: template
    lights:
      all_basement_lights:
        value_template: >-
          {{
            is_state('switch.shelly1pmminig3_34b7da8a0338_switch_0', 'on') and
            is_state('switch.shelly1pmminig3_34b7da8b78c4_switch_0', 'on') and
            is_state('switch.shellyplus2pm_a0a3b3682b10_switch_1', 'on') and
            is_state('switch.shellyplus2pm_a0a3b3682b10_switch_0', 'on')
          }}
        turn_on:
          action: homeassistant.turn_on
          data:
            entity_id:
              - switch.shellyplus2pm_a0a3b3682b10_switch_0
              - switch.shellyplus2pm_a0a3b3682b10_switch_1
              - switch.shelly1pmminig3_34b7da8a0338_switch_0
              - switch.shelly1pmminig3_34b7da8b78c4_switch_0
        turn_off:
          action: homeassistant.turn_off
          data:
            entity_id:
              - switch.shellyplus2pm_a0a3b3682b10_switch_0
              - switch.shellyplus2pm_a0a3b3682b10_switch_1
              - switch.shelly1pmminig3_34b7da8a0338_switch_0
              - switch.shelly1pmminig3_34b7da8b78c4_switch_0


automation:
  - alias: 'Restart Xiaomi Basement TV'
    id: basement_xiaomi_tv_restart
    initial_state: true
    trigger:
      - platform: time
        at: '05:00:00'

    action:
      - action: switch.turn_off
        entity_id: switch.athom_01

      - delay: '00:02:00'

      - action: switch.turn_on
        entity_id: switch.athom_01


  - alias: "Turn on basement lights on motion"
    id: basement_turn_lights_on_motion
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.occupancy_sensor_fe31_occupancy
        to: 'on'

      - platform: homeassistant
        event: start

    condition:
      - condition: state
        entity_id: binary_sensor.occupancy_sensor_fe31_occupancy
        state: 'on'
      - condition: state
        entity_id: input_boolean.away_mode
        state: 'off'

    action:
      - action: homeassistant.turn_on
        entity_id:
          - switch.shellyplus2pm_a0a3b3682b10_switch_0  # Ceiling
          - switch.shellyplus2pm_a0a3b3682b10_switch_1  # Piano


  - alias: "Turn off basement lights when no motion is detected"
    id: basement_turn_lights_off_no_motion_detected
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.occupancy_sensor_fe31_occupancy
        to: 'off'
        for:
          minutes: 5

      - platform: homeassistant
        event: start

    condition:
      - condition: state
        entity_id: binary_sensor.occupancy_sensor_fe31_occupancy
        state: 'off'
        for:
          minutes: 5

    action:
      - action: homeassistant.turn_off
        entity_id:
          - switch.shellyplus2pm_a0a3b3682b10_switch_0  # Ceiling
          - switch.shellyplus2pm_a0a3b3682b10_switch_1  # Piano


  - alias: "Control shelter light with 15 min off delay"
    id: basement_control_shelter_light_with_off_delay
    initial_state: true
    mode: restart
    trigger:
      - platform: state
        entity_id: binary_sensor.occupancy_sensor_fe31_occupancy
        to: 'off'
        for: "00:15:00"
      - platform: homeassistant
        event: start

    action:
      - if:
          - condition: state
            entity_id: binary_sensor.occupancy_sensor_fe31_occupancy
            state: 'on'
        then:
          - service: homeassistant.turn_on
            entity_id: switch.shelly1pmminig3_34b7da8a0338_switch_0
        else:
          - service: homeassistant.turn_off
            entity_id: switch.shelly1pmminig3_34b7da8a0338_switch_0


  - alias: "Control shelter corridor light with 5 min off delay"
    id: basement_control_shelter_corridor_light_with_off_delay
    initial_state: true
    mode: restart
    trigger:
      # - platform: state
      #   entity_id: binary_sensor.occupancy_sensor_34f8_occupancy
      #   to: 'on'
      - platform: state
        entity_id: binary_sensor.occupancy_sensor_34f8_occupancy
        to: 'off'
        for: "00:05:00"
      - platform: homeassistant
        event: start

    action:
      - if:
          - condition: state
            entity_id: binary_sensor.occupancy_sensor_34f8_occupancy
            state: 'on'
        then:
          - service: homeassistant.turn_on
            entity_id: switch.shelly1pmminig3_34b7da8b78c4_switch_0
        else:
          - service: homeassistant.turn_off
            entity_id: switch.shelly1pmminig3_34b7da8b78c4_switch_0
