---
automation:
  - alias: 'Restart Xiaomi Basement TV'
    id: basement_xiaomi_tv_restart
    initial_state: true
    trigger:
      - platform: time
        at: '05:00:00'

    action:
      - action: switch.turn_off
        entity_id: switch.athom_01

      - delay: '00:02:00'

      - action: switch.turn_on
        entity_id: switch.athom_01


  - alias: "Turn on basement lights on motion"
    id: basement_turn_lights_on_motion
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.apollo_msr_2_3318a4_radar_target
        to: 'on'

      - platform: homeassistant
        event: start

    condition:
      - condition: state
        entity_id: binary_sensor.apollo_msr_2_3318a4_radar_target
        state: 'on'

    action:
      - action: homeassistant.turn_on
        entity_id:
          - switch.shellyplus2pm_a0a3b3682b10_switch_0  # Ceiling
          - switch.shellyplus2pm_a0a3b3682b10_switch_1  # Piano


  - alias: "Turn off basement lights when no motion is detected"
    id: basement_turn_lights_off_no_motion_detected
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.apollo_msr_2_3318a4_radar_target
        to: 'off'
        for:
          minutes: 5

      - platform: homeassistant
        event: start

    condition:
      - condition: state
        entity_id: binary_sensor.apollo_msr_2_3318a4_radar_target
        state: 'off'

    action:
      - action: homeassistant.turn_off
        entity_id:
          - switch.shellyplus2pm_a0a3b3682b10_switch_0  # Ceiling
          - switch.shellyplus2pm_a0a3b3682b10_switch_1  # Piano
