---
input_text:
  washing_machine_cycles_completed_today:
    name: washing_machine_cycles_completed_today
  washing_machine_cycles_completed_this_week:
    name: washing_machine_cycles_completed_today
  dishwasher_cycles_completed_today:
    name: dishwasher_cycles_completed_today
  dishwasher_cycles_completed_this_week:
    name: dishwasher_cycles_completed_today


automation:
  - alias: Reset weekly counters
    id: chore_stats_reset_weekly_counters
    initial_state: true
    trigger:
      platform: time
      at: '02:00:00'
    condition:
      condition: and
      conditions:
        - condition: time
          weekday:
            - "sun"
    action:
      - action: input_text.set_value
        data:
          entity_id:
            - input_text.dishwasher_cycles_completed_this_week
            - input_text.washing_machine_cycles_completed_this_week
          value: 0


  - alias: Reset daily counters
    id: chore_stats_reset_daily_counters
    initial_state: true
    trigger:
      platform: time
      at: '00:00:00'
    action:
      - action: input_text.set_value
        data:
          entity_id:
            - input_text.dishwasher_cycles_completed_today
            - input_text.washing_machine_cycles_completed_today
          value: 0


  - alias: Update dishwasher cycles
    id: chore_stats_update_dishwasher_cycles
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.dishwasher_active
        from: 'on'
        to: 'off'
        for:
          minutes: 44

    action:
      - action: input_text.set_value
        data_template:
          entity_id: input_text.dishwasher_cycles_completed_this_week
          value: >-
            {{ states('input_text.dishwasher_cycles_completed_this_week') | int + 1 }}
      - action: input_text.set_value
        data_template:
          entity_id: input_text.dishwasher_cycles_completed_today
          value: >-
            {{ states('input_text.dishwasher_cycles_completed_today') | int + 1 }}


  - alias: Washing Machine Cycle Detection and Count Increment
    id: chore_stats_update_washing_machine_cycles
    description: >
      Detects when the washing machine power goes above 2000W and then waits for the sensor to show 0 for 10 minutes,
      indicating that the cycle is complete. The cycle counter is then incremented.
    trigger:
      - platform: numeric_state
        entity_id: sensor.washing_machine_energy_power
        above: 2000
    action:
      - alias: Wait for sustained power-off (0 for 10 minutes)
        wait_for_trigger:
          - platform: numeric_state
            entity_id: sensor.washing_machine_energy_power
            below: 1
            for:
              minutes: 5
        timeout: "03:30:00"
        continue_on_timeout: false
      - alias: Increment cycle count
        service: input_text.set_value
        target:
          entity_id: input_text.washing_machine_cycles_completed_this_week
        data:
          value: "{{ (states('input_text.washing_machine_cycles_completed_this_week')|int + 1) }}"
    mode: single

  # - alias: Update washing machine cycles
  #   id: chore_stats_update_washing_machine_cycles
  #   initial_state: true
  #   trigger:
  #     - platform: state
  #       entity_id: binary_sensor.washing_machine_active
  #       from: 'on'
  #       to: 'off'
  #       for:
  #         minutes: 40

  #   action:
  #     - action: input_text.set_value
  #       data_template:
  #         entity_id: input_text.washing_machine_cycles_completed_this_week
  #         value: >-
  #           {{ states('input_text.washing_machine_cycles_completed_this_week') | int + 1 }}
  #     - action: input_text.set_value
  #       data_template:
  #         entity_id: input_text.washing_machine_cycles_completed_today
  #         value: >-
  #           {{ states('input_text.washing_machine_cycles_completed_today') | int + 1 }}
