---
rest_command:
  analyze_gas_water_heater_display:
    url: !secret analyze_gas_water_heater_display_url
    method: GET

automation:
  - alias: "Turn on cloak room light on motion"
    id: cloak_room_turn_light_on_motion
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.cloak_room_occupancy
        to: 'on'
      - platform: homeassistant
        event: start
    condition:
      - condition: state
        entity_id: binary_sensor.cloak_room_occupancy
        state: 'on'
    action:
      - action: homeassistant.turn_on
        entity_id: switch.shellyplus2pm_fcb467a684e8_switch_0


  - alias: "Turn off cloak room light when no motion is detected"
    id: cloak_room_turn_light_off_when_no_motion_detected
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.cloak_room_occupancy
        to: 'off'
        for:
          minutes: 10
      - platform: homeassistant
        event: start
    condition:
      - condition: state
        entity_id: binary_sensor.cloak_room_occupancy
        state: 'off'
    action:
      - action: homeassistant.turn_off
        entity_id: switch.shellyplus2pm_fcb467a684e8_switch_0


  - alias: Toggle Switch Based on UPS Voltage
    initial_state: true
    mode: single
    id: cloak_room_turn_on_water_heater_after_power_failure
    trigger:
      - platform: numeric_state
        entity_id: sensor.ups_input_voltage
        below: 200

    action:
      - wait_for_trigger:
          - platform: numeric_state
            entity_id: sensor.ups_input_voltage
            above: 200
        continue_on_timeout: false
      - action: switch.toggle
        target:
          entity_id: switch.gas_water_heater
      - action: notify.ohad_whatsapp_api
        data:
          message: "Electricity power failure detected. The gas water heater has been reset, check that it's on"
          title: Appliance alert
          target: !secret rinat_benita_whatsapp_user_id
          data:
            media_url: {}
      - action: notify.ohad_telegram
        data_template:
          message: "Electricity power failure detected. The gas water heater has been reset, check that it's on"


  - alias: "Breaker Panel LED Control"
    id: cloak_room_breaker_panel_led_control
    description: "Gradually turn on the LED at 100% brightness and ~4000K white when the cabinet is opened (sensor on), and gradually turn it off when closed."
    trigger:
      - platform: state
        entity_id: binary_sensor.breaker_panel_01_contact
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: binary_sensor.breaker_panel_01_contact
                state: "on"
            sequence:
              - service: light.turn_on
                target:
                  entity_id: light.breaker_panel_led_01
                data:
                  brightness_pct: 100
          - conditions:
              - condition: state
                entity_id: binary_sensor.breaker_panel_01_contact
                state: "off"
            sequence:
              - service: light.turn_off
                target:
                  entity_id: light.breaker_panel_led_01
        default: []
    mode: single

  - alias: "Analyze gas water heater display when the sun sets"
    id: cloak_room_analyze_gas_water_heater_display
    initial_state: true
    trigger:
      platform: sun
      event: sunset

    action:
      - action: rest_command.analyze_gas_water_heater_display


  - alias: "Alert if water heater is out of order"
    id: cloak_room_gas_water_heater_check
    initial_state: true
    trigger:
      platform: sun
      event: sunset
      offset: '01:00:00'

    condition:
      - condition: template
        value_template: >-
          {{ not (state_attr('sensor.water_heater', 'is_out_of_order') == 'off' and is_state('sensor.water_heater', '45')) }}

    action:
      - action: camera.snapshot
        data:
          entity_id: camera.gas_heater_cam_gas_heater_esp32_cam
          filename: "/config/www/snapshots/gas_heater_cam_gas_heater_esp32_cam_snapshot.jpg"

      - delay: '00:00:02'

      - action: notify.ohad_telegram
        data:
          title: "Alert: Water heater malfunction"
          message: "Please check the heater display"
          data:
            photo:
              - file: "/config/www/snapshots/gas_heater_cam_gas_heater_esp32_cam_snapshot.jpg"
                caption: >-
                  [View Live Feed]({{ states('sensor.ha_base_url') }}/api/camera_proxy/camera.gas_heater_cam_gas_heater_esp32_cam?token={{ state_attr('camera.gas_heater_cam_gas_heater_esp32_cam', 'access_token') }})
                parse_mode: markdown
