---
automation:
  - alias: 'Announce dining room main shutter will not be closed'
    id: dining_room_main_window_shutter_close_skipped
    initial_state: false
    trigger:
      - platform: event
        event_type: alexa_actionable_notification
        event_data:
          event_id: actionable_notification_close_balcony_window
          event_response_type: ResponseNo
      - platform: event
        event_type: alexa_actionable_notification
        event_data:
          event_id: actionable_notification_close_balcony_window
          event_response_type: ResponseNone

    action:
      - action: notify.alexa_media
        data_template:
          data:
            type: tts
          target:
            - media_player.kitchen_echo
          message: >-
            I understand - I'll skip closing the balcony window shutter.
