---
automation:
  - alias: 'Close dining room shutters before sunset'
    id: dining_room_shutters_close_before_sunset
    initial_state: true
    trigger:
      - platform: sun
        event: sunset
        offset: "-03:00:00"

    condition:
      - condition: state
        entity_id: binary_sensor.dst
        state: 'on'

    action:
      - variables:
          right_window_position: "{{ state_attr('cover.shelly2pmg3_34cdb0776380_cover_0', 'current_position') }}"
          left_window_position: "{{ state_attr('cover.dining_room_left_window', 'current_position') }}"
          main_window_position: "{{ state_attr('cover.dining_room_main_window', 'current_position') }}"

      - action: cover.set_cover_position
        target:
          entity_id:
            - cover.shelly2pmg3_34cdb0776380_cover_0
        data:
          position: "{{ [right_window_position, 35] | min }}"

      - action: cover.set_cover_position
        target:
          entity_id:
            - cover.dining_room_left_window
        data:
          position: "{{ [left_window_position, 35] | min }}"

      - choose:
          - conditions:
              - condition: state
                entity_id:
                  - binary_sensor.dining_room_main_window_01_contact
                  - binary_sensor.dining_room_main_window_02_contact
                state: 'off'
            sequence:
              - action: cover.set_cover_position
                target:
                  entity_id: cover.dining_room_main_window
                data:
                  position: "{{ [main_window_position, 35] | min }}"
        default:
          - action: script.activate_alexa_actionable_notification
            data:
              text: 'I see the balcony window is open, should I close its shutter?'
              event_id: 'actionable_notification_close_balcony_window'
              alexa_device: 'media_player.kitchen_echo'


  - alias: 'Announce dining room main shutter will not be closed'
    id: dining_room_main_window_shutter_close_skipped
    initial_state: true
    trigger:
      - platform: event
        event_type: alexa_actionable_notification
        event_data:
          event_id: actionable_notification_close_balcony_window
          event_response_type: ResponseNo
      - platform: event
        event_type: alexa_actionable_notification
        event_data:
          event_id: actionable_notification_close_balcony_window
          event_response_type: ResponseNone

    action:
      - action: notify.alexa_media
        data_template:
          data:
            type: tts
          target:
            - media_player.kitchen_echo
          message: >-
            I understand - I'll skip closing the balcony window shutter.


  - alias: 'Close dining room main shutter via actionable notification'
    id: dining_room_main_window_shutter_close_actionable_notification
    initial_state: true
    trigger:
      - platform: event
        event_type: alexa_actionable_notification
        event_data:
          event_id: actionable_notification_close_balcony_window
          event_response_type: ResponseYes

    action:
      - action: notify.alexa_media
        data_template:
          data:
            type: tts
          target:
            - media_player.kitchen_echo
          message: >-
            Please close the window for me to be able to close the shutter.

      - wait_template: >
          {{ is_state('binary_sensor.dining_room_main_window_01_contact', 'off')
            and is_state('binary_sensor.dining_room_main_window_02_contact', 'off') }}
        timeout:
          minutes: 2
        continue_on_timeout: false

      - action: cover.set_cover_position
        target:
          entity_id:
            - cover.dining_room_main_window
            - cover.dining_room_left_window
            - cover.shelly2pmg3_34cdb0776380_cover_0
        data:
          position: "{{ [state_attr('cover.dining_room_main_window', 'current_position'), 15] | min }}"


  - alias: 'Close dining room shutters at night'
    id: dining_room_shutters_close_night
    initial_state: true
    trigger:
      - platform: time
        at: '21:00:00'

    condition:
      - condition: state
        entity_id: input_boolean.away_mode
        state: 'off'

    action:
      - choose:
          - conditions:
              - condition: state
                entity_id:
                  - binary_sensor.dining_room_main_window_01_contact
                  - binary_sensor.dining_room_main_window_02_contact
                state: 'off'
            sequence:
              - action: cover.set_cover_position
                target:
                  entity_id:
                    - cover.shelly2pmg3_34cdb0776380_cover_0
                    - cover.dining_room_main_window
                    - cover.dining_room_left_window
                data:
                  position: 15
        default:
          - action: script.activate_alexa_actionable_notification
            data:
              text: 'I see the balcony window is open, should I close its shutter?'
              event_id: 'actionable_notification_close_balcony_window'
              alexa_device: 'media_player.kitchen_echo'


  - alias: 'Close dining room shutters at night - complete'
    id: dining_room_shutters_close_night_complete
    initial_state: true
    trigger:
      - platform: time
        at: '00:00:00'

    condition:
      - condition: state
        entity_id: input_boolean.away_mode
        state: 'off'

    action:
      - action: cover.set_cover_position
        target:
          entity_id:
            - cover.shelly2pmg3_34cdb0776380_cover_0
            - cover.dining_room_main_window
            - cover.dining_room_left_window
        data:
          position: 0


  - alias: 'Open dining room shutters in the morning'
    id: dining_room_open_shutters_morning
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.kids_hallway_01_occupancy
        from: 'off'
        to: 'on'

    condition:
      condition: and
      conditions:
        - condition: template
          value_template: >-
            {{ as_timestamp(now()) - as_timestamp(state_attr('automation.open_dining_room_shutters_in_the_morning', 'last_triggered') or today_at('00:00')) | int > 28800 }}
        - condition: time
          after: '06:00:00'
          before: '10:00:00'
        - condition: state
          entity_id: input_boolean.away_mode
          state: 'off'

    action:
      - action: cover.set_cover_position
        data_template:
          entity_id: cover.dining_room_main_window
          position: >-
            {{ max(state_attr('cover.dining_room_main_window', 'current_position') | int, 100) }}

      - action: cover.set_cover_position
        data_template:
          entity_id: cover.shelly2pmg3_34cdb0776380_cover_0
          position: >-
            {{ max(state_attr('cover.shelly2pmg3_34cdb0776380_cover_0', 'current_position') | int, 70) }}

      - action: cover.set_cover_position
        data_template:
          entity_id: cover.dining_room_left_window
          position: >-
            {{ max(state_attr('cover.dining_room_left_window', 'current_position') | int, 70) }}


  - alias: 'Kitchen counter - Handle button actions'
    id: kitchen_counter_button_actions
    initial_state: true
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.kitchen_counter_01_action

    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: sensor.kitchen_counter_01_action
                state: 'button_1_single'
            sequence:
              - action: homeassistant.turn_on
                entity_id: switch.shelly1pmminig3_34b7da92245c_switch_0

          - conditions:
              - condition: state
                entity_id: sensor.kitchen_counter_01_action
                state: 'button_2_single'
            sequence:
              - action: homeassistant.turn_off
                entity_id: switch.shelly1pmminig3_34b7da92245c_switch_0
