---
automation:
  - alias: "Ella Room - Set AC to night mode (summer)"
    id: ella_room_ac_night_automation
    initial_state: true
    trigger:
      - platform: time
        at: "00:30:00"
      - platform: time
        at: "01:30:00"

    condition:
      condition: and
      conditions:
        - condition: template
          value_template: >-
            {{ not (
                is_state_attr('climate.ella_ac', 'temperature', 24) and
                is_state_attr('climate.ella_ac', 'fan_mode', 'low') and
                is_state_attr('climate.ella_ac', 'swing_mode', 'rangefull')
              )
            }}
        - condition: state
          entity_id: climate.ella_ac
          state: 'cool'

    action:
      - action: climate.set_temperature
        data:
          temperature: 24
          entity_id: climate.ella_ac
      - action: climate.set_fan_mode
        data:
          fan_mode: low
          entity_id: climate.ella_ac
      - action: climate.set_swing_mode
        data:
          swing_mode: rangefull
          entity_id: climate.ella_ac


  - alias: "Ella Room - Turn AC off when no one is in the room"
    id: ella_room_no_presence_turn_ac_off
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.apollo_msr_1_c17318_radar_target
        to: 'off'
        for:
          minutes: 10

    condition:
      condition: template
      value_template: >-
        {{ not is_state('climate.ella_ac', 'off') }}

    action:
      - action: climate.turn_off
        data_template:
          entity_id: climate.ella_ac


  - alias: 'Ella room - Handle Bedside button actions'
    id: ella_room_bedside_button_actions
    initial_state: true
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.ella_bedside_action

    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: sensor.ella_bedside_action
                state: 'single'
            sequence:
              - action: climate.toggle
                target:
                  entity_id: climate.ella_ac


  - alias: 'Ella room - Send a notification when Ketem tracker is charged'
    id: ella_room_notify_when_tracker_is_charged
    initial_state: true
    mode: single
    trigger:
      - platform: numeric_state
        entity_id: sensor.ketem_tracker_battery
        above: 99
        for:
          minutes: 5

    action:
      - choose:
          - conditions:
              - condition: numeric_state
                entity_id: sensor.home_ella_benita_distance
                below: 10000  # 10 km in meters
            sequence:
              - action: notify.ohad_whatsapp_api
                data:
                  message: "Ketem's GPS tracker is charged, please re-attach it"
                  title: Device notification
                  target: !secret ella_benita_whatsapp_user_id
                  data:
                    media_url: {}
        default:
          - action: notify.ohad_whatsapp_api
            data:
              message: 'הג׳יפיאס של כתם סיים להיטען, אנא חברי לה אותו בחזרה'
              title: Device notification
              target: !secret adi_benita_whatsapp_user_id
