---
automation:
  - alias: "Ella Room - Set AC to night mode (summer)"
    id: ella_room_ac_night_automation
    initial_state: true
    trigger:
      - platform: time
        at: "00:30:00"
      - platform: time
        at: "01:30:00"

    condition:
      condition: and
      conditions:
        - condition: template
          value_template: >-
            {{ not (
                is_state_attr('climate.ella_ac', 'temperature', 24) and
                is_state_attr('climate.ella_ac', 'fan_mode', 'low') and
                is_state_attr('climate.ella_ac', 'swing_mode', 'rangefull')
              )
            }}
        - condition: state
          entity_id: climate.ella_ac
          state: 'cool'

    action:
      - service: climate.set_temperature
        data:
          temperature: 24
          entity_id: climate.ella_ac
      - service: climate.set_fan_mode
        data:
          fan_mode: low
          entity_id: climate.ella_ac
      - service: climate.set_swing_mode
        data:
          swing_mode: rangefull
          entity_id: climate.ella_ac


  - alias: "Ella Room - Turn AC off when no one is in the room"
    id: ella_room_no_presence_turn_ac_off
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.apollo_msr_1_c17318_radar_target
        to: 'off'
        for:
          minutes: 10

    condition:
      condition: template
      value_template: >-
        {{ not is_state('climate.ella_ac', 'off') }}

    action:
      - service: climate.turn_off
        data_template:
          entity_id: climate.ella_ac
