---
template:
  - sensor:
      - name: "Ella Room AC Temperature"
        unit_of_measurement: "°C"
        state: "{{ state_attr('climate.ella_ac', 'current_temperature') }}"
        availability: "{{ state_attr('climate.ella_ac', 'current_temperature') is not none }}"
        device_class: temperature
        icon: mdi:thermometer

      - name: "Ella Room AC humidity"
        unit_of_measurement: "%"
        state: "{{ state_attr('climate.ella_ac', 'current_humidity') }}"
        availability: "{{ state_attr('climate.ella_ac', 'current_humidity') is not none }}"
        device_class: humidity
        icon: mdi:water-percent

      - name: "Ella room AC temperature difference"
        unit_of_measurement: "°C"
        state: "{{ (state_attr('climate.ella_ac', 'current_temperature') - state_attr('climate.ella_ac', 'temperature')) | abs }}"
        availability: "{{ state_attr('climate.ella_ac', 'current_temperature') is not none }}"
        device_class: temperature
        icon: mdi:thermometer


sensor:
  - platform: derivative
    source: sensor.ella_room_ac_temperature_difference
    name: Ella room temp difference change per 10 minutes
    round: 1
    unit_time: min
    time_window: 10

automation:
  - alias: Ella room shutdown AC 1 hour after target temperature has been reached
    id: ella_room_shutdown_ac_target_temp_reached
    initial_state: false
    trigger:
      - platform: numeric_state
        entity_id: sensor.ella_room_temp_difference_change_per_10_minutes
        above: -1
        below: 1
        for:
          hours: 1
      - platform: template
        value_template: >-
          {{
            states('climate.ella_ac') != 'off' and
            (now() - states.climate.ella_ac.last_changed).total_seconds() > 3600
          }}

    condition:
      - condition: template
        value_template: >
          {{
            states('climate.ella_ac') != 'off' and
            (now() - states.climate.ella_ac.last_changed).total_seconds() > 3600
          }}
      - condition: numeric_state
        entity_id: sensor.ella_room_temp_difference_change_per_10_minutes
        above: -1
        below: 1

    action:
      - action: climate.turn_off
        entity_id: climate.ella_ac


  - alias: "Ella Room - Set AC to night mode (summer)"
    id: ella_room_ac_night_automation
    initial_state: true
    trigger:
      - platform: time
        at: "00:30:00"
      - platform: time
        at: "01:30:00"

    condition:
      condition: and
      conditions:
        - condition: template
          value_template: >-
            {{ not (
                is_state_attr('climate.ella_ac', 'temperature', 24) and
                is_state_attr('climate.ella_ac', 'fan_mode', 'low') and
                is_state_attr('climate.ella_ac', 'swing_mode', 'rangefull')
              )
            }}
        - condition: state
          entity_id: climate.ella_ac
          state: 'cool'

    action:
      - action: climate.set_temperature
        data:
          temperature: 24
          entity_id: climate.ella_ac
      - action: climate.set_fan_mode
        data:
          fan_mode: low
          entity_id: climate.ella_ac
      - action: climate.set_swing_mode
        data:
          swing_mode: rangefull
          entity_id: climate.ella_ac


  - alias: "Ella Room - Turn AC off when no one is in the room"
    id: ella_room_no_presence_turn_ac_off
    initial_state: false
    trigger:
      - platform: state
        entity_id: binary_sensor.apollo_msr_1_c17318_radar_target
        to: 'off'
        for:
          minutes: 10

    condition:
      condition: template
      value_template: >-
        {{ not is_state('climate.ella_ac', 'off') }}

    action:
      - action: climate.turn_off
        data_template:
          entity_id: climate.ella_ac


  - alias: 'Ella room - Handle Bedside button actions'
    id: ella_room_bedside_button_actions
    initial_state: true
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.ella_bedside_action

    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: sensor.ella_bedside_action
                state: 'single'
            sequence:
              - action: switch.toggle
                target:
                  entity_id:
                    - switch.shelly2pmg3_8cbfea9f54b0_switch_0
                    - switch.shelly2pmg3_8cbfea9f54b0_switch_1
      - choose:
          - conditions:
              - condition: state
                entity_id: sensor.ella_bedside_action
                state: 'double'
            sequence:
              - choose:
                  - conditions:
                      - condition: state
                        entity_id: climate.ella_ac
                        state: 'off'
                    sequence:
                      - choose:
                          - conditions:
                              - condition: numeric_state
                                entity_id: sensor.openweathermap_feels_like_temperature
                                above: 23
                            sequence:
                              - service: climate.set_hvac_mode
                                target:
                                  entity_id: climate.ella_ac
                                data:
                                  hvac_mode: 'cool'
                        default:
                          - service: climate.set_hvac_mode
                            target:
                              entity_id: climate.ella_ac
                            data:
                              hvac_mode: 'heat'
                default:
                  - service: climate.turn_off
                    target:
                      entity_id: climate.ella_ac


  - alias: 'Ella room - Send a notification when Ketem tracker is charged'
    id: ella_room_notify_when_tracker_is_charged
    initial_state: true
    mode: single
    trigger:
      - platform: numeric_state
        entity_id: sensor.ketem_tracker_battery
        above: 99
        for:
          minutes: 5

    action:
      - choose:
          - conditions:
              - condition: numeric_state
                entity_id: sensor.home_ella_benita_distance
                below: 10000  # 10 km in meters
            sequence:
              - action: notify.mobile_app_ellas_iphone
                data:
                  message: "Ketem's GPS tracker is charged, please re-attach it"
                  title: Device notification
        default:
          - action: notify.mobile_app_adidibenita
            data:
              message: 'הג׳יפיאס של כתם סיים להיטען, אנא חברי לה אותו בחזרה'
              title: Device notification


  - alias: 'Ella room - Send a notification when Ketem tracker needs to be charged'
    id: ella_room_notify_when_tracker_needs_to_be_charged
    initial_state: true
    mode: single
    trigger:
      - platform: numeric_state
        entity_id: sensor.ketem_tracker_battery
        below: 15
        for:
          minutes: 5

    action:
      - choose:
          - conditions:
              - condition: numeric_state
                entity_id: sensor.home_ella_benita_distance
                below: 10000  # 10 km in meters
            sequence:
              - action: notify.mobile_app_ellas_iphone
                data:
                  message: "Ketem's GPS tracker needs to be charged"
                  title: Device notification
        default:
          - action: notify.mobile_app_adidibenita
            data:
              message: 'הסוללה בג׳יפיאס של כתם חלשה, אנא הטעיני אותו בהקדם'
              title: Device notification
