automation:
  - alias: Alert on Nuki low battery
    id: entrance_nuki_low_battery_alert
    initial_state: true
    trigger:
      platform: numeric_state
      entity_id: sensor.entrance_door_battery
      below: 80
      for:
        hours: 1

    action:
      - service: notify.mobile_app_ohadbenita
        data_template:
          title: "Appliances"
          message: "Nuki battery level is {{states('sensor.entrance_door_battery')}}%, please recharge the batteries"
