---
binary_sensor:
  - platform: template
    sensors:
      entrance_sensors_off_for_10_minutes:
        friendly_name: "Entrance sensors off for 10 Minutes"
        delay_on: "00:10:00"
        value_template: >
          {{ is_state('binary_sensor.entrance_door_occupancy', 'off') and
             is_state('binary_sensor.entrance_indoor_occupancy', 'off') and
             is_state('binary_sensor.entrance_door_contact', 'off') }}


automation:
  - alias: Alert on Nuki low battery
    id: entrance_nuki_low_battery_alert
    initial_state: true
    trigger:
      platform: numeric_state
      entity_id: sensor.entrance_door_battery
      below: 80
      for:
        hours: 1

    action:
      - action: notify.mobile_app_ohadbenita
        data_template:
          title: "Appliances"
          message: "Nuki battery level is {{states('sensor.entrance_door_battery')}}%, please recharge the batteries"


  - alias: "Turn on entrance light when motion is detected"
    id: entrance_lights_on_when_motion_detected
    initial_state: true
    mode: single
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.entrance_door_occupancy
          - binary_sensor.entrance_indoor_occupancy
          - binary_sensor.entrance_door_contact
        to: 'on'
      - platform: homeassistant
        event: start

    condition:
      condition: and
      conditions:
        - condition: or
          conditions:
            - condition: sun
              before: sunrise
              before_offset: "01:00:00"
            - condition: sun
              after: sunset
              after_offset: "-01:00:00"
        - condition: or
          conditions:
            - condition: state
              entity_id: binary_sensor.entrance_door_occupancy
              state: 'on'
            - condition: state
              entity_id: binary_sensor.entrance_indoor_occupancy
              state: 'on'
            - condition: state
              entity_id: binary_sensor.entrance_door_contact
              state: 'on'

    action:
      - action: homeassistant.turn_on
        entity_id: switch.shellyplus2pm_fcb467a684e8_switch_1


  - alias: "Turn off entrance light when motion is not detected"
    id: entrance_lights_off_when_motion_not_detected
    initial_state: true
    mode: single
    trigger:
      - platform: state
        entity_id: binary_sensor.entrance_sensors_off_for_10_minutes
        to: 'on'

    action:
      - action: homeassistant.turn_off
        target:
          entity_id: switch.shellyplus2pm_fcb467a684e8_switch_1
