---
automation:
  - alias: Alert on Nuki low battery
    id: entrance_nuki_low_battery_alert
    initial_state: true
    trigger:
      platform: numeric_state
      entity_id: sensor.entrance_door_battery
      below: 80
      for:
        hours: 1

    action:
      - action: notify.mobile_app_ohadbenita
        data_template:
          title: "Appliances"
          message: "Nuki battery level is {{states('sensor.entrance_door_battery')}}%, please recharge the batteries"


  - alias: "Turn on entrance light when motion is detected"
    id: entrance_lights_on_when_motion_detected
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.entrance_door_occupancy
        to: 'on'
      - platform: homeassistant
        event: start
    condition:
      - condition: state
        entity_id: binary_sensor.entrance_door_occupancy
        state: 'on'
    action:
      - action: homeassistant.turn_on
        entity_id: switch.shellyplus2pm_fcb467a684e8_switch_1


  - alias: "Turn off entrance light when motion is not detected"
    id: entrance_lights_off_when_motion_not_detected
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.entrance_door_occupancy
        to: 'off'
      - platform: homeassistant
        event: start
    condition:
      - condition: state
        entity_id: binary_sensor.entrance_door_occupancy
        state: 'off'
    action:
      - action: homeassistant.turn_off
        entity_id: switch.shellyplus2pm_fcb467a684e8_switch_1
