---
input_text:
  hass_last_notified_available_version:
    name: hass_last_notified_available_version
  hass_last_notified_upgraded_version:
    name: hass_last_notified_upgraded_version

  cover_dining_room_left_position:
    name: Dining Room Left Window Position
  cover_dining_room_right_position:
    name: Dining Room Right Window Position
  cover_dining_room_main_position:
    name: Dining Room Main Window Position
  cover_living_room_left_position:
    name: Living Room Left Window Position
  cover_living_room_right_position:
    name: Living Room Right Window Position
  cover_living_room_middle_position:
    name: Living Room Middle Window Position


input_number:
  battery_low_level_threshold:
    name: Battery Low Level Threshold
    initial: 50
    min: 20
    max: 80
    step: 5


input_boolean:
  skip_firmware_updates:
    name: Skip firmware checks by end of week
    icon: mdi:update


rest_command:
  shelly_calibrate_cover:
    url: "http://{{ shelly_ip }}/rpc"
    method: POST
    headers:
      content-type: "application/json"
    payload: '{"id":1,"method":"Cover.Calibrate","params":{"id":0}}'


sensor:
  - platform: rest
    name: Home Assistant Released Version
    scan_interval: 300
    json_attributes:
      - body
      - html_url
    resource: https://api.github.com/repos/home-assistant/home-assistant/releases/latest
    username: !secret github_username
    password: !secret github_access_token
    authentication: basic
    value_template: '{{ value_json.tag_name }}'
    headers:
      Accept: application/vnd.github.v3+json
      Content-Type: application/json
      User-Agent: Home Assistant REST sensor


automation:
  - alias: Notify HASS is online
    initial_state: true
    trigger:
      - platform: homeassistant
        event: start
    action:
      - action: notify.mobile_app_ohadbenita
        data:
          title: "HA Service"
          message: "🤖 HomeAssistant is online - {{ states('sensor.current_local_version') }}"


  - alias: Home Assistant Release Check
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.hass_docker_version_dockerhub_update_available
        to: 'on'

      - platform: homeassistant
        event: start

    condition:
      condition: and
      conditions:
        - condition: template
          value_template: >-
            {% if is_state('input_text.hass_last_notified_available_version', states('sensor.hass_docker_version')) %}
                False
            {% else %}
                True
            {% endif %}

    action:
      - action: notify.ohad_telegram
        data_template:
          message: >-
            A new version of Home Assistant is available, {{ states('sensor.hass_docker_version') }}, while existing local version is {{states('sensor.current_local_version') }}

            Link: {{ state_attr('sensor.home_assistant_released_version', 'html_url') }}

      - action: input_text.set_value
        data_template:
          entity_id: input_text.hass_last_notified_available_version
          value: "{{ states('sensor.hass_docker_version') }}"


  - alias: Notify if upgrade occurred
    id: ha_notify_on_upgrade
    initial_state: true
    trigger:
      - platform: homeassistant
        event: start

    condition:
      condition: and
      conditions:
        - condition: template
          value_template: >-
            {% if is_state('input_text.hass_last_notified_upgraded_version', states('sensor.current_local_version')) %}
                False
            {% else %}
                True
            {% endif %}

    action:
      - action: notify.ohad_telegram
        data_template:
          message: >-
            HASS has been upgraded from {{states('input_text.hass_last_notified_upgraded_version')}} to {{states('sensor.current_local_version')}}, you can find the release notes @ https://github.com/home-assistant/home-assistant/releases/{{states('sensor.current_local_version')}}

      - action: input_text.set_value
        data_template:
          entity_id: input_text.hass_last_notified_upgraded_version
          value: "{{ states('sensor.current_local_version') }}"


  - alias: Notify when Zigbee sensors go offline
    id: ha_zigbee_sensor_offline_notification
    initial_state: true
    mode: queued
    max: 5
    trigger:
      - platform: mqtt
        topic: z2m-mainfloor/+/availability
        payload: offline

    action:
      - action: notify.ohad_telegram
        data:
          message: |
            {{ trigger.topic.split('/')[1] }} is {{ trigger.payload }}


  - alias: Notify when core network devices are offline
    id: ha_core_devices_availability_check
    mode: single
    initial_state: true
    trigger:
      - platform: template
        value_template: >
          {% set core_devices = [
            'lock.entrance_door',
            'lock.kitchen_door',
            'lock.kids_bathroom_door',
            'switch.irrigation_l1',
            'climate.living_room_ac',
            'climate.master_bedroom_ac',
            'climate.ella_ac',
            'cover.living_room_left_window',
            'cover.living_room_middle_window',
            'cover.living_room_right_window',
            'cover.dining_room_right_window',
            'cover.dining_room_left_window',
            'cover.dining_room_main_window',
            'switch.shellyplus2pm_fcb4670e68e8_switch_0',
            'switch.shellyplus2pm_fcb4670e68e8_switch_1',
            'switch.shelly1_34945470bfa1',
            'switch.shelly1_e8db84d27b53'
          ] %}
          {% from 'availability_template.jinja' import avail %}
          {{- not (avail(core_devices) | bool) -}}
    action:
      - service: notify.ohad_telegram
        data:
          message: >
            The following devices are offline:
            {%- for entity_id in [
              'lock.entrance_door',
              'lock.kitchen_door',
              'lock.kids_bathroom_door',
              'switch.irrigation_l1',
              'climate.living_room_ac',
              'climate.master_bedroom_ac',
              'climate.ella_ac',
              'cover.living_room_left_window',
              'cover.living_room_middle_window',
              'cover.living_room_right_window',
              'cover.dining_room_right_window',
              'cover.dining_room_left_window',
              'cover.dining_room_main_window',
              'switch.shellyplus2pm_fcb4670e68e8_switch_0',
              'switch.shellyplus2pm_fcb4670e68e8_switch_1',
              'switch.shelly1_34945470bfa1',
              'switch.shelly1_e8db84d27b53'
            ] -%}
              {% if states(entity_id) == 'unknown' or is_state(entity_id, 'unavailable') %}
                - {{ state_attr(entity_id, 'friendly_name') | replace("_", "\\_") }} - {{ entity_id | replace("_", "\\_") }}
              {%- endif -%}
              {%- endfor -%}

  - alias: "Weekly Battery Level Check"
    id: ha_weekly_battery_level_check
    initial_state: true
    trigger:
      platform: time
      at: "09:00:00"
    condition:
      condition: time
      weekday:
        - sun
    action:
      - variables:
          threshold: "{{ states('input_number.battery_low_level_threshold') | int }}"
          exclude:
            entity_id:
              - sensor.ellas_iphone_battery_level
              - sensor.ohadbenita_battery_level
              - sensor.rinats_iphone_battery_level
              - sensor.rois_iphone_battery_level
          low_battery_devices: >
            {% set threshold = states('input_number.battery_low_level_threshold') | int %}
            {% set exclude = exclude %}
            {% set result = namespace(sensors=[]) %}
            {% for state in states.sensor | selectattr('attributes.device_class', '==', 'battery') %}
              {% if 0 <= state.state | int(-1) < threshold and not state.entity_id in exclude.entity_id %}
                {% set result.sensors = result.sensors + [state.name ~ ' (' ~ state.state ~ '%)'] %}
              {% endif %}
            {% endfor %}
            {% for state in states.binary_sensor | selectattr('attributes.device_class', '==', 'battery') | selectattr('state', '==', 'on') %}
              {% if not state.entity_id in exclude.entity_id %}
                {% set result.sensors = result.sensors + [state.name] %}
              {% endif %}
            {% endfor %}
            {{ result.sensors | join('\n') }}
      - choose:
        - conditions:  # yamllint disable-line rule:indentation
            - condition: template
              value_template: "{{ low_battery_devices | length > 0 }}"
          sequence:
            - action: notify.ohad_telegram
              data:
                title: "Low Battery Alert"
                message: >
                  The following devices have low battery levels (below {{ threshold }}%):
                  {{ low_battery_devices }}
        default:
          - action: notify.ohad_telegram
            data:
              title: "Battery Check"
              message: "All devices have sufficient battery levels."


  - alias: "Notify on low battery levels - sensor-based"
    id: ha_battery_level_notification_sensor_based
    initial_state: true
    mode: queued
    max: 5
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.entrance_door_battery_low
          - binary_sensor.kids_bathroom_door_battery_low
          - binary_sensor.kitchen_door_battery_low
          - binary_sensor.kitchen_sink_battery_low
          - binary_sensor.kitchen_ceiling_battery_low
        to: 'on'
    action:
      - service: persistent_notification.create
        data:
          title: "Low Battery Alert"
          message: >
            The {{ trigger.to_state.attributes.friendly_name }} has a low battery.


  - alias: "Check for Pending Device Firmware Updates"
    id: ha_check_for_pending_firmware_updates
    description: "Send a Telegram message if there are pending updates for devices"
    initial_state: true
    trigger:
      - platform: homeassistant
        event: start
      - platform: template
        value_template: >
          {{ states.update | selectattr('attributes.device_class', 'eq', 'firmware') | selectattr('state', 'eq', 'on') | list | count > 0 }}
      - platform: state
        entity_id: input_boolean.skip_firmware_updates
        to: 'off'

    condition:
      - condition: template
        value_template: >
          {{ states.update | selectattr('attributes.device_class', 'eq', 'firmware') | selectattr('state', 'eq', 'on') | list | count > 0 }}
      - condition: state
        entity_id: input_boolean.skip_firmware_updates
        state: 'off'

    action:
      - action: notify.ohad_telegram
        data:
          message: >
            {% set updates = states.update | selectattr('attributes.device_class', 'eq', 'firmware') | selectattr('state', 'eq', 'on') | list %}
            {% if updates | count > 0 %}
            There are pending firmware updates for the following devices:
            {%- for update in updates %}
              {% set release_url = update.attributes.release_url %}
              - Entity: {{ update.entity_id | replace('_', '\_') }} - Installed: {{ update.attributes.installed_version }} | Available: [{{ update.attributes.latest_version }}]({{ release_url }})
            {%- endfor %}
            Do you want to update now?
            {% else %}
            There are no pending firmware updates at this time.
            {% endif %}
          data:
            parse_mode: markdown
            inline_keyboard:
              - "Update Now:/trigger_firmware_update, Snooze Updates (EOW):/snooze_firmware_updates"


  - alias: "Trigger Firmware Update via Telegram"
    id: ha_check_trigger_firmware_updates
    description: "Trigger firmware update when the user responds via Telegram."
    initial_state: true
    trigger:
      - platform: event
        event_type: telegram_callback
        event_data:
          data: "/trigger_firmware_update"

    action:
      - action: update.install
        data_template:
          entity_id: >
            {{ states.update | selectattr('attributes.device_class', 'eq', 'firmware') | selectattr('state', 'eq', 'on') | map(attribute='entity_id') | list }}

      - action: notify.ohad_telegram
        data:
          message: "Triggered installation of pending firmware updates"


  - alias: "Update check firmware skipped helper"
    id: ha_update_firmware_update_skipped_helper
    description: "Turn firmware check skipped when the user responds via Telegram."
    initial_state: true
    trigger:
      - platform: event
        event_type: telegram_callback
        event_data:
          data: "/snooze_firmware_updates"

    action:
      - action: input_boolean.turn_on
        entity_id: input_boolean.skip_firmware_updates

      - action: notify.ohad_telegram
        data:
          message: "Update check will be snoozed by end of week"


  - alias: Reset Firmware Check helper
    id: ha_reset_firmware_check_helper
    initial_state: true
    trigger:
      platform: time
      at: '02:00:00'
    condition:
      condition: and
      conditions:
        - condition: time
          weekday:
            - "sun"
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.skip_firmware_updates


  - alias: Alert on Synology disk issues
    id: ha_synology_alert_on_disk_issues
    initial_state: true
    trigger:
      - platform: state
        entity_id:
          - sensor.benita_nas_drive_1_status
          - sensor.benita_nas_drive_2_status
          - sensor.benita_nas_drive_3_status
          - sensor.benita_nas_drive_4_status
        from: 'normal'

    action:
      - action: notify.ohad_telegram
        data_template:
          message: One of the Synology disks is malfunctioning, please check it as soon as possible.


  - alias: Notify when Synology security status is unsafe
    id: ha_synology_security_status_check
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.benita_nas_security_status
      to: 'on'

    action:
      - action: notify.ohad_telegram
        data:
          title: "Synology security status - unsafe"
          message: "Synology's security status changed to unsafe, please check security advisor for recent findings and recommendations"


  - alias: Perform daily backup
    id: ha_perform_daily_backup
    trigger:
      - platform: time
        at: "02:00:00"
    action:
      - action: auto_backup.backup_full
        data:
          name: "DailyBackup: {{ now().strftime('%A, %B %-d, %Y') }}"
          keep_days: 14


  - alias: Notify on backup failure
    id: ha_notify_on_backup_failure
    trigger:
      platform: event
      event_type: auto_backup.backup_failed
    action:
      - action: persistent_notification.create
        data:
          title: "HA backup Failed"
          message: |-
            Name: {{ trigger.event.data.name }}
            Error: {{ trigger.event.data.error }}

      - action: notify.ohad_telegram
        data:
          title: "HA backup Failed"
          message: >-
            Name: {{ trigger.event.data.name }}
            Error: {{ trigger.event.data.error }}


  - alias: "Monthly Cover Calibration"
    trigger:
      platform: time
      at: "12:00:00"
    condition:
      - condition: template
        value_template: "{{ now().day == 1 }}"  # Runs on the 1st of the month
    action:
      # Store current positions into input_text entities
      - action: input_text.set_value
        data_template:
          entity_id: input_text.cover_dining_room_left_position
          value: "{{ state_attr('cover.dining_room_left_window', 'current_position') }}"
      - action: input_text.set_value
        data_template:
          entity_id: input_text.cover_dining_room_right_position
          value: "{{ state_attr('cover.dining_room_right_window', 'current_position') }}"
      - action: input_text.set_value
        data_template:
          entity_id: input_text.cover_dining_room_main_position
          value: "{{ state_attr('cover.dining_room_main_window', 'current_position') }}"
      - action: input_text.set_value
        data_template:
          entity_id: input_text.cover_living_room_left_position
          value: "{{ state_attr('cover.living_room_left_window', 'current_position') }}"
      - action: input_text.set_value
        data_template:
          entity_id: input_text.cover_living_room_right_position
          value: "{{ state_attr('cover.living_room_right_window', 'current_position') }}"
      - action: input_text.set_value
        data_template:
          entity_id: input_text.cover_living_room_middle_position
          value: "{{ state_attr('cover.living_room_middle_window', 'current_position') }}"

      - variables:
          cover_ip_map:
            cover.dining_room_left_window: '172.16.1.237'
            cover.dining_room_right_window: '172.16.1.181'
            cover.dining_room_main_window: '172.16.1.189'
            cover.living_room_left_window: '172.16.1.68'
            cover.living_room_right_window: '172.16.1.28'
            cover.living_room_middle_window: '172.16.1.208'

      # Calibrate covers by iterating over entity IDs and fetching IPs
      - repeat:
          count: "{{ cover_ip_map | length }}"
          sequence:
            - action: rest_command.shelly_calibrate_cover
              data:
                shelly_ip: "{{ cover_ip_map[(cover_ip_map.keys() | list)[repeat.index -1]] }}"

      # Wait 10 minutes after calibration
      - delay: "00:10:00"

      # Restore positions from input_text entities
      - action: cover.set_cover_position
        target:
          entity_id: cover.dining_room_left_window
        data_template:
          position: "{{ states('input_text.cover_dining_room_left_position') | int }}"
      - action: cover.set_cover_position
        target:
          entity_id: cover.dining_room_right_window
        data_template:
          position: "{{ states('input_text.cover_dining_room_right_position') | int }}"
      - action: cover.set_cover_position
        target:
          entity_id: cover.dining_room_main_window
        data_template:
          position: "{{ states('input_text.cover_dining_room_main_position') | int }}"
      - action: cover.set_cover_position
        target:
          entity_id: cover.living_room_left_window
        data_template:
          position: "{{ states('input_text.cover_living_room_left_position') | int }}"
      - action: cover.set_cover_position
        target:
          entity_id: cover.living_room_right_window
        data_template:
          position: "{{ states('input_text.cover_living_room_right_position') | int }}"
      - action: cover.set_cover_position
        target:
          entity_id: cover.living_room_middle_window
        data_template:
          position: "{{ states('input_text.cover_living_room_middle_position') | int }}"


  - alias: "Alert on Grisha's bin being full"
    id: ha_alert_grisha_bin_full
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.grisha_bin_full
      to: 'on'

    action:
      - action: notify.ohad_telegram
        data:
          message: "[Device maintenance] Grisha's bin is full."
