---
input_text:
  hass_last_notified_available_version:
    name: hass_last_notified_available_version

  hass_last_notified_upgraded_version:
    name: hass_last_notified_upgraded_version

input_number:
  battery_low_level_threshold:
    name: Battery Low Level Threshold
    initial: 50
    min: 20
    max: 80
    step: 5

sensor:
  - platform: rest
    name: Home Assistant Released Version
    scan_interval: 300
    json_attributes:
      - body
      - html_url
    resource: https://api.github.com/repos/home-assistant/home-assistant/releases/latest
    username: !secret github_username
    password: !secret github_access_token
    authentication: basic
    value_template: '{{ value_json.tag_name }}'
    headers:
      Accept: application/vnd.github.v3+json
      Content-Type: application/json
      User-Agent: Home Assistant REST sensor


automation:
  - alias: Notify HASS is online
    initial_state: true
    trigger:
      - platform: homeassistant
        event: start
    action:
      - action: notify.mobile_app_ohadbenita
        data:
          title: "HA Service"
          message: "🤖 HomeAssistant is online - {{ states('sensor.current_local_version') }}"


  - alias: Home Assistant Release Check
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.hass_docker_version_dockerhub_update_available
        to: 'on'

      - platform: homeassistant
        event: start

    condition:
      condition: and
      conditions:
        - condition: template
          value_template: >-
            {% if is_state('input_text.hass_last_notified_available_version', states('sensor.hass_docker_version')) %}
                False
            {% else %}
                True
            {% endif %}

    action:
      - action: notify.ohad_telegram
        data_template:
          message: >-
            A new version of Home Assistant is available, {{ states('sensor.hass_docker_version') }}, while existing local version is {{states('sensor.current_local_version') }}

            Link: {{ state_attr('sensor.home_assistant_released_version', 'html_url') }}

      - action: input_text.set_value
        data_template:
          entity_id: input_text.hass_last_notified_available_version
          value: "{{ states('sensor.hass_docker_version') }}"


  - alias: Notify if upgrade occurred
    id: ha_notify_on_upgrade
    initial_state: true
    trigger:
      - platform: homeassistant
        event: start

    condition:
      condition: and
      conditions:
        - condition: template
          value_template: >-
            {% if is_state('input_text.hass_last_notified_upgraded_version', states('sensor.current_local_version')) %}
                False
            {% else %}
                True
            {% endif %}

    action:
      - action: notify.ohad_telegram
        data_template:
          message: >-
            HASS has been upgraded from {{states('input_text.hass_last_notified_upgraded_version')}} to {{states('sensor.current_local_version')}}, you can find the release notes @ https://github.com/home-assistant/home-assistant/releases/{{states('sensor.current_local_version')}}

      - action: input_text.set_value
        data_template:
          entity_id: input_text.hass_last_notified_upgraded_version
          value: "{{ states('sensor.current_local_version') }}"


  - alias: Notify when Zigbee sensors go offline
    id: ha_zigbee_sensor_offline_notification
    initial_state: true
    trigger:
      - platform: mqtt
        topic: z2m-mainfloor/+/availability
        payload: offline

    action:
      - action: notify.ohad_telegram
        data:
          message: |
            {{ trigger.topic.split('/')[1] }} is {{ trigger.payload }}
    mode: queued
    max: 10


  - alias: "Weekly Battery Level Check"
    id: ha_weekly_battery_level_check
    trigger:
      platform: time
      at: "09:00:00"
    condition:
      condition: time
      weekday:
        - sun
    action:
      - variables:
          threshold: "{{ states('input_number.battery_low_level_threshold') | int }}"
          exclude:
            entity_id:
              - sensor.ellas_iphone_battery_level
              - sensor.ohadbenita_battery_level
              - sensor.rinats_iphone_battery_level
              - sensor.rois_iphone_battery_level
          low_battery_devices: >
            {% set threshold = states('input_number.battery_low_level_threshold') | int %}
            {% set exclude = exclude %}
            {% set result = namespace(sensors=[]) %}
            {% for state in states.sensor | selectattr('attributes.device_class', '==', 'battery') %}
              {% if 0 <= state.state | int(-1) < threshold and not state.entity_id in exclude.entity_id %}
                {% set result.sensors = result.sensors + [state.name ~ ' (' ~ state.state ~ '%)'] %}
              {% endif %}
            {% endfor %}
            {% for state in states.binary_sensor | selectattr('attributes.device_class', '==', 'battery') | selectattr('state', '==', 'on') %}
              {% if not state.entity_id in exclude.entity_id %}
                {% set result.sensors = result.sensors + [state.name] %}
              {% endif %}
            {% endfor %}
            {{ result.sensors | join('\n') }}
      - choose:
        - conditions:  # yamllint disable-line rule:indentation
            - condition: template
              value_template: "{{ low_battery_devices | length > 0 }}"
          sequence:
            - action: notify.ohad_telegram
              data:
                title: "Low Battery Alert"
                message: >
                  The following devices have low battery levels (below {{ threshold }}%):
                  {{ low_battery_devices }}
        default:
          - action: notify.ohad_telegram
            data:
              title: "Battery Check"
              message: "All devices have sufficient battery levels."
