---
template:
  - binary_sensor:
      - name: "Washing machine active"
        state: "{{ states('sensor.washing_machine_energy_power') | default(0) | float > 5 }}"
      - name: "Kids bathroom occupancy"
        device_class: occupancy
        state: >-
          {% set s1 = states('binary_sensor.occupancy_sensor_808b_occupancy') %}
          {% set s2 = states('binary_sensor.occupancy_sensor_a5d0_occupancy') %}
          {% if 'unavailable' in [s1, s2] %}
            'unavailable'
          {% elif s1 == 'on' or s2 == 'on' %}
            on
          {% else %}
            off
          {% endif %}

automation:
  - alias: Announce washing machine cycle completed
    id: kids_bathroom_announce_washing_machine_cycle_completed
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.washing_machine_active
        from: 'on'
        to: 'off'
        for:
          minutes: 5
    condition:
      - condition: numeric_state
        entity_id: sensor.home_ella_benita_distance
        below: 10000  # 10 km in meters
    action:
      - action: notify.mobile_app_ellas_iphone
        data:
          message: Washing machine cycle complete, please hang the clothes to dry
          title: Chore notification


  - alias: Kids bathroom water Leak detection
    id: kids_bathroom_water_leak_detection
    initial_state: true
    trigger:
      - entity_id:
          - binary_sensor.kids_bathroom_sink_water_leak
        platform: state
        to: 'on'
    action:
      - action: notify.ohad_telegram
        data_template:
          message: "Water leak has been detected @ {{ trigger.from_state.attributes.friendly_name }} !!!"


  - alias: "Turn off kids bathroom lights when no motion is detected"
    id: kids_bathroom_turn_light_off_no_motion_detected
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.kids_bathroom_occupancy
        to: 'off'
        for:
          minutes: 15

      - platform: homeassistant
        event: start

    condition:
      - condition: state
        entity_id: binary_sensor.kids_bathroom_occupancy
        state: 'off'

    action:
      - action: homeassistant.turn_off
        entity_id: switch.shellyplus2pm_fcb467a557a0_switch_1
