---
template:
  - binary_sensor:
      - name: "Washing machine active"
        state: "{{ states('sensor.washing_machine_energy_power') | default(0) | float > 5 }}"
      - name: "Kids bathroom occupancy"
        device_class: occupancy
        state: >-
          {% set s1 = states('binary_sensor.occupancy_sensor_808b_occupancy') %}
          {% set s2 = states('binary_sensor.occupancy_sensor_a5d0_occupancy') %}
          {% if 'unavailable' in [s1, s2] %}
            'unavailable'
          {% elif s1 == 'on' or s2 == 'on' %}
            on
          {% else %}
            off
          {% endif %}

automation:
  - alias: Announce washing machine cycle completed
    id: kids_bathroom_announce_washing_machine_cycle_completed
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.washing_machine_active
        from: 'on'
        to: 'off'
        for:
          minutes: 5
    condition:
      - condition: numeric_state
        entity_id: sensor.home_ella_benita_distance
        below: 10000  # 10 km in meters
    action:
      - action: notify.mobile_app_ellas_iphone
        data:
          message: Washing machine cycle complete, please hang the clothes to dry
          title: Chore notification


  - alias: Kids bathroom water Leak detection
    id: kids_bathroom_water_leak_detection
    initial_state: false
    trigger:
      - entity_id:
          - binary_sensor.kids_bathroom_water_leak
          - binary_sensor.washing_machine_water_leak
        platform: state
        to: 'on'
    action:
      - action: notify.send_message
        data:
          entity_id: notify.telegram_bot_659000495_155103022
          message: "Water leak has been detected @ {{ trigger.from_state.attributes.friendly_name }} !!!"


  - alias: "Turn off kids bathroom lights when no motion is detected"
    id: kids_bathroom_turn_light_off_no_motion_detected
    initial_state: false
    trigger:
      - platform: state
        entity_id: binary_sensor.kids_bathroom_occupancy
        to: 'off'
        for:
          minutes: 5

      - platform: homeassistant
        event: start

    condition:
      - condition: state
        entity_id: binary_sensor.kids_bathroom_occupancy
        state: 'off'

    action:
      - action: homeassistant.turn_off
        entity_id: switch.shellyplus2pm_fcb467a557a0_switch_1


  - alias: 'Kids bathroom i4 switches - Toggle clinic door lock'
    id: kids_bathroom_switch_button_actions
    initial_state: true
    mode: single

    trigger:
      - platform: state
        entity_id: binary_sensor.kids_bathroom_entrance_i4_switches_input_0
        from:
          - 'on'
          - 'off'
        to:
          - 'on'
          - 'off'

    condition:
      - condition: state
        entity_id: input_boolean.away_mode
        state: 'off'

    action:
      - variables:
          was_locked: "{{ is_state('lock.clinic_door', 'locked') }}"

      - action: script.alexa_notification
        data:
          alexa_device: media_player.kids_bathroom_echo
          volume: 0.4
          message: >
            Clinic door is now {{ 'unlocked' if was_locked else 'locked' }}

      - choose:
          - conditions:
              - condition: template
                value_template: "{{ was_locked }}"
            sequence:
              - action: lock.unlock
                target:
                  entity_id: lock.clinic_door
        default:
          - action: lock.lock
            target:
              entity_id: lock.clinic_door
