---
binary_sensor:
  - platform: template
    sensors:
      dishwasher_active:
        value_template: "{{ states('sensor.athom_02_energy_power') | float > 5 }}"


automation:
  - alias: Water Leak detection
    id: kitchen_water_leak_detection
    initial_state: true
    trigger:
      - entity_id:
          - binary_sensor.kitchen_sink_water_leak
        platform: state
        to: 'on'
    action:
      - action: notify.ohad_telegram
        data_template:
          message: "Water leak has been detected @ {{ trigger.from_state.attributes.friendly_name }} !!!"

  - alias: Smnoke detection on
    id: kitchen_smoke_detection_on
    initial_state: true
    trigger:
      - entity_id: binary_sensor.kitchen_ceiling_smoke
        platform: state
        from: 'off'
        to: 'on'
    action:
      - action: notify.ohad_telegram
        data_template:
          message: "Smoke has been detected"
      - action: notify.mobile_app_ohadbenita
        data_template:
          title: "Hazards"
          message: "Smoke has been detected, density is {{states('sensor.kitchen_ceiling_smoke_density')}}%"

  - alias: Smnoke detection off
    id: kitchen_smoke_detection_off
    initial_state: true
    trigger:
      - entity_id: binary_sensor.kitchen_ceiling_smoke
        platform: state
        from: 'on'
        to: 'off'
    action:
      - action: notify.ohad_telegram
        data_template:
          message: "Smoke is not detected anymore"
      - action: notify.mobile_app_ohadbenita
        data_template:
          title: "Hazards"
          message: "Smoke is not detected, density is {{states('sensor.kitchen_ceiling_smoke_density')}}%"


  - alias: Pantry lights - turn on when motion detected
    id: kitchen_pantry_lights_on_motion_detected
    initial_state: true
    trigger:
      - entity_id: binary_sensor.pantry_occupancy
        platform: state
        from: 'off'
        to: 'on'
      - platform: state
        entity_id: binary_sensor.kitchen_door_contact
        to: 'on'
    action:
      - action: homeassistant.turn_on
        entity_id:
          - switch.shellyplus2pm_d48afc581860_switch_0  # indoor light


  - alias: Pantry lights - turn off when no motion detected
    id: kitchen_pantry_lights_off_no_motion
    initial_state: true
    trigger:
      - entity_id: binary_sensor.pantry_occupancy
        platform: state
        to: 'off'
        for:
          minutes: 5
    action:
      - action: homeassistant.turn_off
        entity_id:
          - switch.shellyplus2pm_d48afc581860_switch_0  # indoor light


  - alias: 'Turn on kitchen lights upon first movement in the morning'
    id: kitchen_turn_on_light_morning_first_movement
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.entrance_to_living_room_01_occupancy
        from: 'off'
        to: 'on'

    condition:
      condition: and
      conditions:
        - condition: template
          value_template: >-
            {{ as_timestamp(now()) - as_timestamp(state_attr('automation.turn_on_kitchen_lights_upon_first_movement_in_the_morning', 'last_triggered') or today_at('00:00')) | int > 14400 }}
        - condition: time
          after: '06:30:00'
          before: '10:00:00'
        - condition: state
          entity_id: input_boolean.away_mode
          state: 'off'

    action:
      - action: homeassistant.turn_on
        entity_id:
          - switch.shellyplus2pm_fcb4670e68e8_switch_0
          - switch.shellyplus2pm_fcb4670e68e8_switch_1

  - alias: Announce Dishwasher cycle completed
    id: kitchen_announce_dishwasher_cycle_completed
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.dishwasher_active
        from: 'on'
        to: 'off'
        for:
          minutes: 33
    condition:
      condition: and
      conditions:
        - condition: template  # 2 hours
          value_template: >-
            {{as_timestamp(now()) - as_timestamp(state_attr('automation.announce_dishwasher_cycle_completed', 'last_triggered')) | int > 7200}}

    action:
      - action: notify.ohad_whatsapp_api
        data:
          message: Diswasher cycle complete, please unload the dishes
          title: Chore notification
          target: !secret roi_benita_whatsapp_user_id
          data:
            media_url: {}


  # maps:
  #   - flag: 0
  #     name: Main floor
  #     rooms:
  #       "16": Living room
  #       "17": Living room1
  #       "18": Kitchen
  #       "19": Study
  #       "20": Corridor
  #       "21": Corridor1
  #       "22": Guest bedroom
  #       "23": Dining room1
  #       "24": Hall
  #       "25": Living room2


  - alias: Tami4 button - dock Yulanda
    id: kitchen_yulanda_dock_button_press
    initial_state: false
    trigger:
      - platform: state
        entity_id: sensor.kitchen_tami4_action
        to: '1_single'

    action:
      - action: vacuum.return_to_base
        target:
          entity_id: vacuum.yulanda

      - action: script.alexa_notification
        data:
          alexa_device: media_player.kitchen_echo
          notification_type: announce
          current_volume: >-
            {{ state_attr('media_player.kitchen_echo', 'volume_level') }}
          message: >-
            I just sent Yulanda to its dock


  - alias: Tami4 button - Send Yulanda to clean the kitchen
    id: kitchen_yulanda_clean_kitchen_button_press
    initial_state: true
    trigger:
      - platform: state
        entity_id: sensor.kitchen_tami4_action
        to: '2_single'

    action:
      - action: vacuum.send_command
        data:
          command: app_segment_clean
          params:
            - segments:
                - 18
              repeat: 2
        target:
          entity_id: vacuum.yulanda

      - action: script.alexa_notification
        data:
          alexa_device: media_player.kitchen_echo
          notification_type: announce
          current_volume: >-
            {{ state_attr('media_player.kitchen_echo', 'volume_level') }}
          message: >-
            I just sent Yulanda to clean the kitchen


  - alias: Tami4 button - Send Yulanda to clean the dining room
    id: kitchen_yulanda_clean_dining_room_button_press
    initial_state: true
    trigger:
      - platform: state
        entity_id: sensor.kitchen_tami4_action
        to: '3_single'

    action:
      - action: vacuum.send_command
        data:
          command: app_segment_clean
          params:
            - segments:
                - 23
              repeat: 2
        target:
          entity_id: vacuum.yulanda

      - action: script.alexa_notification
        data:
          alexa_device: media_player.kitchen_echo
          notification_type: announce
          current_volume: >-
            {{ state_attr('media_player.kitchen_echo', 'volume_level') }}
          message: >-
            I just sent Yulanda to clean the dining room


  - alias: Tami4 button - Send Yulanda to clean the entire floor
    id: kitchen_yulanda_clean_entire_floor
    initial_state: true
    trigger:
      - platform: state
        entity_id: sensor.kitchen_tami4_action
        to: '4_single'

    action:
      - action: vacuum.start
        target:
          entity_id: vacuum.yulanda

      - action: script.alexa_notification
        data:
          alexa_device: media_player.kitchen_echo
          notification_type: announce
          current_volume: >-
            {{ state_attr('media_player.kitchen_echo', 'volume_level') }}
          message: >-
            I just sent Yulanda to clean the entire floor
