---
automation:
  - alias: Water Leak detection
    id: kitchen_water_leak_detection
    initial_state: true
    trigger:
      - entity_id:
          - binary_sensor.kitchen_sink_water_leak
        platform: state
        to: 'on'
    action:
      - action: notify.ohad_telegram
        data_template:
          message: "Water leak has been detected @ {{ trigger.from_state.attributes.friendly_name }} !!!"

  - alias: Smnoke detection on
    id: kitchen_smoke_detection_on
    initial_state: true
    trigger:
      - entity_id: binary_sensor.kitchen_ceiling_smoke
        platform: state
        from: 'off'
        to: 'on'
    action:
      - action: notify.ohad_telegram
        data_template:
          message: "Smoke has been detected"
      - action: notify.mobile_app_ohadbenita
        data_template:
          title: "Hazards"
          message: "Smoke has been detected, density is {{states('sensor.kitchen_ceiling_smoke_density')}}%"

  - alias: Smnoke detection off
    id: kitchen_smoke_detection_off
    initial_state: true
    trigger:
      - entity_id: binary_sensor.kitchen_ceiling_smoke
        platform: state
        from: 'on'
        to: 'off'
    action:
      - action: notify.ohad_telegram
        data_template:
          message: "Smoke is not detected anymore"
      - action: notify.mobile_app_ohadbenita
        data_template:
          title: "Hazards"
          message: "Smoke is not detected, density is {{states('sensor.kitchen_ceiling_smoke_density')}}%"


  - alias: Pantry lights - turn off when motion detected
    id: kitchen_pantry_lights_on_motion_detected
    initial_state: true
    trigger:
      - entity_id: binary_sensor.pantry_occupancy
        platform: state
        from: 'off'
        to: 'on'
    action:
      - action: homeassistant.turn_on
        entity_id:
          - switch.shellyplus2pm_d48afc581860_switch_0
          - switch.shellyplus2pm_d48afc581860_switch_1


  - alias: Pantry lights - turn off when no motion detected
    id: kitchen_pantry_lights_off_no_motion
    initial_state: true
    trigger:
      - entity_id: binary_sensor.pantry_occupancy
        platform: state
        from: 'on'
        to: 'off'
    action:
      - action: homeassistant.turn_off
        entity_id:
          - switch.shellyplus2pm_d48afc581860_switch_0
          - switch.shellyplus2pm_d48afc581860_switch_1


  - alias: 'Turn on kitchen lights upon first movement in the morning'
    id: kitchen_turn_on_light_morning_first_movement
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.entrance_to_living_room_01_occupancy
        from: 'off'
        to: 'on'

    condition:
      condition: and
      conditions:
        - condition: template
          value_template: >-
            {{ as_timestamp(now()) - as_timestamp(state_attr('automation.turn_on_kitchen_lights_upon_first_movement_in_the_morning', 'last_triggered') or today_at('00:00')) | int > 7200 }}
        - condition: time
          after: '06:30:00'
          before: '10:00:00'
        - condition: state
          entity_id: input_boolean.away_mode
          state: 'off'

    action:
      - action: homeassistant.turn_on
        entity_id:
          - switch.shellyplus2pm_fcb4670e68e8_switch_0
          - switch.shellyplus2pm_fcb4670e68e8_switch_1
