---
template:
  - sensor:
      - name: "Living room AC Temperature"
        unit_of_measurement: "°C"
        state: "{{ state_attr('climate.living_room_ac', 'current_temperature') }}"
        availability: "{{ state_attr('climate.living_room_ac', 'current_temperature') is not none }}"
        device_class: temperature
        icon: mdi:thermometer

      - name: "Living room AC humidity"
        unit_of_measurement: "%"
        state: "{{ state_attr('climate.living_room_ac', 'current_humidity') }}"
        availability: "{{ state_attr('climate.living_room_ac', 'current_humidity') is not none }}"
        device_class: humidity
        icon: mdi:water-percent

sensor:
  - platform: history_stats
    name: living_room_presence_hours_today
    entity_id: binary_sensor.living_room_presence
    state: 'on'
    type: time
    start: "{{ today_at('00:00') }}"
    end: "{{ now() }}"

light:
  - platform: template
    lights:
      public_space_lights:
        value_template: >-
          {{
            is_state('switch.shellyplus2pm_fcb4670e68e8_switch_0', 'on') and
            is_state('switch.shellyplus2pm_fcb4670e68e8_switch_1', 'on') and
            is_state('switch.shelly1pmminig3_3030f9eca0dc_switch_0', 'on') and
            is_state('switch.shelly1pmminig3_34b7da92245c_switch_0', 'on')
          }}
        turn_on:
          action: homeassistant.turn_on
          data:
            entity_id:
              - switch.shelly1pmminig3_3030f9eca0dc_switch_0
              - switch.shelly1pmminig3_34b7da92245c_switch_0
              - switch.shellyplus2pm_fcb4670e68e8_switch_0
              - switch.shellyplus2pm_fcb4670e68e8_switch_1
        turn_off:
          action: homeassistant.turn_off
          data:
            entity_id:
              - switch.shelly1pmminig3_34b7da92245c_switch_0
              - switch.shelly1pmminig3_3030f9eca0dc_switch_0
              - switch.shellyplus2pm_fcb4670e68e8_switch_0
              - switch.shellyplus2pm_fcb4670e68e8_switch_1


automation:
  - alias: "Living Room - Turn AC off when no one is in the room"
    id: living_room_no_presence_turn_ac_off
    initial_state: false
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.apollo_msr_2_04f838_radar_target
          - binary_sensor.apollo_msr_2_354f7c_radar_target
        to: 'off'
        for:
          minutes: 15

    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: binary_sensor.apollo_msr_2_04f838_radar_target
          state: 'off'
        - condition: state
          entity_id: binary_sensor.apollo_msr_2_354f7c_radar_target
          state: 'off'

    action:
      - action: climate.turn_off
        data_template:
          entity_id: climate.living_room_ac


  - alias: "Turn on living room couch light when TV light is turned on"
    id: living_room_couch_light_turn_on_when_tv_light_is_on
    initial_state: true
    trigger:
      - platform: state
        entity_id: switch.shelly1pmminig3_3030f9eca0dc_switch_0  # TV light
        to: 'on'
    condition:
      - condition: state
        entity_id: switch.shelly1pmminig3_34b7da92245c_switch_0  # Couch light
        state: 'off'
    action:
      - action: homeassistant.turn_on
        entity_id: switch.shelly1pmminig3_34b7da92245c_switch_0


  - alias: "Turn off living room couch light when TV light is turned off"
    id: living_room_couch_light_turn_off_when_tv_light_is_off
    initial_state: true
    trigger:
      - platform: state
        entity_id: switch.shelly1pmminig3_3030f9eca0dc_switch_0  # TV light
        to: 'off'
    condition:
      - condition: state
        entity_id: switch.shelly1pmminig3_34b7da92245c_switch_0  # Couch light
        state: 'on'
    action:
      - action: homeassistant.turn_off
        entity_id: switch.shelly1pmminig3_34b7da92245c_switch_0


  - alias: 'Kitchen - toggle lights by single button press'
    id: kitchen_toggle_lights_by_switch
    initial_state: true
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.entrance_01_action
        to: 'single'

    action:
      - choose:
          - conditions:
              - condition: template
                value_template: >
                  {% set switches = [states('switch.shellyplus2pm_fcb4670e68e8_switch_0'), states('switch.shellyplus2pm_fcb4670e68e8_switch_1'), states('switch.shelly1pmminig3_34b7da92245c_switch_0'), states('switch.shelly1pmminig3_3030f9eca0dc_switch_0')] %}
                  {% set on_switches = switches | select('eq', 'on') | list %}
                  {{ on_switches | length > 2 }}
            sequence:
              - action: homeassistant.turn_off
                target:
                  entity_id:
                    - switch.shellyplus2pm_fcb4670e68e8_switch_0
                    - switch.shellyplus2pm_fcb4670e68e8_switch_1
                    - switch.shelly1pmminig3_3030f9eca0dc_switch_0
                    - switch.shelly1pmminig3_34b7da92245c_switch_0
        default:
          - action: switch.turn_on
            target:
              entity_id:
                - switch.shellyplus2pm_fcb4670e68e8_switch_0
                - switch.shellyplus2pm_fcb4670e68e8_switch_1
                - switch.shelly1pmminig3_34b7da92245c_switch_0
                - switch.shelly1pmminig3_3030f9eca0dc_switch_0


  - alias: 'Kitchen - turn everything off by double button press'
    id: kitchen_turn_everything_off
    initial_state: true
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.entrance_01_action
        to: 'double'

    action:
      - action: script.turn_everything_off


  - alias: 'Living room fireplace switch - turn on AC'
    id: living_room_fireplace_switch_turn_on_ac
    initial_state: true
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.living_room_01_action
        to: 'button_2_single'

    action:
      - choose:
          - conditions:
              - condition: numeric_state
                entity_id: input_number.daily_expected_max_temperature
                above: 23
            sequence:
              - action: climate.set_hvac_mode
                target:
                  entity_id: climate.living_room_ac
                data:
                  hvac_mode: 'cool'
        default:
          - service: climate.set_hvac_mode
            target:
              entity_id: climate.living_room_ac
            data:
              hvac_mode: 'heat'


  - alias: 'Living room fireplace switch - turn off AC'
    id: living_room_fireplace_switch_turn_off_ac
    initial_state: true
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.living_room_01_action
        to: 'button_1_single'

    action:
      - action: climate.turn_off
        target:
          entity_id: climate.living_room_ac


  - alias: 'Living room fireplace switch - Increase AC temperature'
    id: living_room_fireplace_increase_ac_temperature
    initial_state: true
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.living_room_01_action
        to: 'button_4_single'

    action:
      - action: climate.set_temperature
        target:
          entity_id: climate.living_room_ac
        data:
          temperature: "{{ state_attr('climate.living_room_ac', 'temperature') | float + 1 }}"


  - alias: 'Living room fireplace switch - Decrease AC temperature'
    id: living_room_fireplace_decrease_ac_temperature
    initial_state: true
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.living_room_01_action
        to: 'button_3_single'

    action:
      - action: climate.set_temperature
        target:
          entity_id: climate.living_room_ac
        data:
          temperature: "{{ state_attr('climate.living_room_ac', 'temperature') | float - 1 }}"


  - alias: Notify TV is playing for turning the lights off
    id: kitchen_notify_tv_is_playing_before_turning_lights_off
    initial_state: false
    trigger:
      platform: state
      entity_id: media_player.livingroom_tv
      to: 'playing'
      for:
        minutes: 1
    condition:
      condition: and
      conditions:
          # 1 hour since last execution
        - condition: template
          value_template: >-
            {{ as_timestamp(now()) - as_timestamp(state_attr('automation.notify_tv_is_playing_for_turning_the_lights_off', 'last_triggered') or today_at('00:00:00')) > 3600}}
        - condition: time
          after: '21:00:00'
        - condition: state
          entity_id: light.public_space_lights
          state: 'on'

    action:
      - action: script.activate_alexa_actionable_notification
        data_template:
          text: 'So you are watching TV, should I turn off the lights ?'
          event_id: 'actionable_notification_lights_tv_playing'
          alexa_device: 'media_player.kitchen_echo'


  - alias: Turn off the lights via actionable notification
    id: living_room_turn_off_lights_via_actionable_notification
    initial_state: true
    trigger:
      - platform: event
        event_type: alexa_actionable_notification
        event_data:
          event_id: actionable_notification_lights_tv_playing
          event_response_type: ResponseYes

    action:
      - action: homeassistant.turn_off
        entity_id: light.public_space_lights


  - alias: Turn on the AC when Ohad start brushing
    id: living_room_turn_on_ac_school_morning_toothbrush_running
    initial_state: true
    trigger:
      - platform: state
        entity_id: sensor.io_series_4_f7ec
        to: running

    conditions:
      - condition: time
        after: "06:00:00"
        before: "08:00:00"
      - condition: state
        entity_id: binary_sensor.high_vacation
        state: 'off'
      - condition: numeric_state
        entity_id: sensor.living_room_ac_temperature
        below: 18

    action:
      - action: climate.turn_on
        entity_id: climate.living_room_ac


  - alias: 'Shutdown AC if window is left open for more than 10 minutes'
    id: living_room_shutdown_ac_balcony_window_is_open
    initial_state: false
    trigger:
      - platform: state
        entity_id: binary_sensor.dining_room_main_window_contact
        to: 'on'
        for:
          minutes: 10

    conditions:
      - condition: template
        value_template: "{{ not is_state('climate.living_room_ac', 'off') }}"

    action:
      - action: climate.turn_off
        target:
          entity_id: climate.living_room_ac
