---
automation:
  - alias: 'Close living room shutters at 21:00'
    id: living_room_shutters_close_at_night
    initial_state: false
    trigger:
      platform: time
      at: '21:00:00'

    condition:
      - condition: state
        entity_id: input_boolean.away_mode
        state: 'off'

    action:
      - action: cover.set_cover_position
        target:
          entity_id:
            - cover.living_room_right_window
            - cover.living_room_middle_window
            - cover.living_room_left_window
        data:
          position: 5

  - alias: 'Open living room shutters in the morning'
    id: living_room_open_living_room_shutters_morning
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.entrance_to_living_room_01_occupancy
        from: 'off'
        to: 'on'

    condition:
      condition: and
      conditions:
        - condition: template
          value_template: >-
            {{ as_timestamp(now()) - as_timestamp(state_attr('automation.open_living_room_shutters_in_the_morning', 'last_triggered') or today_at('00:00')) | int > 7200 }}
        - condition: time
          after: '06:30:00'
          before: '10:00:00'
        - condition: state
          entity_id: input_boolean.away_mode
          state: 'off'

    action:
      - action: cover.set_cover_position
        data_template:
          entity_id: cover.living_room_right_window
          position: >-
            {{ max(state_attr('cover.living_room_right_window', 'current_position') | int, 70) }}

      - action: cover.set_cover_position
        data_template:
          entity_id: cover.living_room_middle_window
          position: >-
            {{ max(state_attr('cover.living_room_middle_window', 'current_position') | int, 70) }}

      - action: cover.set_cover_position
        data_template:
          entity_id: cover.living_room_left_window
          position: >-
            {{ max(state_attr('cover.living_room_left_window', 'current_position') | int, 70) }}


  - alias: 'Close living room shutters - sunset'
    id: living_room_shutters_close_before_sunset
    trigger:
      - platform: event
        event_type: alexa_actionable_notification
        event_data:
          event_id: shutters_close_sunset
          event_response_type: ResponseYes

      - platform: event
        event_type: alexa_actionable_notification
        event_data:
          event_id: shutters_close_sunset
          event_response_type: ResponseNone

      - platform: sun
        event: sunset
        offset: "-03:00:00"

    action:
      - action: cover.set_cover_position
        target:
          entity_id:
            - cover.living_room_left_window
            - cover.living_room_middle_window
            - cover.living_room_right_window
        data:
          position: 35


  - alias: 'Toggle living room AC state'
    id: living_room_ac_toggle_state
    initial_state: true
    trigger:
      - platform: state
        entity_id: sensor.living_room_ac_action
        to: 'single'

    action:
      - action: climate.toggle
        target:
          entity_id: climate.living_room_ac


  - alias: 'Increase living room AC temperature by 1 degree'
    id: living_room_ac_increase_temp_one_degree
    initial_state: true
    trigger:
      - platform: state
        entity_id: sensor.living_room_ac_action
        to: 'double'

    action:
      - action: climate.set_temperature
        target:
          entity_id: climate.living_room_ac
        data:
          temperature: "{{ state_attr('climate.living_room_ac', 'temperature') | float + 1 }}"


  - alias: 'Decrease living room AC temperature by 1 degree'
    id: living_room_ac_decrease_temp_one_degree
    initial_state: true
    trigger:
      - platform: state
        entity_id: sensor.living_room_ac_action
        to: 'hold'

    action:
      - action: climate.set_temperature
        target:
          entity_id: climate.living_room_ac
        data:
          temperature: "{{ state_attr('climate.living_room_ac', 'temperature') | float -1 }}"


  - alias: "Living Room - Turn AC off when no one is in the room"
    id: living_room_no_presence_turn_ac_off
    initial_state: true
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.apollo_msr_2_04f838_radar_target
          - binary_sensor.apollo_msr_2_354f7c_radar_target
        to: 'off'
        for:
          minutes: 15

    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: binary_sensor.apollo_msr_2_04f838_radar_target
          state: 'off'
        - condition: state
          entity_id: binary_sensor.apollo_msr_2_354f7c_radar_target
          state: 'off'

    action:
      - action: climate.turn_off
        data_template:
          entity_id: climate.living_room_ac


  - alias: "Turn on living room couch light when TV light is turned on"
    id: living_room_couch_light_turn_on_when_tv_light_is_on
    initial_state: true
    trigger:
      - platform: state
        entity_id: switch.shelly1_34945470bfa1 # TV light
        to: 'on'
      - platform: homeassistant
        event: start
    condition:
      - condition: state
        entity_id: switch.shelly1_34945470bfa1 # TV light
        state: 'on'
    action:
      - action: homeassistant.turn_on
        entity_id: switch.shelly1_e8db84d27b53


  - alias: "Turn off living room couch light when TV light is turned off"
    id: living_room_couch_light_turn_off_when_tv_light_is_off
    initial_state: true
    trigger:
      - platform: state
        entity_id: switch.shelly1_34945470bfa1 # TV light
        to: 'off'
      - platform: homeassistant
        event: start
    condition:
      - condition: state
        entity_id: switch.shelly1_34945470bfa1 # TV light
        state: 'off'
    action:
      - action: homeassistant.turn_off
        entity_id: switch.shelly1_e8db84d27b53


  - alias: 'Kitchen - toggle lights by single button press'
    id: kitchen_toggle_lights_by_switch
    initial_state: true
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.entrance_01_action
        to: 'single'

    action:
      - choose:
          - conditions:
              - condition: template
                value_template: >
                  {% set switches = [states('switch.shellyplus2pm_fcb4670e68e8_switch_0'), states('switch.shellyplus2pm_fcb4670e68e8_switch_1'), states('switch.shelly1_34945470bfa1'), states('switch.shelly1_e8db84d27b53')] %}
                  {% set on_switches = switches | select('eq', 'on') | list %}
                  {{ on_switches | length > 2 }}
            sequence:
              - service: switch.turn_off
                target:
                  entity_id:
                    - switch.shellyplus2pm_fcb4670e68e8_switch_0
                    - switch.shellyplus2pm_fcb4670e68e8_switch_1
                    - switch.shelly1_34945470bfa1
                    - switch.shelly1_e8db84d27b53
        default:
          - service: switch.turn_on
            target:
              entity_id:
                - switch.shellyplus2pm_fcb4670e68e8_switch_0
                - switch.shellyplus2pm_fcb4670e68e8_switch_1
                - switch.shelly1_34945470bfa1
                - switch.shelly1_e8db84d27b53


  - alias: 'Kitchen - turn everything off by double button press'
    id: kitchen_turn_everything_off
    initial_state: true
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.entrance_01_action
        to: 'double'

    action:
      - action: lock.lock
        target:
          entity_id: >
            {{ states.lock | map(attribute='entity_id') | list }}

      - action: switch.turn_off
        entity_id:
          - switch.shellyplus2pm_fcb4670e68e8_switch_0
          - switch.shellyplus2pm_fcb4670e68e8_switch_1
          - switch.shelly1_34945470bfa1
          - switch.shelly1_e8db84d27b53

      - action: cover.set_cover_position
        data:
          position: 35
        target:
          entity_id:
            - cover.living_room_left_window
            - cover.living_room_middle_window
            - cover.living_room_right_window
            - cover.dining_room_right_window
            - cover.dining_room_left_window

      - action: climate.turn_off
        entity_id: climate.living_room_ac
