---
template:
  - sensor:
      - name: "Living room AC Temperature"
        unit_of_measurement: "°C"
        state: "{{ state_attr('climate.living_room_ac', 'current_temperature') }}"
        availability: "{{ state_attr('climate.living_room_ac', 'current_temperature') is not none }}"
        device_class: temperature
        icon: mdi:thermometer

      - name: "Living room AC humidity"
        unit_of_measurement: "%"
        state: "{{ state_attr('climate.living_room_ac', 'current_humidity') }}"
        availability: "{{ state_attr('climate.living_room_ac', 'current_humidity') is not none }}"
        device_class: humidity
        icon: mdi:water-percent


light:
  - platform: template
    lights:
      public_space_lights:
        value_template: >-
          {{
            is_state('switch.shellyplus2pm_fcb4670e68e8_switch_0', 'on') and
            is_state('switch.shellyplus2pm_fcb4670e68e8_switch_1', 'on') and
            is_state('switch.shelly1_34945470bfa1', 'on') and
            is_state('switch.shelly1_e8db84d27b53', 'on')
          }}
        turn_on:
          action: homeassistant.turn_on
          data:
            entity_id:
              - switch.shelly1_e8db84d27b53
              - switch.shelly1_34945470bfa1
              - switch.shellyplus2pm_fcb4670e68e8_switch_0
              - switch.shellyplus2pm_fcb4670e68e8_switch_1
        turn_off:
          action: homeassistant.turn_off
          data:
            entity_id:
              - switch.shelly1_e8db84d27b53
              - switch.shelly1_34945470bfa1
              - switch.shellyplus2pm_fcb4670e68e8_switch_0
              - switch.shellyplus2pm_fcb4670e68e8_switch_1


automation:
  - alias: 'Close living room shutters at 21:00'
    id: living_room_shutters_close_at_night
    initial_state: true
    trigger:
      platform: time
      at: '21:00:00'

    condition:
      - condition: state
        entity_id: input_boolean.away_mode
        state: 'off'

    action:
      - variables:
          left_window_position: "{{ state_attr('cover.living_room_left_window', 'current_position') }}"
          middle_window_position: "{{ state_attr('cover.living_room_middle_window', 'current_position') }}"
          right_window_position: "{{ state_attr('cover.living_room_right_window', 'current_position') }}"


      - action: cover.set_cover_position
        target:
          entity_id:
            - cover.living_room_left_window
        data:
          position: "{{ [left_window_position, 15] | min }}"

      - action: cover.set_cover_position
        target:
          entity_id:
            - cover.living_room_middle_window
        data:
          position: "{{ [middle_window_position, 15] | min }}"

      - action: cover.set_cover_position
        target:
          entity_id:
            - cover.living_room_right_window
        data:
          position: "{{ [right_window_position, 15] | min }}"


  - alias: 'Close living room shutters at night'
    id: living_room_shutters_close_at_night_complete
    initial_state: true
    trigger:
      platform: time
      at: '00:00:00'

    condition:
      - condition: state
        entity_id: input_boolean.away_mode
        state: 'off'

    action:
      - action: cover.set_cover_position
        target:
          entity_id:
            - cover.living_room_right_window
            - cover.living_room_middle_window
            - cover.living_room_left_window
        data:
          position: 0


  - alias: 'Open living room shutters in the morning'
    id: living_room_open_living_room_shutters_morning
    initial_state: true
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.entrance_to_living_room_01_occupancy
          - binary_sensor.entrance_indoor_occupancy
        from: 'off'
        to: 'on'

    condition:
      condition: and
      conditions:  # 4 hours passed (don't run twice the same day)
        - condition: template
          value_template: >-
            {{ as_timestamp(now()) - as_timestamp(state_attr('automation.open_living_room_shutters_in_the_morning', 'last_triggered') or today_at('00:00')) | int > 28800 }}
        - condition: time
          after: '06:30:00'
          before: '10:00:00'
        - condition: state
          entity_id: input_boolean.away_mode
          state: 'off'

    action:
      - action: cover.set_cover_position
        data_template:
          entity_id: cover.living_room_right_window
          position: >-
            {{ max(state_attr('cover.living_room_right_window', 'current_position') | int, 70) }}

      - action: cover.set_cover_position
        data_template:
          entity_id: cover.living_room_middle_window
          position: >-
            {{ max(state_attr('cover.living_room_middle_window', 'current_position') | int, 70) }}

      - action: cover.set_cover_position
        data_template:
          entity_id: cover.living_room_left_window
          position: >-
            {{ max(state_attr('cover.living_room_left_window', 'current_position') | int, 70) }}


  - alias: 'Close living room shutters - sunset'
    id: living_room_shutters_close_before_sunset
    trigger:
      - platform: event
        event_type: alexa_actionable_notification
        event_data:
          event_id: shutters_close_sunset
          event_response_type: ResponseYes

      - platform: event
        event_type: alexa_actionable_notification
        event_data:
          event_id: shutters_close_sunset
          event_response_type: ResponseNone

      - platform: sun
        event: sunset
        offset: "-03:00:00"

    condition:
      - condition: state
        entity_id: binary_sensor.dst
        state: 'on'

    action:
      - variables:
          left_window_position: "{{ state_attr('cover.living_room_left_window', 'current_position') }}"
          middle_window_position: "{{ state_attr('cover.living_room_middle_window', 'current_position') }}"
          right_window_position: "{{ state_attr('cover.living_room_right_window', 'current_position') }}"

      - action: cover.set_cover_position
        target:
          entity_id:
            - cover.living_room_left_window
        data:
          position: "{{ [left_window_position, 35] | min }}"

      - action: cover.set_cover_position
        target:
          entity_id:
            - cover.living_room_middle_window
        data:
          position: "{{ [middle_window_position, 35] | min }}"

      - action: cover.set_cover_position
        target:
          entity_id:
            - cover.living_room_right_window
        data:
          position: "{{ [right_window_position, 35] | min }}"

  - alias: "Living Room - Turn AC off when no one is in the room"
    id: living_room_no_presence_turn_ac_off
    initial_state: false
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.apollo_msr_2_04f838_radar_target
          - binary_sensor.apollo_msr_2_354f7c_radar_target
        to: 'off'
        for:
          minutes: 15

    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: binary_sensor.apollo_msr_2_04f838_radar_target
          state: 'off'
        - condition: state
          entity_id: binary_sensor.apollo_msr_2_354f7c_radar_target
          state: 'off'

    action:
      - action: climate.turn_off
        data_template:
          entity_id: climate.living_room_ac


  - alias: "Turn on living room couch light when TV light is turned on"
    id: living_room_couch_light_turn_on_when_tv_light_is_on
    initial_state: true
    trigger:
      - platform: state
        entity_id: switch.shelly1_34945470bfa1  # TV light
        to: 'on'
    condition:
      - condition: state
        entity_id: switch.shelly1_e8db84d27b53  # Couch light
        state: 'off'
    action:
      - action: homeassistant.turn_on
        entity_id: switch.shelly1_e8db84d27b53


  - alias: "Turn off living room couch light when TV light is turned off"
    id: living_room_couch_light_turn_off_when_tv_light_is_off
    initial_state: true
    trigger:
      - platform: state
        entity_id: switch.shelly1_34945470bfa1  # TV light
        to: 'off'
    condition:
      - condition: state
        entity_id: switch.shelly1_e8db84d27b53  # Couch light
        state: 'on'
    action:
      - action: homeassistant.turn_off
        entity_id: switch.shelly1_e8db84d27b53


  - alias: 'Kitchen - toggle lights by single button press'
    id: kitchen_toggle_lights_by_switch
    initial_state: true
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.entrance_01_action
        to: 'single'

    action:
      - choose:
          - conditions:
              - condition: template
                value_template: >
                  {% set switches = [states('switch.shellyplus2pm_fcb4670e68e8_switch_0'), states('switch.shellyplus2pm_fcb4670e68e8_switch_1'), states('switch.shelly1_34945470bfa1'), states('switch.shelly1_e8db84d27b53')] %}
                  {% set on_switches = switches | select('eq', 'on') | list %}
                  {{ on_switches | length > 2 }}
            sequence:
              - action: homeassistant.turn_off
                target:
                  entity_id:
                    - switch.shellyplus2pm_fcb4670e68e8_switch_0
                    - switch.shellyplus2pm_fcb4670e68e8_switch_1
                    - switch.shelly1_34945470bfa1
                    - switch.shelly1_e8db84d27b53
        default:
          - action: switch.turn_on
            target:
              entity_id:
                - switch.shellyplus2pm_fcb4670e68e8_switch_0
                - switch.shellyplus2pm_fcb4670e68e8_switch_1
                - switch.shelly1_34945470bfa1
                - switch.shelly1_e8db84d27b53


  - alias: 'Kitchen - turn everything off by double button press'
    id: kitchen_turn_everything_off
    initial_state: true
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.entrance_01_action
        to: 'double'

    action:
      - action: script.turn_everything_off

  - alias: 'Living room fireplace switch - turn on AC'
    id: living_room_fireplace_switch_turn_on_ac
    initial_state: true
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.living_room_01_action
        to: 'button_2_single'

    action:
      - action: climate.turn_on
        target:
          entity_id: climate.living_room_ac


  - alias: 'Living room fireplace switch - turn off AC'
    id: living_room_fireplace_switch_turn_off_ac
    initial_state: true
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.living_room_01_action
        to: 'button_1_single'

    action:
      - action: climate.turn_off
        target:
          entity_id: climate.living_room_ac


  - alias: 'Living room fireplace switch - Increase AC temperature'
    id: living_room_fireplace_increase_ac_temperature
    initial_state: true
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.living_room_01_action
        to: 'button_4_single'

    action:
      - action: climate.set_temperature
        target:
          entity_id: climate.living_room_ac
        data:
          temperature: "{{ state_attr('climate.living_room_ac', 'temperature') | float + 1 }}"


  - alias: 'Living room fireplace switch - Decrease AC temperature'
    id: living_room_fireplace_decrease_ac_temperature
    initial_state: true
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.living_room_01_action
        to: 'button_3_single'

    action:
      - action: climate.set_temperature
        target:
          entity_id: climate.living_room_ac
        data:
          temperature: "{{ state_attr('climate.living_room_ac', 'temperature') | float - 1 }}"


  - alias: 'Living room fireplace switch - Open living room shutters'
    id: living_room_fireplace_open_living_shutters
    initial_state: true
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.living_room_01_action
        to: 'button_6_single'

    action:
      - action: cover.set_cover_position
        target:
          entity_id:
            - cover.living_room_right_window
            - cover.living_room_middle_window
            - cover.living_room_left_window
        data:
          position: 80


  - alias: 'Living room fireplace switch - Close living room shutters'
    id: living_room_fireplace_close_living_room_shutters
    initial_state: true
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.living_room_01_action
        to: 'button_5_single'

    action:
      - action: cover.set_cover_position
        target:
          entity_id:
            - cover.living_room_right_window
            - cover.living_room_middle_window
            - cover.living_room_left_window
        data:
          position: 35

  - alias: 'Living room fireplace switch - Open dining room shutters'
    id: living_room_fireplace_open_dining_room_shutters
    initial_state: true
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.living_room_01_action
        to: 'button_6_double'

    action:
      - action: cover.set_cover_position
        target:
          entity_id:
            - cover.dining_room_right_window
            - cover.dining_room_left_window
        data:
          position: 80

      - action: cover.set_cover_position
        target:
          entity_id: cover.dining_room_main_window
        data:
          position: 100


  - alias: 'Living room fireplace switch - Close dining room shutters'
    id: living_room_fireplace_close_dining_room_shutters
    initial_state: true
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.living_room_01_action
        to: 'button_5_double'

    action:
      - action: cover.set_cover_position
        target:
          entity_id:
            - cover.dining_room_right_window
            - cover.dining_room_main_window
            - cover.dining_room_left_window
        data:
          position: 35


  - alias: 'Living room fireplace switch - Open public space shutters'
    id: living_room_fireplace_open_public_space_shutters
    initial_state: true
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.living_room_01_action
        to: 'button_6_triple'

    action:
      - action: cover.set_cover_position
        target:
          entity_id: group.public_space_shutters
        data:
          position: 100


  - alias: 'Living room fireplace switch - Close public space shutters'
    id: living_room_fireplace_close_public_space_shutters
    initial_state: true
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.living_room_01_action
        to: 'button_5_triple'

    action:
      - action: cover.set_cover_position
        target:
          entity_id: group.public_space_shutters
        data:
          position: 15


  - alias: Notify TV is playing for turning the lights off
    id: kitchen_notify_tv_is_playing_before_turning_lights_off
    initial_state: true
    trigger:
      platform: state
      entity_id: media_player.livingroom_tv
      to: 'playing'
      for:
        minutes: 1
    condition:
      condition: and
      conditions:
          # 1 hour since last execution
        - condition: template
          value_template: >-
            {{ as_timestamp(now()) - as_timestamp(state_attr('automation.notify_tv_is_playing_for_turning_the_lights_off', 'last_triggered') or today_at('00:00:00')) > 3600}}
        - condition: time
          after: '21:00:00'
        - condition: state
          entity_id: light.public_space_lights
          state: 'on'

    action:
      - action: script.activate_alexa_actionable_notification
        data_template:
          text: 'So you are watching TV, should I turn off the lights ?'
          event_id: 'actionable_notification_lights_tv_playing'
          alexa_device: 'media_player.kitchen_echo'

  - alias: Turn off the lights via actionable notification
    id: living_room_turn_off_lights_via_actionable_notification
    initial_state: true
    trigger:
      - platform: event
        event_type: alexa_actionable_notification
        event_data:
          event_id: actionable_notification_lights_tv_playing
          event_response_type: ResponseYes

      - platform: event
        event_type: alexa_actionable_notification
        event_data:
          event_id: actionable_notification_lights_tv_playing
          event_response_type: ResponseNone

    action:
      - action: homeassistant.turn_off
        entity_id: light.public_space_lights


  - alias: Turn on the AC when Ohad start brushing
    id: living_room_turn_on_ac_school_morning_toothbrush_running
    initial_state: true
    trigger:
      - platform: state
        entity_id: sensor.io_series_4_f7ec
        to: running

    conditions:
      - condition: time
        after: "06:00:00"
        before: "08:00:00"
      - condition: state
        entity_id: sensor.school_is_high_vacation
        state: 'False'
      - condition: numeric_state
        entity_id: sensor.living_room_ac_temperature
        below: 20

    action:
      - action: climate.turn_on
        entity_id: climate.living_room_ac
