---
input_datetime:
  ohad_iphone_alarm:
    name: Ohad iPhone alarm
    has_date: true
    has_time: true


input_boolean:
  master_bedroom_sleep_mode:
    name: sleep mode
    icon: mdi:sleep


light:
  - platform: template
    lights:
      master_bedroom_lights:
        value_template: >-
          {{
            is_state('light.shellydimmer2_ec64c9c66fdc', 'on') and
            is_state('switch.shelly1pmminig3_34b7da8eef08_switch_0', 'on') and
            is_state('switch.shellyplus2pm_fcb4670e673c_switch_0', 'on') and
            is_state('switch.shellyplus2pm_fcb4670e673c_switch_1', 'on')
          }}
        turn_on:
          action: homeassistant.turn_on
          data:
            entity_id:
              - switch.shellyplus2pm_fcb4670e673c_switch_0
              - switch.shellyplus2pm_fcb4670e673c_switch_1
              - switch.shelly1pmminig3_34b7da8eef08_switch_0
              - light.shellydimmer2_ec64c9c66fdc
        turn_off:
          action: homeassistant.turn_off
          data:
            entity_id:
              - switch.shellyplus2pm_fcb4670e673c_switch_0
              - switch.shellyplus2pm_fcb4670e673c_switch_1
              - switch.shelly1pmminig3_34b7da8eef08_switch_0
              - light.shellydimmer2_ec64c9c66fdc


template:
  - sensor:
      - name: "Master Bedroom AC Temperature"
        unit_of_measurement: "°C"
        state: "{{ state_attr('climate.master_bedroom_ac', 'current_temperature') }}"
        availability: "{{ state_attr('climate.master_bedroom_ac', 'current_temperature') is not none }}"
        device_class: temperature
        icon: mdi:thermometer

      - name: "Master Bedroom AC humidity"
        unit_of_measurement: "%"
        state: "{{ state_attr('climate.master_bedroom_ac', 'current_humidity') }}"
        availability: "{{ state_attr('climate.master_bedroom_ac', 'current_humidity') is not none }}"
        device_class: humidity
        icon: mdi:water-percent

      - name: "Master bedroom AC room temperature difference"
        unit_of_measurement: "°C"
        state: "{{ (state_attr('climate.master_bedroom_ac', 'current_temperature') - state_attr('climate.master_bedroom_ac', 'temperature')) | abs }}"
        availability: "{{ state_attr('climate.master_bedroom_ac', 'current_temperature') is not none }}"
        device_class: temperature
        icon: mdi:thermometer


sensor:
  - platform: derivative
    source: sensor.master_bedroom_ac_room_temperature_difference
    name: Master bedroom temp difference change per 10 minutes
    round: 1
    unit_time: min
    time_window: 10


automation:
  - alias: "Turn on master bedroom wardrobe light on motion"
    id: master_bedroom_wardrobe_turn_light_on_motion
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.master_bedroom_wardrobe_contact
        to: 'on'
      - platform: homeassistant
        event: start
    condition:
      - condition: state
        entity_id: binary_sensor.master_bedroom_wardrobe_contact
        state: 'on'
    action:
      - action: homeassistant.turn_on
        entity_id: switch.shelly1pmminig3_34b7da8da318_switch_0


  - alias: "Turn off master bedroom wardrobe light when no motion is detected"
    id: master_bedroom_wardrobe_turn_light_off_no_motion_detected
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.master_bedroom_wardrobe_contact
        to: 'off'
      - platform: homeassistant
        event: start
    condition:
      - condition: state
        entity_id: binary_sensor.master_bedroom_wardrobe_contact
        state: 'off'
    action:
      - action: homeassistant.turn_off
        entity_id: switch.shelly1pmminig3_34b7da8da318_switch_0


  - alias: 'Open shutters in the morning when the alarm goes off'
    id: master_bedroom_shutters_open_alarm_goes_off
    trigger:
      - platform: state
        entity_id: input_datetime.ohad_iphone_alarm

    condition:
      - condition: template
        value_template: >
          {% set alarm_time = states('input_datetime.ohad_iphone_alarm') %}
          {% set current_time = now().strftime('%Y-%m-%d %H:%M:00') %}
          {% set current_time_obj = strptime(current_time, '%Y-%m-%d %H:%M:%S') %}
          {% set alarm_time_obj = strptime(alarm_time, '%Y-%m-%d %H:%M:%S') %}
          {{ (alarm_time_obj - current_time_obj).total_seconds() <= 600 }}
      - condition: state
        entity_id: input_boolean.away_mode
        state: 'off'

    action:
      - delay: '00:10:00'

      - action: cover.set_cover_position
        target:
          entity_id:
            - cover.master_bedroom_main_window
        data:
          position: 85


  - alias: 'Close master bedroom shutters at night'
    id: master_bedroom_shutters_close_night
    initial_state: false
    trigger:
      - platform: time
        at: '23:00:00'

    condition:
      - condition: state
        entity_id: input_boolean.away_mode
        state: 'off'

    action:
      - action: cover.set_cover_position
        target:
          entity_id:
            - cover.master_bedroom_main_window
        data:
          position: 20

  - alias: "Turn on master bedroom light when fan light is turned on"
    id: master_bedroom_spots_turn_on_when_fan_light_is_on
    initial_state: true
    trigger:
      - platform: state
        entity_id: switch.shelly1pmminig3_34b7da8eef08_switch_0
        to: 'on'
      - platform: homeassistant
        event: start
    condition:
      - condition: state
        entity_id: switch.shelly1pmminig3_34b7da8eef08_switch_0
        state: 'on'
    action:
      - action: light.turn_on
        target:
          entity_id: light.shellydimmer2_ec64c9c66fdc
        data:
          brightness_pct: 100
      # - action: homeassistant.turn_on
      #   entity_id:
      #     - switch.shellyplus2pm_fcb4670e673c_switch_0
      #     - switch.shellyplus2pm_fcb4670e673c_switch_1


  - alias: "Turn off master bedroom lights when light is turned off"
    id: master_bedroom_lights_turn_off_when_fan_light_is_off
    initial_state: true
    trigger:
      - platform: state
        entity_id: switch.shelly1pmminig3_34b7da8eef08_switch_0
        to: 'off'
      - platform: homeassistant
        event: start
    condition:
      - condition: state
        entity_id: switch.shelly1pmminig3_34b7da8eef08_switch_0
        state: 'off'
    action:
      - action: homeassistant.turn_off
        entity_id:
          - light.shellydimmer2_ec64c9c66fdc
          # - switch.shellyplus2pm_fcb4670e673c_switch_0
          # - switch.shellyplus2pm_fcb4670e673c_switch_1


  - alias: 'Master bedroom bedside switch 01 - turn on main light'
    id: master_bedroom_bedside_switch_01_turn_on_main_light
    initial_state: true
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.master_bedroom_bedside_01_action
        to: 'button_2_single'

    action:
      - action: switch.turn_on
        target:
          entity_id: switch.shelly1pmminig3_34b7da8eef08_switch_0


  - alias: 'Master bedroom bedside switch 01 - turn off main light'
    id: master_bedroom_bedside_switch_01_turn_off_main_light
    initial_state: true
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.master_bedroom_bedside_01_action
        to: 'button_1_single'

    action:
      - action: switch.turn_off
        target:
          entity_id: switch.shelly1pmminig3_34b7da8eef08_switch_0


  - alias: 'Master bedroom bedside switch 01 - open shutters'
    id: master_bedroom_bedside_switch_01_open_shutters
    initial_state: true
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.master_bedroom_bedside_01_action
        to: 'button_4_single'

    action:
      - action: cover.set_cover_position
        data:
          position: 100
        target:
          entity_id:
            - cover.master_bedroom_main_window
            - cover.shellyplus2pm_c4d8d5582a90  # right
            - cover.shellyplus2pm_e465b8f38f54  # left


  - alias: 'Master bedroom bedside switch 01 - close shutters'
    id: master_bedroom_bedside_switch_01_close_shutter
    initial_state: true
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.master_bedroom_bedside_01_action
        to: 'button_3_single'

    action:
      - action: cover.set_cover_position
        data:
          position: 20
        target:
          entity_id:
            - cover.master_bedroom_main_window
            - cover.shellyplus2pm_c4d8d5582a90  # right
            - cover.shellyplus2pm_e465b8f38f54  # left


  - alias: 'Master bedroom bedside switch 01 - turn on spots in night mode'
    id: master_bedroom_bedside_switch_01_turn_on_spots_night_mode
    initial_state: true
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.master_bedroom_bedside_01_action
        to: 'button_6_single'

    action:
      - action: switch.turn_off
        entity_id: switch.shelly1pmminig3_34b7da8eef08_switch_0

      - delay: '00:00:02'

      - action: light.turn_on
        target:
          entity_id: light.shellydimmer2_ec64c9c66fdc
        data:
          brightness_pct: 1


  - alias: 'Master bedroom bedside switch 01 - turn off spots'
    id: master_bedroom_bedside_switch_01_turn_off_spots
    initial_state: true
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.master_bedroom_bedside_01_action
        to: 'button_5_single'

    action:
      - action: light.turn_off
        target:
          entity_id: light.shellydimmer2_ec64c9c66fdc


  - alias: 'Master bedroom bedside switch 01 - turn on AC'
    id: master_bedroom_bedside_switch_01_turn_on_ac
    initial_state: true
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.master_bedroom_bedside_01_action
        to: 'button_6_double'

    action:
      - action: climate.turn_on
        target:
          entity_id: climate.master_bedroom_ac


  - alias: 'Master bedroom bedside switch 01 - turn off AC'
    id: master_bedroom_bedside_switch_01_turn_off_ac
    initial_state: true
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.master_bedroom_bedside_01_action
        to: 'button_5_double'

    action:
      - action: climate.turn_off
        target:
          entity_id: climate.master_bedroom_ac


  - alias: 'Master bedroom bedside switch 02 - toggle main light'
    id: master_bedroom_bedside_switch_02_toggle_main_light
    initial_state: true
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.master_bedroom_bedside_02_action
        to: '1_single'

    action:
      - action: switch.toggle
        target:
          entity_id: switch.shelly1pmminig3_34b7da8eef08_switch_0


  - alias: 'Master bedroom bedside switch 02 - toggle AC'
    id: master_bedroom_bedside_switch_02_toggle_ac
    initial_state: true
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.master_bedroom_bedside_02_action
        to: '2_single'

    action:
      - action: climate.toggle
        target:
          entity_id: climate.master_bedroom_ac


  - alias: 'Master bedroom bedside switch 02 - open shutters lights in'
    id: master_bedroom_bedside_switch_02_open_shutters_lights_in
    initial_state: true
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.master_bedroom_bedside_02_action
        to: '3_single'

    action:
      - action: cover.set_cover_position
        data:
          position: 70
        target:
          entity_id:
            - cover.master_bedroom_main_window
            - cover.shellyplus2pm_c4d8d5582a90  # right
            - cover.shellyplus2pm_e465b8f38f54  # left


  - alias: 'Master bedroom bedside switch 02 - open shutters complete'
    id: master_bedroom_bedside_switch_02_open_shutters_complete
    initial_state: true
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.master_bedroom_bedside_02_action
        to: '3_double'

    action:
      - action: cover.set_cover_position
        data:
          position: 100
        target:
          entity_id:
            - cover.master_bedroom_main_window
            - cover.shellyplus2pm_c4d8d5582a90  # right
            - cover.shellyplus2pm_e465b8f38f54  # left


  - alias: 'Master bedroom bedside switch 02 - control spots'
    id: master_bedroom_bedside_switch_02_control_spots
    initial_state: true
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.master_bedroom_bedside_02_action
        to: '4_single'

    action:
      - if:
          - condition: state
            entity_id: light.shellydimmer2_ec64c9c66fdc
            state: 'off'
        then:
          - service: switch.turn_off
            target:
              entity_id: switch.shelly1pmminig3_34b7da8eef08_switch_0

          - delay: '00:00:02'

          - service: light.turn_on
            target:
              entity_id: light.shellydimmer2_ec64c9c66fdc
            data:
              brightness_pct: 1
        else:
          - service: light.turn_off
            target:
              entity_id: light.shellydimmer2_ec64c9c66fdc


  - alias: 'Master bedroom bedside switch 02 - control night light'
    id: master_bedroom_bedside_switch_02_night_light
    initial_state: true
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.master_bedroom_bedside_02_action
        to: '5_single'

    action:
      - action: switch.toggle
        target:
          entity_id: switch.sonoff_s20_02


  - alias: "Master bedroom - Turn AC off when no one is in the room"
    id: master_bedroom_no_presence_turn_ac_off
    initial_state: false
    trigger:
      - platform: state
        entity_id: binary_sensor.apollo_msr_2_398b60_radar_target
        to: 'off'
        for:
          minutes: 10

    condition:
      - condition: template
        value_template: >-
          {{ not is_state('climate.master_bedroom_ac', 'off') }}
      - condition: state
        entity_id: input_boolean.master_bedroom_sleep_mode
        state: 'off'

    action:
      - action: climate.turn_off
        data_template:
          entity_id: climate.master_bedroom_ac


  - alias: "Turn off master bedroom AC when no motion is detected"
    id: master_bedroom_turn_ac_off_no_motion_detected
    initial_state: false
    trigger:
      - platform: state
        entity_id: binary_sensor.apollo_msr_2_398b60_radar_target
        to: 'off'
        for:
          minutes: 5

      - platform: homeassistant
        event: start

    condition:
      - condition: state
        entity_id: binary_sensor.apollo_msr_2_398b60_radar_target
        state: 'off'
      - condition: time
        before: '23:00:00'
        after: '08:00:00'

    action:
      - action: homeassistant.turn_off
        entity_id: climate.master_bedroom_ac


  - alias: "Master bedroom turn off sleep mode"
    id: master_bedroom_turn_off_sleep_mode
    initial_state: true
    trigger:
      - platform: event
        event_type: state_changed
        event_data:
          entity_id: switch.shelly1pmminig3_34b7da8eef08_switch_0
    condition:
      - condition: template
        value_template: >
          {{ not trigger.event.data.new_state.context.user_id and not trigger.event.data.new_state.context.parent_id }}
      - condition: state
        entity_id: switch.shelly1pmminig3_34b7da8eef08_switch_0
        state: 'on'
      - condition: state
        entity_id: input_boolean.master_bedroom_sleep_mode
        state: 'on'

    action:
      - action: input_boolean.turn_off
        entity_id: input_boolean.master_bedroom_sleep_mode

  - alias: Toggle master bedroom fan light by entrance button
    id: master_bedroom_toggle_master_bedroom_entrance_light
    initial_state: true
    trigger:
      - platform: state
        entity_id: sensor.master_bedroom_entrance_01_action
        to: 'single'

    action:
      - action: switch.toggle
        entity_id: switch.shelly1pmminig3_34b7da8eef08_switch_0


  - alias: Shutdown AC 1 hour after target temperature has been reached
    id: master_bedroom_shutdown_ac_target_temp_reached
    initial_state: true
    trigger:
      - platform: numeric_state
        entity_id: sensor.master_bedroom_temp_difference_change_per_10_minutes
        above: -1
        below: 1
        for:
          hours: 1
      - platform: template
        value_template: >-
          {{
            states('climate.master_bedroom_ac') != 'off' and
            (now() - states.climate.master_bedroom_ac.last_changed).total_seconds() > 3600
          }}

    condition:
      - condition: template
        value_template: >
          {{
            states('climate.master_bedroom_ac') != 'off' and
            (now() - states.climate.master_bedroom_ac.last_changed).total_seconds() > 3600
          }}
      - condition: numeric_state
        entity_id: sensor.master_bedroom_temp_difference_change_per_10_minutes
        above: -1
        below: 1

    action:
      - action: climate.turn_off
        entity_id: climate.master_bedroom_ac
