---
automation:
  - alias: Master bathroom water leak detection
    id: master_bathroom_water_leak_detection
    initial_state: true
    trigger:
      - entity_id:
          - binary_sensor.master_bathroom_sink_water_leak
        platform: state
        to: 'on'
    action:
      - action: notify.send_message
        target:
          entity_id: notify.telegram_bot_659000495_155103022
        data_template:
          message: "Water leak has been detected @ {{ trigger.from_state.attributes.friendly_name }} !!!"
