---
input_datetime:
  ohad_iphone_alarm:
    name: Ohad iPhone alarm
    has_date: true
    has_time: true


input_boolean:
  master_bedroom_sleep_mode:
    name: sleep mode
    icon: mdi:sleep


light:
  - platform: template
    lights:
      master_bedroom_lights:
        value_template: >-
          {{
            is_state('switch.master_bedroom_spots', 'on') and
            is_state('switch.master_bedroom_light_and_fan_switch_1', 'on') and
            is_state('switch.shellyplus2pm_fcb4670e673c_switch_0', 'on')
          }}
        turn_on:
          action: homeassistant.turn_on
          target:
            entity_id:
              - switch.shellyplus2pm_fcb4670e673c_switch_0
              - switch.master_bedroom_light_and_fan_switch_1
              - switch.master_bedroom_spots
        turn_off:
          action: homeassistant.turn_off
          target:
            entity_id:
              - switch.shellyplus2pm_fcb4670e673c_switch_0
              - switch.master_bedroom_light_and_fan_switch_1
              - switch.master_bedroom_spots


template:
  - sensor:
      - name: "Master Bedroom AC Temperature"
        unit_of_measurement: "°C"
        state: "{{ state_attr('climate.master_bedroom_ac', 'current_temperature') }}"
        availability: "{{ state_attr('climate.master_bedroom_ac', 'current_temperature') is not none }}"
        device_class: temperature
        icon: mdi:thermometer

      - name: "Master Bedroom AC humidity"
        unit_of_measurement: "%"
        state: "{{ state_attr('climate.master_bedroom_ac', 'current_humidity') }}"
        availability: "{{ state_attr('climate.master_bedroom_ac', 'current_humidity') is not none }}"
        device_class: humidity
        icon: mdi:water-percent

      - name: "Master bedroom AC room temperature difference"
        unit_of_measurement: "°C"
        state: "{{ (state_attr('climate.master_bedroom_ac', 'current_temperature') - state_attr('climate.master_bedroom_ac', 'temperature')) | abs }}"
        availability: "{{ state_attr('climate.master_bedroom_ac', 'current_temperature') is not none }}"
        device_class: temperature
        icon: mdi:thermometer


sensor:
  - platform: derivative
    source: sensor.master_bedroom_ac_room_temperature_difference
    name: Master bedroom temp difference change per 10 minutes
    round: 1
    unit_time: min
    time_window: 10


automation:
  - alias: "Turn on master bedroom wardrobe light when the door is opened"
    id: master_bedroom_wardrobe_turn_light_when_the_door_is_opened
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.master_bedroom_wardrobe_contact
        from: 'off'
        to: 'on'
      - platform: homeassistant
        event: start
    condition:
      - condition: state
        entity_id: binary_sensor.master_bedroom_wardrobe_contact
        state: 'on'
    action:
      - action: homeassistant.turn_on
        entity_id: switch.shelly1pmminig3_34b7da8da318_switch_0


  - alias: "Turn off master bedroom wardrobe light when no motion is detected"
    id: master_bedroom_wardrobe_turn_light_off_no_motion_detected
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.master_bedroom_wardrobe_contact
        from: 'on'
        to: 'off'
      - platform: homeassistant
        event: start
    condition:
      - condition: state
        entity_id: binary_sensor.master_bedroom_wardrobe_contact
        state: 'off'
    action:
      - action: homeassistant.turn_off
        entity_id: switch.shelly1pmminig3_34b7da8da318_switch_0


  - alias: 'Open shutters in the morning when the alarm goes off'
    id: master_bedroom_shutters_open_alarm_goes_off
    trigger:
      - platform: state
        entity_id: input_datetime.ohad_iphone_alarm

    condition:
      - condition: template
        value_template: >
          {% set alarm_time = states('input_datetime.ohad_iphone_alarm') %}
          {% set current_time = now().strftime('%Y-%m-%d %H:%M:00') %}
          {% set current_time_obj = strptime(current_time, '%Y-%m-%d %H:%M:%S') %}
          {% set alarm_time_obj = strptime(alarm_time, '%Y-%m-%d %H:%M:%S') %}
          {{ (alarm_time_obj - current_time_obj).total_seconds() <= 600 }}
      - condition: state
        entity_id: input_boolean.away_mode
        state: 'off'

    action:
      - delay: '00:10:00'

      - action: cover.set_cover_position
        target:
          entity_id:
            - cover.master_bedroom_main_window
        data:
          position: 85


  - alias: 'Close master bedroom shutters at night'
    id: master_bedroom_shutters_close_night
    initial_state: false
    trigger:
      - platform: time
        at: '23:00:00'

    condition:
      - condition: state
        entity_id: input_boolean.away_mode
        state: 'off'

    action:
      - action: cover.set_cover_position
        target:
          entity_id:
            - cover.master_bedroom_main_window
        data:
          position: 20


  - alias: "Toggle spots on switch change"
    id: master_bedroom_spots_toggle_on_switch_change
    initial_state: true
    trigger:
      - platform: state
        entity_id: switch.shellyplus2pm_fcb4670e673c_switch_1
    action:
      - action: switch.toggle
        target:
          entity_id: switch.master_bedroom_spots


  - alias: 'Master bedroom bedside switch 01 - turn on main light'
    id: master_bedroom_bedside_switch_01_turn_on_main_light
    initial_state: true
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.master_bedroom_bedside_01_action
        to: 'button_2_single'

    action:
      - action: switch.turn_on
        target:
          entity_id: switch.master_bedroom_light_and_fan_switch_0


  - alias: 'Master bedroom bedside switch 01 - turn off main light'
    id: master_bedroom_bedside_switch_01_turn_off_main_light
    initial_state: true
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.master_bedroom_bedside_01_action
        to: 'button_1_single'

    action:
      - action: switch.turn_off
        target:
          entity_id: switch.master_bedroom_light_and_fan_switch_0


  - alias: 'Master bedroom bedside switch 01 - open shutters'
    id: master_bedroom_bedside_switch_01_open_shutters
    initial_state: true
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.master_bedroom_bedside_01_action
        to: 'button_4_single'

    action:
      - action: cover.set_cover_position
        data:
          position: 100
        target:
          entity_id:
            - cover.master_bedroom_main_window
            - cover.shellyplus2pm_c4d8d5582a90  # right
            - cover.shellyplus2pm_e465b8f38f54  # left


  - alias: 'Master bedroom bedside switch 01 - close shutters'
    id: master_bedroom_bedside_switch_01_close_shutter
    initial_state: true
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.master_bedroom_bedside_01_action
        to: 'button_3_single'

    action:
      - action: cover.set_cover_position
        data:
          position: 20
        target:
          entity_id:
            - cover.master_bedroom_main_window
            - cover.shellyplus2pm_c4d8d5582a90  # right
            - cover.shellyplus2pm_e465b8f38f54  # left


  - alias: 'Master bedroom bedside switch 01 - turn on AC'
    id: master_bedroom_bedside_switch_01_turn_on_ac
    initial_state: true
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.master_bedroom_bedside_01_action
        to: 'button_6_double'

    action:
      - choose:
          - conditions:
              - condition: numeric_state
                entity_id: sensor.openweathermap_feels_like_temperature
                above: 23
            sequence:
              - service: climate.set_hvac_mode
                target:
                  entity_id: climate.master_bedroom_ac
                data:
                  hvac_mode: 'cool'
        default:
          - service: climate.set_hvac_mode
            target:
              entity_id: climate.master_bedroom_ac
            data:
              hvac_mode: 'heat'


  - alias: 'Master bedroom bedside switch 01 - turn off AC'
    id: master_bedroom_bedside_switch_01_turn_off_ac
    initial_state: true
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.master_bedroom_bedside_01_action
        to: 'button_5_double'

    action:
      - action: climate.turn_off
        target:
          entity_id: climate.master_bedroom_ac


  - alias: 'Master bedroom bedside switch 02 - toggle main light'
    id: master_bedroom_bedside_switch_02_toggle_main_light
    initial_state: true
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.master_bedroom_bedside_02_action
        to: '1_single'

    action:
      - action: switch.toggle
        target:
          entity_id: switch.master_bedroom_light_and_fan_switch_0


  - alias: 'Master bedroom bedside switch 02 - toggle AC'
    id: master_bedroom_bedside_switch_02_toggle_ac
    initial_state: true
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.master_bedroom_bedside_02_action
        to: '2_single'

    action:
      - action: climate.toggle
        target:
          entity_id: climate.master_bedroom_ac


  - alias: 'Master bedroom bedside switch 02 - open shutters lights in'
    id: master_bedroom_bedside_switch_02_open_shutters_lights_in
    initial_state: true
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.master_bedroom_bedside_02_action
        to: '3_single'

    action:
      - action: cover.set_cover_position
        data:
          position: 70
        target:
          entity_id:
            - cover.master_bedroom_main_window
            - cover.shellyplus2pm_c4d8d5582a90  # right
            - cover.shellyplus2pm_e465b8f38f54  # left


  - alias: 'Master bedroom bedside switch 02 - open shutters complete'
    id: master_bedroom_bedside_switch_02_open_shutters_complete
    initial_state: true
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.master_bedroom_bedside_02_action
        to: '3_double'

    action:
      - action: cover.set_cover_position
        data:
          position: 100
        target:
          entity_id:
            - cover.master_bedroom_main_window
            - cover.shellyplus2pm_c4d8d5582a90  # right
            - cover.shellyplus2pm_e465b8f38f54  # left


  - alias: 'Master bedroom bedside switch 02 - control night light'
    id: master_bedroom_bedside_switch_02_night_light
    initial_state: true
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.master_bedroom_bedside_02_action
        to: '5_single'

    action:
      - action: switch.toggle
        target:
          entity_id: switch.sonoff_s20_02


  - alias: "Master bedroom - Turn AC off when no one is in the room"
    id: master_bedroom_no_presence_turn_ac_off
    initial_state: false
    trigger:
      - platform: state
        entity_id: binary_sensor.apollo_msr_2_398b60_radar_target
        from: 'on'
        to: 'off'
        for:
          minutes: 10

    condition:
      - condition: template
        value_template: >-
          {{ not is_state('climate.master_bedroom_ac', 'off') }}
      - condition: state
        entity_id: input_boolean.master_bedroom_sleep_mode
        state: 'off'

    action:
      - action: climate.turn_off
        data_template:
          entity_id: climate.master_bedroom_ac


  - alias: "Turn off master bedroom AC when no motion is detected"
    id: master_bedroom_turn_ac_off_no_motion_detected
    initial_state: false
    trigger:
      - platform: state
        entity_id: binary_sensor.apollo_msr_2_398b60_radar_target
        from: 'on'
        to: 'off'
        for:
          minutes: 5

      - platform: homeassistant
        event: start

    condition:
      - condition: state
        entity_id: binary_sensor.apollo_msr_2_398b60_radar_target
        state: 'off'
      - condition: time
        before: '23:00:00'
        after: '08:00:00'

    action:
      - action: homeassistant.turn_off
        entity_id: climate.master_bedroom_ac


  # - alias: "Master bedroom turn off sleep mode"
  #   id: master_bedroom_turn_off_sleep_mode
  #   initial_state: true
  #   trigger:
  #     - platform: event
  #       event_type: state_changed
  #       event_data:
  #         entity_id: switch.shelly1pmminig3_34b7da8eef08_switch_0
  #   condition:
  #     - condition: template
  #       value_template: >
  #         {{ not trigger.event.data.new_state.context.user_id and not trigger.event.data.new_state.context.parent_id }}
  #     - condition: state
  #       entity_id: switch.shelly1pmminig3_34b7da8eef08_switch_0
  #       state: 'on'
  #     - condition: state
  #       entity_id: input_boolean.master_bedroom_sleep_mode
  #       state: 'on'

  #   action:
  #     - action: input_boolean.turn_off
  #       entity_id: input_boolean.master_bedroom_sleep_mode


  - alias: Shutdown AC 1 hour after target temperature has been reached
    id: master_bedroom_shutdown_ac_target_temp_reached
    initial_state: false
    trigger:
      - platform: numeric_state
        entity_id: sensor.master_bedroom_temp_difference_change_per_10_minutes
        above: -1
        below: 1
        for:
          hours: 1
      - platform: template
        value_template: >-
          {{
            states('climate.master_bedroom_ac') != 'off' and
            (now() - states.climate.master_bedroom_ac.last_changed).total_seconds() > 3600
          }}

    condition:
      - condition: template
        value_template: >
          {{
            states('climate.master_bedroom_ac') != 'off' and
            (now() - states.climate.master_bedroom_ac.last_changed).total_seconds() > 3600
          }}
      - condition: numeric_state
        entity_id: sensor.master_bedroom_temp_difference_change_per_10_minutes
        above: -1
        below: 1

    action:
      - action: climate.turn_off
        entity_id: climate.master_bedroom_ac


  - alias: "Close master bedroom covers if bathroom humidity is above 85 / restore when below 50"
    id: master_bathroom_covers_on_humidity_change
    mode: single
    initial_state: false
    trigger:
      - platform: numeric_state
        entity_id: sensor.master_bathroom_temperature_humidity
        above: 85
        for:
          minutes: 2
      - platform: numeric_state
        entity_id: sensor.master_bathroom_temperature_humidity
        below: 50
        for:
          minutes: 2

    action:
      - choose:
          # High humidity branch
          - conditions:
              - condition: template
                value_template: "{{ trigger.to_state.state | float > 85 }}"
            sequence:
              # 1) Capture current positions in an ad-hoc scene
              - service: scene.create
                data:
                  scene_id: master_bedroom_covers_before_humidity
                  snapshot_entities:
                    - cover.shellyplus2pm_e465b8f38f54
                    - cover.shellyplus2pm_c4d8d5582a90

              # 2) Check and partially close covers if they're above 45
              - choose:
                  - conditions:
                      - condition: numeric_state
                        entity_id: cover.shellyplus2pm_e465b8f38f54
                        attribute: current_position
                        above: 45
                    sequence:
                      - service: cover.set_cover_position
                        data:
                          entity_id: cover.shellyplus2pm_e465b8f38f54
                          position: 45
              - choose:
                  - conditions:
                      - condition: numeric_state
                        entity_id: cover.shellyplus2pm_c4d8d5582a90
                        attribute: current_position
                        above: 45
                    sequence:
                      - service: cover.set_cover_position
                        data:
                          entity_id: cover.shellyplus2pm_c4d8d5582a90
                          position: 45

          # Low humidity branch
          - conditions:
              - condition: template
                value_template: "{{ trigger.to_state.state | float < 50 }}"
              - condition: state
                entity_id: sun.sun
                state: above_horizon
            sequence:
              - service: scene.turn_on
                data:
                  entity_id: scene.master_bedroom_covers_before_humidity

        default: []


  - alias: "Close master bedroom covers on sunset"
    id: master_bathroom_covers_on_sunset
    mode: single
    initial_state: true
    trigger:
      - platform: sun
        event: sunset

    action:
      - choose:
          - conditions:
              - condition: numeric_state
                entity_id: cover.shellyplus2pm_e465b8f38f54
                attribute: current_position
                above: 45
            sequence:
              - service: cover.set_cover_position
                data:
                  entity_id: cover.shellyplus2pm_e465b8f38f54
                  position: 45
      - choose:
          - conditions:
              - condition: numeric_state
                entity_id: cover.shellyplus2pm_c4d8d5582a90
                attribute: current_position
                above: 45
            sequence:
              - service: cover.set_cover_position
                data:
                  entity_id: cover.shellyplus2pm_c4d8d5582a90
                  position: 45
      - choose:
          - conditions:
              - condition: numeric_state
                entity_id: cover.master_bedroom_main_window
                attribute: current_position
                above: 30
            sequence:
              - service: cover.set_cover_position
                data:
                  entity_id: cover.master_bedroom_main_window
                  position: 30


  - alias: "Open covers to 100% when school is in session"
    id: master_bedroom_open_covers_on_a_school_day
    description: "At 8 AM, open covers to 100% if it's not school vacation"
    initial_state: true
    trigger:
      - platform: time
        at: "08:00:00"

    condition:
      - condition: state
        entity_id: binary_sensor.high_vacation
        state: 'off'
      - condition: time
        weekday:
          - sun
          - mon
          - tue
          - wed
          - thu

    action:
      - action: cover.set_cover_position
        target:
          entity_id:
            - cover.shellyplus2pm_c4d8d5582a90
            - cover.shellyplus2pm_e465b8f38f54
        data:
          position: 100


  - alias: "Toggle master bedroom lights by Ohad bedside switch"
    id: master_bedroom_toggle_lights_by_ohad_bedside_switch
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.master_bedroom_switches_i4_left_side_input_3

    condition:
      - condition: template
        value_template: >
          {{ trigger.from_state.state != 'unavailable' }}

    action:
      - action: light.toggle
        entity_id: light.master_bedroom_lights
