---
sensor:
  - platform: mqtt_room
    name: "ohad_ble"
    device_id: "ohad"
    state_topic: "espresense/devices/ohad"
    timeout: 5
    away_timeout: 120

  - platform: mqtt_room
    name: "rinat_ble"
    device_id: "rinat"
    state_topic: "espresense/devices/rinat"
    timeout: 5
    away_timeout: 120

  - platform: mqtt_room
    name: "ella_ble"
    device_id: "ella"
    state_topic: "espresense/devices/ella"
    timeout: 5
    away_timeout: 120

  - platform: mqtt_room
    name: "roi_ble"
    device_id: "roi"
    state_topic: "espresense/devices/roi"
    timeout: 5
    away_timeout: 120

  - platform: mqtt_room
    name: "adi_ble"
    device_id: "adi"
    state_topic: "espresense/devices/adi"
    timeout: 5
    away_timeout: 120

  - platform: history_stats
    name: Ketem inside today
    entity_id: binary_sensor.ketem
    state: "on"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"

  - platform: history_stats
    name: Ketem outside today
    entity_id: binary_sensor.ketem
    state: "off"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"

automation:
- alias: "Alert: Ketem presence unchanged for 12 hours (away mode)"
  id: presence_ketem_didnt_enter_or_exit_in_the_past_12_hours_away_mode
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.ketem
      for:
        hours: 12

  condition:
    - condition: state
      entity_id: input_boolean.away_mode
      state: 'on'

  action:
    - action: notify.ohad_telegram
      data:
        title: "Alert: Cat presence sensor unchanged"
        message: >
          *State:* `{{ states('binary_sensor.ketem') }}`
          *Unchanged since:* `{{ relative_time(states.binary_sensor.ketem.last_changed) }}`
        data:
          parse_mode: markdown
