---
sensor:
  - platform: mqtt_room
    name: "ohad_ble"
    device_id: "ohad"
    state_topic: "espresense/devices/ohad"
    timeout: 5
    away_timeout: 120

  - platform: mqtt_room
    name: "rinat_ble"
    device_id: "rinat"
    state_topic: "espresense/devices/rinat"
    timeout: 5
    away_timeout: 120

  - platform: mqtt_room
    name: "ella_ble"
    device_id: "ella"
    state_topic: "espresense/devices/ella"
    timeout: 5
    away_timeout: 120

  - platform: mqtt_room
    name: "roi_ble"
    device_id: "roi"
    state_topic: "espresense/devices/roi"
    timeout: 5
    away_timeout: 120

  - platform: mqtt_room
    name: "adi_ble"
    device_id: "adi"
    state_topic: "espresense/devices/adi"
    timeout: 5
    away_timeout: 120

  - platform: history_stats
    name: Ketem inside today
    entity_id: binary_sensor.ketem  # yamllint disable-line rule:indentation
    state: "on"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"

  - platform: history_stats
    name: Ketem outside today
    entity_id: binary_sensor.ketem
    state: "off"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"


template:
  - sensor:
      - name: "People at Home"
        unique_id: people_at_home
        state: >
          {{ expand([
              'person.ohad_benita',
              'person.rinat_benita',
              'person.ella_benita',
              'person.roi_benita',
              'person.adi_benita'
            ])
            | selectattr('state', 'eq', 'home')
            | list
            | count }}
        attributes:
          persons_home: >
            {{ expand([
                'person.ohad_benita',
                'person.rinat_benita',
                'person.ella_benita',
                'person.roi_benita',
                'person.adi_benita'
              ])
              | selectattr('state', 'eq', 'home')
              | map(attribute='entity_id')
              | list }}


automation:
  - alias: "Alert: Ketem presence unchanged for 20 hours (away mode)"
    id: presence_ketem_didnt_enter_or_exit_in_the_past_20_hours_away_mode
    mode: single

    trigger:
      - platform: state
        entity_id: binary_sensor.ketem
        for:
          hours: 20

    condition:
      - condition: state
        entity_id: input_boolean.away_mode
        state: "on"

    action:
      - action: notify.send_message
        target:
          entity_id: notify.telegram_bot_659000495_155103022
        data:
          title: "Ketem notifications"
          message: >-
            Status: {% if is_state('binary_sensor.ketem', 'off') %}Away{% else %}Home{% endif %}
            Unchanged since: {{ relative_time(states.binary_sensor.ketem.last_changed) }}
          data:
            parse_mode: markdown

      - action: notify.mobile_app_ohadbenita
        data:
          title: "Ketem notifications"
          message: >-
            Status: {% if is_state('binary_sensor.ketem', 'off') %}Away{% else %}Home{% endif %},
            unchanged since {{ relative_time(states.binary_sensor.ketem.last_changed) }}
          data:
            push:
              sound:
                name: default
                critical: 1
                volume: 1.0

      - action: notify.mobile_app_ellas_iphone
        data:
          title: "Ketem notifications"
          message: >-
            Status: {% if is_state('binary_sensor.ketem', 'off') %}Away{% else %}Home{% endif %},
            unchanged since {{ relative_time(states.binary_sensor.ketem.last_changed) }}
          data:
            push:
              sound:
                name: default
                critical: 1
                volume: 1.0

      # Roi
      - action: notify.mobile_app_rois_iphone
        data:
          title: "Ketem notifications"
          message: >-
            Status: {% if is_state('binary_sensor.ketem', 'off') %}Away{% else %}Home{% endif %},
            unchanged since {{ relative_time(states.binary_sensor.ketem.last_changed) }}
          data:
            push:
              sound:
                name: default
                critical: 1
                volume: 1.0

      # Adi (Hebrew)
      - action: notify.mobile_app_adidibenita
        data:
          title: "התראות קטם"
          message: >-
            מצב: {% if is_state('binary_sensor.ketem', 'off') %}מחוץ לבית{% else %}בבית{% endif %},
            ללא שינוי מאז {{ relative_time(states.binary_sensor.ketem.last_changed) }}
          data:
            push:
              sound:
                name: default
                critical: 1
                volume: 1.0

      # Rinat
      - action: notify.mobile_app_rinats_iphone
        data:
          title: "Ketem notifications"
          message: >-
            Status: {% if is_state('binary_sensor.ketem', 'off') %}Away{% else %}Home{% endif %},
            unchanged since {{ relative_time(states.binary_sensor.ketem.last_changed) }}
          data:
            push:
              sound:
                name: default
                critical: 1
                volume: 1.0
