---
automation:
  - alias: Lehavim red alert
    id: red_alert_lehavim
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.oref_alert
        to: 'on'

    action:
      - action: notify.ohad_telegram
        data_template:
          message: >-
            Red alert in Lehavim, you got 45 seconds to get to a shelter

      - action: homeassistant.turn_on
        entity_id:
          - switch.shelly1pmminig3_34b7da8b78c4_switch_0
          - switch.shelly1pmminig3_34b7da8a0338_switch_0

      - action: script.alexa_notification
        data:
          alexa_device: media_player.everywhere
          notification_type: announce
          current_volume: >-
            {{ state_attr('media_player.kitchen_echo', 'volume_level') }}
          message: >-
            Red alert, please head to the nearest shelter now.
            Red alert, please head to the nearest shelter now.
            Red alert, please head to the nearest shelter now!
