---
binary_sensor:
  - platform: rest
    name: lehavim_red_alert
    unique_id: lehavim_red_alert
    resource: !secret red_alert_lehavim_url
    scan_interval: 2
    value_template: >-
      {{ bool(value_json.exists) }}

automation:
  - alias: Lehavim red alert
    id: red_alert_lehavim
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.lehavim_red_alert
        to: 'on'

    action:
      - action: notify.ohad_telegram
        data_template:
          message: >-
            Red alert in Lehavim, you got 45 seconds to get to a shelter

      - action: script.alexa_notification
        data:
          alexa_device: media_player.everywhere
          notification_type: announce
          current_volume: >-
            {{ state_attr('media_player.kitchen_echo', 'volume_level') }}
          message: >-
            Red alert, please head to the nearest shelter now.
            Red alert, please head to the nearest shelter now.
            Red alert, please head to the nearest shelter now!
