---
input_boolean:
  roi_sleep_mode:
    name: Is sleep mode enabled
    icon: mdi:sleep

automation:
  - alias: "Roi Room - Set AC to night mode (summer)"
    id: roi_room_ac_night_automation
    initial_state: true
    trigger:
      - platform: time
        at: "00:30:00"
      - platform: time
        at: "01:30:00"

    condition:
      condition: and
      conditions:
        - condition: template
          value_template: >-
            {{ not (
                is_state_attr('climate.roi_room_ac', 'preset_mode', 'sleep') and
                is_state_attr('climate.roi_room_ac', 'temperature', 24) and
                is_state_attr('climate.roi_room_ac', 'fan_mode', 'silent') and
                is_state_attr('climate.roi_room_ac', 'swing_mode', 'both')
              )
            }}
        - condition: state
          entity_id: climate.roi_room_ac
          state: 'cool'

    action:
      - action: switch.turn_off
        entity_id: switch.roi_room_ac_beeper

      - action: climate.set_preset_mode
        data:
          preset_mode: sleep
          entity_id: climate.roi_room_ac
      - action: climate.set_temperature
        data:
          temperature: 24
          entity_id: climate.roi_room_ac
      - action: climate.set_fan_mode
        data:
          fan_mode: silent
          entity_id: climate.roi_room_ac
      - action: climate.set_swing_mode
        data:
          swing_mode: both
          entity_id: climate.roi_room_ac

      - action: switch.turn_on
        entity_id: switch.roi_room_ac_beeper

  - alias: "Roi Room - Turn AC off when no one is in the room"
    id: roi_room_no_presence_turn_ac_off
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.apollo_msr_1_cd44f0_radar_target
        to: 'off'
        for:
          minutes: 10

    condition:
      - condition: template
        value_template: >-
          {{ not is_state('climate.roi_ac', 'off') }}
      - condition: state
        entity_id: input_boolean.roi_sleep_mode
        state: 'off'

    action:
      - action: climate.turn_off
        data_template:
          entity_id: climate.roi_room_ac

  - alias: "Turn on Roi room light on motion"
    id: roi_room_turn_light_on_motion
    initial_state: false
    trigger:
      - platform: state
        entity_id: binary_sensor.apollo_msr_1_cd44f0_radar_target
        to: 'on'

      - platform: homeassistant
        event: start

    condition:
      - condition: state
        entity_id: binary_sensor.apollo_msr_1_cd44f0_radar_target
        state: 'on'
      - condition: time
        before: '23:00:00'
        after: '08:00:00'
      - condition: state
        entity_id: input_boolean.roi_sleep_mode
        state: 'off'

    action:
      - action: homeassistant.turn_on
        entity_id:
          - switch.shellyplus2pm_10061ccdc57c_switch_0  # light
          - switch.shellyplus2pm_10061ccdc57c_switch_1  # fan


  - alias: "Turn off Roi room light when no motion is detected"
    id: roi_room_turn_light_off_no_motion_detected
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.apollo_msr_1_cd44f0_radar_target
        to: 'off'
        for:
          minutes: 5

      - platform: homeassistant
        event: start

    condition:
      - condition: state
        entity_id: binary_sensor.apollo_msr_1_cd44f0_radar_target
        state: 'off'
      - condition: time
        before: '23:00:00'
        after: '08:00:00'

    action:
      - action: homeassistant.turn_off
        entity_id:
          - switch.shellyplus2pm_10061ccdc57c_switch_0  # light
          - switch.shellyplus2pm_10061ccdc57c_switch_1  # fan


  - alias: "Roi room turn off sleep mode"
    id: roi_room_turn_off_sleep_mode
    initial_state: true
    trigger:
      - platform: event
        event_type: state_changed
        event_data:
          entity_id: switch.shellyplus2pm_10061ccdc57c_switch_0
    condition:
      - condition: template
        value_template: >
          {{ not trigger.event.data.new_state.context.user_id and not trigger.event.data.new_state.context.parent_id }}
      - condition: state
        entity_id: switch.shellyplus2pm_10061ccdc57c_switch_0
        state: 'on'
      - condition: state
        entity_id: input_boolean.roi_sleep_mode
        state: 'on'

    action:
      - action: input_boolean.turn_off
        entity_id: input_boolean.roi_sleep_mode
