---
input_boolean:
  roi_sleep_mode:
    name: sleep mode
    icon: mdi:sleep


template:
  - sensor:
      - name: "Roi Room AC Temperature"
        unit_of_measurement: "°C"
        state: "{{ state_attr('climate.roi_room_ac', 'current_temperature') }}"
        availability: "{{ state_attr('climate.roi_room_ac', 'current_temperature') is not none }}"
        device_class: temperature
        icon: mdi:thermometer


sensor:
  - platform: derivative
    source: sensor.roi_room_temperature
    name: Roi room temp difference change per 10 minutes
    round: 1
    unit_time: min
    time_window: 10


automation:
  - alias: "Roi Room - Set AC to night mode (summer)"
    id: roi_room_ac_night_automation
    initial_state: true
    trigger:
      - platform: time
        at: "00:30:00"
      - platform: time
        at: "01:30:00"

    condition:
      condition: and
      conditions:
        - condition: template
          value_template: >-
            {{ not (
                is_state_attr('climate.roi_room_ac', 'preset_mode', 'sleep') and
                is_state_attr('climate.roi_room_ac', 'temperature', 23) and
                is_state_attr('climate.roi_room_ac', 'fan_mode', 'silent') and
                is_state_attr('climate.roi_room_ac', 'swing_mode', 'both')
              )
            }}
        - condition: state
          entity_id: climate.roi_room_ac
          state: 'cool'

    action:
      - action: switch.turn_off
        entity_id: switch.roi_room_ac_beeper

      - action: climate.set_preset_mode
        data:
          preset_mode: sleep
          entity_id: climate.roi_room_ac
      - action: climate.set_temperature
        data:
          temperature: 23
          entity_id: climate.roi_room_ac
      - action: climate.set_fan_mode
        data:
          fan_mode: silent
          entity_id: climate.roi_room_ac
      - action: climate.set_swing_mode
        data:
          swing_mode: both
          entity_id: climate.roi_room_ac

      - action: switch.turn_on
        entity_id: switch.roi_room_ac_beeper

  - alias: "Roi Room - Turn AC off when no one is in the room"
    id: roi_room_no_presence_turn_ac_off
    initial_state: false
    trigger:
      - platform: state
        entity_id: binary_sensor.apollo_msr_1_cd44f0_radar_target
        to: 'off'
        for:
          minutes: 20

    condition:
      - condition: template
        value_template: >-
          {{ not is_state('climate.roi_ac', 'off') }}
      - condition: state
        entity_id: input_boolean.roi_sleep_mode
        state: 'off'

    action:
      - action: climate.turn_off
        data_template:
          entity_id: climate.roi_room_ac

  - alias: "Turn on Roi room light on motion"
    id: roi_room_turn_light_on_motion
    initial_state: false
    trigger:
      - platform: state
        entity_id: binary_sensor.occupancy_sensor_71bf_occupancy
        to: 'on'

      - platform: homeassistant
        event: start

    condition:
      - condition: state
        entity_id: binary_sensor.occupancy_sensor_71bf_occupancy
        state: 'on'
      - condition: time
        before: '23:00:00'
        after: '08:00:00'
      - condition: state
        entity_id: input_boolean.roi_sleep_mode
        state: 'off'

    action:
      - action: homeassistant.turn_on
        entity_id:
          - switch.shellyplus2pm_10061ccdc57c_switch_0  # light
          # - switch.shellyplus2pm_10061ccdc57c_switch_1  # fan


  - alias: "Turn off Roi room fan when no motion is detected"
    id: roi_room_turn_light_off_no_motion_detected
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.occupancy_sensor_71bf_occupancy
        to: 'off'
        for:
          minutes: 15

      - platform: homeassistant
        event: start

    condition:
      - condition: state
        entity_id: binary_sensor.occupancy_sensor_71bf_occupancy
        state: 'off'
      - condition: time
        before: '23:00:00'
        after: '07:00:00'

    action:
      - action: homeassistant.turn_off
        entity_id:
          - switch.shellyplus2pm_10061ccdc57c_switch_0  # light
          - switch.shellyplus2pm_10061ccdc57c_switch_1  # fan


  - alias: "Roi room turn off sleep mode"
    id: roi_room_turn_off_sleep_mode
    initial_state: true
    trigger:
      - platform: event
        event_type: state_changed
        event_data:
          entity_id: switch.shellyplus2pm_10061ccdc57c_switch_0
    condition:
      - condition: template
        value_template: >
          {{ not trigger.event.data.new_state.context.user_id and not trigger.event.data.new_state.context.parent_id }}
      - condition: state
        entity_id: switch.shellyplus2pm_10061ccdc57c_switch_0
        state: 'on'
      - condition: state
        entity_id: input_boolean.roi_sleep_mode
        state: 'on'

    action:
      - action: input_boolean.turn_off
        entity_id: input_boolean.roi_sleep_mode


  - alias: 'Roi room - Handle Bedside button actions'
    id: roi_room_bedside_button_actions
    initial_state: true
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.roi_bedside_action

    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: sensor.roi_bedside_action
                state: 'single'
            sequence:
              - action: switch.toggle
                target:
                  entity_id: switch.shellyplus2pm_10061ccdc57c_switch_0  # light

          - conditions:
              - condition: state
                entity_id: sensor.roi_bedside_action
                state: 'double'
            sequence:
              - action: switch.toggle
                target:
                  entity_id: switch.shellyplus2pm_10061ccdc57c_switch_1  # fan

          - conditions:
              - condition: state
                entity_id: sensor.roi_bedside_action
                state: 'hold'
            sequence:
              - choose:
                  - conditions:
                      - condition: state
                        entity_id: climate.roi_room_ac
                        state: 'off'
                    sequence:
                      - choose:
                          - conditions:
                              - condition: numeric_state
                                entity_id: sensor.openweathermap_feels_like_temperature
                                above: 23
                            sequence:
                              - service: climate.set_hvac_mode
                                target:
                                  entity_id: climate.roi_room_ac
                                data:
                                  hvac_mode: 'cool'
                        default:
                          - service: climate.set_hvac_mode
                            target:
                              entity_id: climate.roi_room_ac
                            data:
                              hvac_mode: 'heat'
                default:
                  - service: climate.turn_off
                    target:
                      entity_id: climate.roi_room_ac


  - alias: "Roi room entrance switch fan control"
    id: roi_room_entrance_switch_fan_control
    initial_state: true
    trigger:
      - platform: state
        entity_id: switch.shelly1pmminig3_54320454e6dc_switch_0

    action:
      - action: switch.toggle
        entity_id: switch.shellyplus2pm_10061ccdc57c_switch_1    # fan


  - alias: Shutdown Roi room AC 1 hour after target temperature has been reached
    id: roi_room_shutdown_ac_target_temp_reached
    initial_state: false
    trigger:
      - platform: numeric_state
        entity_id: sensor.roi_room_temp_difference_change_per_10_minutes
        above: -1
        below: 1
        for:
          hours: 1
      - platform: template
        value_template: >-
          {{
            states('climate.roi_room_ac') != 'off' and
            (now() - states.climate.roi_room_ac.last_changed).total_seconds() > 3600
          }}

    condition:
      - condition: template
        value_template: >
          {{
            states('climate.roi_room_ac') != 'off' and
            (now() - states.climate.roi_room_ac.last_changed).total_seconds() > 3600
          }}
      - condition: numeric_state
        entity_id: sensor.roi_room_temp_difference_change_per_10_minutes
        above: -1
        below: 1

    action:
      - action: climate.turn_off
        entity_id: climate.roi_room_ac
