---
input_text:
  person_detection_snapshot_filename:
    name: Snapshot file name


binary_sensor:
  - platform: template
    sensors:
      dining_room_main_window_contact:
        friendly_name: "Dining room main window"
        device_class: opening
        value_template: >
          {{ is_state('binary_sensor.dining_room_main_window_01_contact', 'on') or is_state('binary_sensor.dining_room_main_window_02_contact', 'on') }}

      living_room_middle_window_contact:
        friendly_name: "Living room middle window"
        device_class: opening
        value_template: >
          {{ is_state('binary_sensor.living_room_middle_window_01_contact', 'on') or is_state('binary_sensor.living_room_middle_window_02_contact', 'on') }}

      living_room_right_window_contact:
        friendly_name: "Living room right window"
        device_class: opening
        value_template: >
          {{ is_state('binary_sensor.living_room_right_window_01_contact', 'on') or is_state('binary_sensor.living_room_right_window_02_contact', 'on') }}

      living_room_left_window_contact:
        friendly_name: "Living room left window"
        device_class: opening
        value_template: >
          {{ is_state('binary_sensor.living_room_left_window_01_contact', 'on') or is_state('binary_sensor.living_room_left_window_02_contact', 'on') }}

      all_doors_and_windows:
        friendly_name: "All Doors and Windows"
        device_class: opening
        value_template: >
          {{ is_state('binary_sensor.kitchen_door_contact', 'on') or
             is_state('binary_sensor.entrance_door_contact', 'on') or
             is_state('binary_sensor.kids_bathroom_door_contact', 'on') or
             is_state('binary_sensor.kitchen_window_01_contact', 'on') or
             is_state('binary_sensor.dining_room_left_window_01_contact', 'on') or
             is_state('binary_sensor.dining_room_right_window_01_contact', 'on') or
             is_state('binary_sensor.dining_room_main_window_contact', 'on') or
             is_state('binary_sensor.living_room_middle_window_contact', 'on') or
             is_state('binary_sensor.living_room_right_window_contact', 'on') or
             is_state('binary_sensor.living_room_left_window_contact', 'on') or
             is_state('binary_sensor.study_window_contact', 'on') }}


lock:
  - platform: template
    name: "All doors"
    value_template: >
      {{ is_state('lock.entrance_door', 'locked') and
         is_state('lock.kids_bathroom_door', 'locked') and
         is_state('lock.kitchen_door', 'locked') and
         is_state('lock.clinic_door', 'locked')
         }}
    lock:
      action: lock.lock
      target:
        entity_id:
          - lock.entrance_door
          - lock.kids_bathroom_door
          - lock.kitchen_door
          - lock.clinic_door
    unlock:
      action: lock.unlock
      target:
        entity_id:
          - lock.entrance_door
          - lock.kids_bathroom_door
          - lock.kitchen_door
          - lock.clinic_door


automation:
  - alias: "Security - Camera snapshot on person trigger"
    id: security_camera_snapshot_on_person_trigger
    mode: queued
    initial_state: false
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.front_porch_and_parking_person
          - binary_sensor.main_entrance_person
          - binary_sensor.kitchen_path_person
        to: 'on'
    action:
      - action: input_text.set_value
        data:
          entity_id: input_text.person_detection_snapshot_filename
          value: >-
            {{ '/config/www/camera_captures/' + trigger.entity_id.split('.')[1].replace('_person', '') + '/' + now().strftime('%Y_%m_%d_%H_%M') + '.jpg' }}
      - delay:
          seconds: 2
      - action: camera.snapshot
        data:
          entity_id: >-
            {{ 'camera.' + trigger.entity_id.split('.')[1].replace('_person', '_snapshots_clear') }}
          filename: "{{ states('input_text.person_detection_snapshot_filename') }}"
      - action: notify.ohad_telegram
        data:
          title: "Security - human presence detected"
          message: >-
            Presence detected @ {{ trigger.entity_id.split('.')[1].replace('_person', '').replace('_', ' ') | title }}
          data:
            photo:
              - file: "{{ states('input_text.person_detection_snapshot_filename') }}"
                caption: Snapshot taken at {{ trigger.entity_id.split('.')[1].replace('_person', '').replace('_', ' ') | title }}


  - alias: "Security - Lock all doors in the night"
    id: security_lock_all_doors_in_the_night
    mode: single
    initial_state: true
    trigger:
      - platform: time
        at: '23:00:00'
      - platform: time
        at: '00:00:00'

    action:
      - action: lock.lock
        entity_id:
          - lock.entrance_door
          - lock.kids_bathroom_door
          - lock.kitchen_door
          - lock.clinic_door
