---
input_text:
  person_detection_snapshot_filename:
    name: Snapshot file name

input_boolean:
  turn_everything_off_failed:
    name: Turn everything off failed


binary_sensor:
  - platform: template
    sensors:
      dining_room_main_window_contact:
        friendly_name: "Dining room main window"
        device_class: opening
        value_template: >
          {{ is_state('binary_sensor.dining_room_main_window_01_contact', 'on') or is_state('binary_sensor.dining_room_main_window_02_contact', 'on') }}

      living_room_middle_window_contact:
        friendly_name: "Living room middle window"
        device_class: opening
        value_template: >
          {{ is_state('binary_sensor.living_room_middle_window_01_contact', 'on') or is_state('binary_sensor.living_room_middle_window_02_contact', 'on') }}

      living_room_right_window_contact:
        friendly_name: "Living room right window"
        device_class: opening
        value_template: >
          {{ is_state('binary_sensor.living_room_right_window_01_contact', 'on') or is_state('binary_sensor.living_room_right_window_02_contact', 'on') }}

      living_room_left_window_contact:
        friendly_name: "Living room left window"
        device_class: opening
        value_template: >
          {{ is_state('binary_sensor.living_room_left_window_01_contact', 'on') or is_state('binary_sensor.living_room_left_window_02_contact', 'on') }}

      all_doors_and_windows:
        friendly_name: "All Doors and Windows"
        device_class: opening
        value_template: >
          {{
            is_state('binary_sensor.kitchen_door_contact', 'on') or
            is_state('binary_sensor.entrance_door_contact', 'on') or
            is_state('binary_sensor.kids_bathroom_door_contact', 'on') or
            is_state('binary_sensor.kitchen_window_01_contact', 'on') or
            is_state('binary_sensor.dining_room_left_window_01_contact', 'on') or
            is_state('binary_sensor.dining_room_right_window_01_contact', 'on') or
            is_state('binary_sensor.dining_room_main_window_contact', 'on') or
            is_state('binary_sensor.living_room_middle_window_contact', 'on') or
            is_state('binary_sensor.living_room_right_window_contact', 'on') or
            is_state('binary_sensor.living_room_left_window_contact', 'on') or
            is_state('binary_sensor.study_window_contact', 'on') or
            is_state('binary_sensor.roi_window_contact', 'on') or
            is_state('binary_sensor.adi_window_contact', 'on')
          }}

      all_windows:
        friendly_name: "All Windows"
        device_class: opening
        value_template: >
          {{
            is_state('binary_sensor.dining_room_left_window_01_contact', 'on') or
            is_state('binary_sensor.dining_room_right_window_01_contact', 'on') or
            is_state('binary_sensor.dining_room_main_window_contact', 'on') or
            is_state('binary_sensor.living_room_middle_window_contact', 'on') or
            is_state('binary_sensor.living_room_right_window_contact', 'on') or
            is_state('binary_sensor.living_room_left_window_contact', 'on') or
            is_state('binary_sensor.study_window_contact', 'on') or
            is_state('binary_sensor.roi_window_contact', 'on') or
            is_state('binary_sensor.adi_window_contact', 'on')
          }}


lock:
  - platform: template
    name: "All doors"
    value_template: >
      {{ is_state('lock.entrance_door', 'locked') and
         is_state('lock.kids_bathroom_door', 'locked') and
         is_state('lock.kitchen_door', 'locked') and
         is_state('lock.clinic_door', 'locked')
         }}
    lock:
      action: lock.lock
      target:
        entity_id:
          - lock.entrance_door
          - lock.kids_bathroom_door
          - lock.kitchen_door
          - lock.clinic_door
    unlock:
      action: lock.unlock
      target:
        entity_id:
          - lock.entrance_door
          - lock.kids_bathroom_door
          - lock.kitchen_door
          - lock.clinic_door


automation:
  - alias: "Security - Camera snapshot on person trigger"
    id: security_camera_snapshot_on_person_trigger
    mode: queued
    initial_state: false
    trigger:
      - platform: state
        entity_id: binary_sensor.main_entrance_person
        to: 'on'

    condition:
      - condition: state
        entity_id: alarm_control_panel.alarmo
        state: "armed_away"

    action:
      - action: input_text.set_value
        data:
          entity_id: input_text.person_detection_snapshot_filename
          value: >-
            {{ '/config/www/camera_captures/' + trigger.entity_id.split('.')[1].replace('_person', '') + '/' + now().strftime('%Y_%m_%d_%H_%M') + '.jpg' }}
      - action: camera.snapshot
        data:
          entity_id: >-
            {{ 'camera.' + trigger.entity_id.split('.')[1].replace('_person', '_snapshots_clear') }}
          filename: "{{ states('input_text.person_detection_snapshot_filename') }}"
      - delay:
          seconds: 1
      - action: notify.ohad_telegram
        data:
          title: "Security - human presence detected"
          message: >-
            Presence detected @ {{ trigger.entity_id.split('.')[1].replace('_person', '').replace('_', ' ') | title }}
          data:
            photo:
              - file: "{{ states('input_text.person_detection_snapshot_filename') }}"
                caption: Snapshot taken at {{ trigger.entity_id.split('.')[1].replace('_person', '').replace('_', ' ') | title }}


  - alias: "Security - Lock all doors in the night"
    id: security_lock_all_doors_in_the_night
    mode: single
    initial_state: true
    trigger:
      - platform: time
        at: '23:00:00'
      - platform: time
        at: '00:00:00'

    action:
      - action: lock.lock
        entity_id:
          - lock.entrance_door
          - lock.kids_bathroom_door
          - lock.kitchen_door
          - lock.clinic_door

  - alias: Disarm alarm when we are back
    id: security_disarm_alarm_when_entrance_door_is_unlocked
    mode: single
    initial_state: true
    trigger:
      - platform: state
        entity_id: lock.entrance_door
        to: unlocked

    condition:
      - condition: state
        entity_id: alarm_control_panel.alarmo
        state: armed_away

    action:
      - action: alarmo.disarm
        data:
          entity_id: alarm_control_panel.alarmo
          code: !secret alarmo_ohad_code


  - alias: Alert on entrance door open during nighttime
    id: security_alert_on_entrance_door_open_during_nighttime
    mode: single
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.entrance_door_contact
        to: 'on'
        for:
          minutes: 10

    condition:
      - condition: time
        after: '23:00:00'
        before: '07:00:00'

    action:
      - action: notify.ohad_telegram
        data:
          title: "Security - entrance door is open"
          message: >-
            The entrance door has been open for the past 10 minutes, please close it as soon as possible.
      - action: script.alexa_notification
        data:
          alexa_device: media_player.master_bedroom_echo
          notification_type: announce
          current_volume: >-
            {{ state_attr('media_player.master_bedroom_echo', 'volume_level') }}
          message: >-
            The entrance door is open for 10 minutes, please close it.

  - alias: Turn everything off script execution failed
    id: security_turn_everything_off_script_failed
    mode: single
    initial_state: true
    trigger:
      - platform: state
        entity_id: input_boolean.turn_everything_off_failed
        to: 'on'
        for:
          minutes: 3

    action:
      - action: notify.ohad_telegram
        data:
          message: 'Turn everything off automation failed to execute.'
