---
automation:
  - alias: "Study Room - Turn lights off when no one is in the room"
    id: study_room_turn_ac_and_lights_off
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.apollo_msr_1_ce7700_radar_target
        to: 'off'
        for:
          minutes: 2

      - platform: homeassistant
        event: start

    condition:
      - condition: state
        entity_id: switch.shellyplus1pm_e465b8f12024_switch_0
        state: 'on'
      - condition: state
        entity_id: binary_sensor.apollo_msr_1_ce7700_radar_target
        state: 'off'

    action:
      - action: homeassistant.turn_off
        entity_id: switch.shellyplus1pm_e465b8f12024_switch_0


  - alias: "Study Room - Turn on the lights when motion is detected"
    initial_state: true
    id: study_room_turn_lights_on_motion_detected
    trigger:
      - platform: state
        entity_id: binary_sensor.apollo_msr_1_ce7700_radar_target
        to: 'on'

    condition:
      - condition: state
        entity_id: switch.shellyplus1pm_e465b8f12024_switch_0
        state: 'off'

    action:
      - action: homeassistant.turn_on
        entity_id: switch.shellyplus1pm_e465b8f12024_switch_0

  - alias: "Study room - Turn on AC when temperature is above threshold"
    initial_state: true
    id: study_room_turn_ac_on
    trigger:
      - platform: numeric_state
        entity_id: sensor.study_temperature_temperature
        above: 32

    condition:
      - condition: state
        entity_id: binary_sensor.apollo_msr_1_ce7700_radar_target
        state: 'on'
      - condition: state
        entity_id: sensor.ohad_ble
        state: 'study'
      - condition: numeric_state
        entity_id: sensor.ohad_ble
        attribute: distance
        below: 5.5

    action:
      - action: switch.turn_on
        entity_id: switch.study_room_ac_beeper

      - action: climate.set_hvac_mode
        target:
          entity_id: climate.study_room_ac
        data:
          hvac_mode: cool

      - action: switch.turn_off
        entity_id: switch.study_room_ac_beeper

      - action: climate.set_preset_mode
        data:
          preset_mode: sleep
          entity_id: climate.study_room_ac

      - action: climate.set_temperature
        data:
          temperature: 25
          entity_id: climate.study_room_ac

      - action: climate.set_fan_mode
        data:
          fan_mode: silent
          entity_id: climate.study_room_ac

      - action: climate.set_swing_mode
        data:
          swing_mode: both
          entity_id: climate.study_room_ac


  - alias: "Study Room - Close cover on sunset"
    initial_state: true
    id: study_room_close_cover_sunset
    trigger:
      - platform: sun
        event: sunset

    condition:
      - condition: state
        entity_id: input_boolean.away_mode
        state: 'off'

    action:
      - action: cover.close_cover
        entity_id: cover.study_room


  - alias: "Study Room - Open cover in the morning"
    initial_state: true
    id: study_room_open_cover_morning
    trigger:
      - platform: time
        at: "08:00:00"
      - platform: time
        at: "08:30:00"

    condition:
      - condition: state
        entity_id: input_boolean.away_mode
        state: 'off'
      - condition: state
        entity_id: person.ohad_benita
        state: 'home'

    action:
      - action: cover.set_cover_position
        data_template:
          entity_id: cover.study_room
          position: >-
            {{ max(state_attr('cover.study_room', 'current_position') | int, 80) }}


  - alias: "Study Room - Toggle light by switch"
    initial_state: true
    id: study_room_toggle_light_by_switch
    trigger:
      - platform: state
        entity_id: sensor.study_room_01_action
        to: 'open'

    action:
      - action: switch.toggle
        entity_id: switch.shellyplus1pm_e465b8f12024_switch_0


  - alias: "Study Room - Toggle AC by switch"
    initial_state: true
    id: study_room_toggle_ac_by_switch
    trigger:
      - platform: state
        entity_id: sensor.study_room_01_action
        to: 'close'

    action:
      - if:
          - condition: state
            entity_id: climate.study_room_ac
            state: 'off'
        then:
          - choose:
              - conditions:
                  - condition: state
                    entity_id: binary_sensor.dst
                    state: 'on'
                sequence:
                  - action: climate.set_hvac_mode
                    data:
                      entity_id: climate.study_room_ac
                      hvac_mode: 'cool'
              - conditions:
                  - condition: state
                    entity_id: binary_sensor.dst
                    state: 'off'
                sequence:
                  - action: climate.set_hvac_mode
                    data:
                      entity_id: climate.study_room_ac
                      hvac_mode: 'heat'

      - action: climate.toggle
        entity_id: climate.study_room_ac
