---
automation:
  - alias: "Study Room - Turn lights off when no one is in the room"
    id: study_room_turn_ac_and_lights_off
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.apollo_msr_1_ce7700_radar_target
        to: 'off'
        for:
          minutes: 2

      - platform: homeassistant
        event: start

    condition:
      - condition: state
        entity_id: switch.shellyplus1pm_e465b8f12024_switch_0
        state: 'on'
      - condition: state
        entity_id: binary_sensor.apollo_msr_1_ce7700_radar_target
        state: 'off'

    action:
      - action: homeassistant.turn_off
        entity_id: switch.shellyplus1pm_e465b8f12024_switch_0


  - alias: "Study Room - Turn on the lights when motion is detected"
    initial_state: true
    id: study_room_turn_lights_on_motion_detected
    trigger:
      - platform: state
        entity_id: binary_sensor.apollo_msr_1_ce7700_radar_target
        to: 'on'

    condition:
      - condition: state
        entity_id: switch.shellyplus1pm_e465b8f12024_switch_0
        state: 'off'
      - condition: not
        conditions:
          - condition: state
            entity_id: sensor.creality_ender_v3_ke_current_print_state
            state: 'printing'
      - condition: time
        weekday:
          - sun
          - mon
          - tue
          - wed
          - thu
        after: '08:00:00'
        before: '20:00:00'
      - condition: state
        entity_id: binary_sensor.jewish_calendar_issur_melacha_in_effect
        state: 'off'

    action:
      - action: homeassistant.turn_on
        entity_id: switch.shellyplus1pm_e465b8f12024_switch_0


  - alias: "Study Room - Turn AC off when no one is in the room"
    id: study_room_turn_ac_off_when_no_motion_is_detected
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.apollo_msr_1_ce7700_radar_target
        to: 'off'
        for:
          minutes: 10

      - platform: homeassistant
        event: start

    condition:
      - condition: template
        value_template: >-
          {{ not is_state('climate.study_room_ac', 'off') }}
      - condition: state
        entity_id: binary_sensor.apollo_msr_1_ce7700_radar_target
        state: 'off'

    action:
      - action: homeassistant.turn_off
        entity_id: climate.study_room_ac


  # DISABLED since the sensor has been removed
  # - alias: "Study room - Turn on AC when temperature is above threshold"
  #   initial_state: true
  #   id: study_room_turn_ac_on
  #   trigger:
  #     - platform: numeric_state
  #       entity_id: sensor.study_temperature_temperature
  #       above: 32

  #   condition:
  #     - condition: state
  #       entity_id: binary_sensor.apollo_msr_1_ce7700_radar_target
  #       state: 'on'
  #     - condition: state
  #       entity_id: sensor.ohad_ble
  #       state: 'study'
  #     - condition: numeric_state
  #       entity_id: sensor.ohad_ble
  #       attribute: distance
  #       below: 5.5

  #   action:
  #     - action: switch.turn_on
  #       entity_id: switch.study_room_ac_beeper

  #     - action: climate.set_hvac_mode
  #       target:
  #         entity_id: climate.study_room_ac
  #       data:
  #         hvac_mode: cool

  #     - action: switch.turn_off
  #       entity_id: switch.study_room_ac_beeper

  #     - action: climate.set_preset_mode
  #       data:
  #         preset_mode: sleep
  #         entity_id: climate.study_room_ac

  #     - action: climate.set_temperature
  #       data:
  #         temperature: 25
  #         entity_id: climate.study_room_ac

  #     - action: climate.set_fan_mode
  #       data:
  #         fan_mode: silent
  #         entity_id: climate.study_room_ac

  #     - action: climate.set_swing_mode
  #       data:
  #         swing_mode: both
  #         entity_id: climate.study_room_ac


  - alias: "Study Room - Close cover on sunset"
    initial_state: true
    id: study_room_close_cover_sunset
    trigger:
      - platform: sun
        event: sunset

    condition:
      - condition: state
        entity_id: input_boolean.away_mode
        state: 'off'

    action:
      - action: cover.close_cover
        entity_id: cover.study_room


  - alias: "Study Room - Open cover in the morning"
    initial_state: true
    id: study_room_open_cover_morning
    trigger:
      - platform: time
        at: "08:00:00"
      - platform: time
        at: "08:30:00"

    condition:
      - condition: state
        entity_id: input_boolean.away_mode
        state: 'off'
      - condition: state
        entity_id: person.ohad_benita
        state: 'home'
      - condition: time
        weekday:
          - sun
          - mon
          - tue
          - wed
          - thu
      - condition: state
        entity_id: binary_sensor.jewish_calendar_issur_melacha_in_effect
        state: 'off'

    action:
      - action: cover.set_cover_position
        data_template:
          entity_id: cover.study_room
          position: >-
            {{ max(state_attr('cover.study_room', 'current_position') | int, 45) }}


  - alias: "Study Room - Toggle light by switch"
    initial_state: true
    id: study_room_toggle_light_by_switch
    trigger:
      - platform: state
        entity_id: sensor.study_room_01_action
        to: 'open'

    action:
      - action: switch.toggle
        entity_id: switch.shellyplus1pm_e465b8f12024_switch_0


  - alias: "Study Room - Toggle AC by switch"
    initial_state: true
    id: study_room_toggle_ac_by_switch
    trigger:
      - platform: state
        entity_id: sensor.study_room_01_action
        to: 'close'

    action:
      - if:
          - condition: state
            entity_id: climate.study_room_ac
            state: 'off'
        then:
          - choose:
              - conditions:
                  - condition: state
                    entity_id: binary_sensor.dst
                    state: 'on'
                sequence:
                  - action: climate.set_hvac_mode
                    data:
                      entity_id: climate.study_room_ac
                      hvac_mode: 'cool'
              - conditions:
                  - condition: state
                    entity_id: binary_sensor.dst
                    state: 'off'
                sequence:
                  - action: climate.set_hvac_mode
                    data:
                      entity_id: climate.study_room_ac
                      hvac_mode: 'heat'

      - action: climate.toggle
        entity_id: climate.study_room_ac


  - alias: Turn off Bike Charger when charging is complete
    id: study_room_turn_off_bike_charger_when_complete
    initial_state: true
    trigger:
      platform: numeric_state
      entity_id: sensor.study_room_e_bike_charger_energy_power
      below: 5
      for:
        hours: 1

    condition:
      - condition: state
        entity_id: switch.study_room_e_bike_charger
        state: 'on'

    action:
      - action: switch.turn_off
        entity_id: switch.study_room_e_bike_charger
      - action: notify.ohad_telegram
        data:
          title: Appliances
          message: Bike charge cycle is completed


  - alias: 'Study room - Handle 3D printer stand button actions'
    id: study_room_3d_printer_stand_button_actions
    initial_state: true
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.study_room_3d_printer_stand_action

    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: sensor.study_room_3d_printer_stand_action
                state: 'button_1_single'
            sequence:
              - action: cover.set_cover_position
                data_template:
                  entity_id: cover.study_room
                  position: >-
                    {{ max(state_attr('cover.study_room', 'current_position') | int, 80) }}

          - conditions:
              - condition: state
                entity_id: sensor.study_room_3d_printer_stand_action
                state: 'button_2_single'
            sequence:
              - action: cover.set_cover_position
                data:
                  entity_id: cover.study_room
                  position: 0

          - conditions:
              - condition: state
                entity_id: sensor.study_room_3d_printer_stand_action
                state: 'button_1_double'
            sequence:
              - action: switch.turn_on
                target:
                  entity_id: switch.creality_printer

          - conditions:
              - condition: state
                entity_id: sensor.study_room_3d_printer_stand_action
                state: 'button_2_double'
            sequence:
              - action: switch.turn_off
                target:
                  entity_id: switch.creality_printer
