---

template:
  - sensor:
      - name: "Study room cover position"
        unique_id: study_room_cover_position
        unit_of_measurement: "%"
        state: >
          {{ state_attr('cover.study_room', 'current_position') }}
        availability: >
          {{ state_attr('cover.study_room','current_position') is number
             or states('cover.study_room') in ['open','closed'] }}

  - binary_sensor:
      - name: "Study room cover moving"
        unique_id: study_room_cover_moving
        state: >
          {% set change = states('sensor.study_room_cover_position_stats') %}
          {{ change | int(0) != 0 }}

sensor:
  - platform: statistics
    name: study_room_cover_position_stats
    entity_id: sensor.study_room_cover_position
    state_characteristic: change
    max_age:
      seconds: 3
    sampling_size: 5
    precision: 0


automation:
  - alias: "Study Room - Turn lights off when no one is in the room"
    id: study_room_turn_ac_and_lights_off
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.apollo_msr_1_ce7700_radar_target
        to: 'off'
        for:
          minutes: 2

      - platform: homeassistant
        event: start

    condition:
      - condition: state
        entity_id: switch.shellyplus1pm_e465b8f12024_switch_0
        state: 'on'
      - condition: state
        entity_id: binary_sensor.apollo_msr_1_ce7700_radar_target
        state: 'off'

    action:
      - action: homeassistant.turn_off
        entity_id: switch.shellyplus1pm_e465b8f12024_switch_0


  - alias: "Study Room - Turn on the lights when motion is detected"
    id: study_room_turn_lights_on_motion_detected
    trigger:
      - platform: state
        entity_id: binary_sensor.apollo_msr_1_ce7700_radar_target
        to: 'on'
      - platform: numeric_state
        entity_id: sensor.apollo_msr_1_ce7700_radar_still_distance
        below: 370

    condition:
      - condition: numeric_state
        entity_id: sensor.apollo_msr_1_ce7700_radar_still_distance
        below: 370
      - condition: state
        entity_id: switch.shellyplus1pm_e465b8f12024_switch_0
        state: 'off'
      - condition: state
        entity_id: binary_sensor.apollo_msr_1_ce7700_radar_target
        state: 'on'
      - not:
          - condition: state
            entity_id: sensor.creality_ender_v3_ke_current_print_state
            state: 'printing'
    action:
      - action: homeassistant.turn_on
        entity_id: switch.shellyplus1pm_e465b8f12024_switch_0


  - alias: "Study Room - Turn AC off when no one is in the room"
    id: study_room_turn_ac_off_when_no_motion_is_detected
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.apollo_msr_1_ce7700_radar_target
        to: 'off'
        for:
          minutes: 10

      - platform: homeassistant
        event: start

    condition:
      - condition: template
        value_template: >-
          {{ not is_state('climate.study_room_ac', 'off') }}
      - condition: state
        entity_id: binary_sensor.apollo_msr_1_ce7700_radar_target
        state: 'off'

    action:
      - action: homeassistant.turn_off
        entity_id: climate.study_room_ac


  - alias: Study Skadis light - follow occupancy
    description: Turn the study Skadis light on/off based on occupancy sensor.
    mode: single

    trigger:
      - platform: state
        entity_id: binary_sensor.occupancy_sensor_b978_occupancy
        to:
          - "on"
          - "off"

    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: binary_sensor.occupancy_sensor_b978_occupancy
                state: "on"
            sequence:
              - action: light.turn_on
                entity_id: light.study_skadis_led_driver
          - conditions:
              - condition: state
                entity_id: binary_sensor.occupancy_sensor_b978_occupancy
                state: "off"
            sequence:
              - action: light.turn_off
                entity_id: light.study_skadis_led_driver

  # DISABLED since the sensor has been removed
  # - alias: "Study room - Turn on AC when temperature is above threshold"
  #   initial_state: true
  #   id: study_room_turn_ac_on
  #   trigger:
  #     - platform: numeric_state
  #       entity_id: sensor.study_temperature_temperature
  #       above: 32

  #   condition:
  #     - condition: state
  #       entity_id: binary_sensor.apollo_msr_1_ce7700_radar_target
  #       state: 'on'
  #     - condition: state
  #       entity_id: sensor.ohad_ble
  #       state: 'study'
  #     - condition: numeric_state
  #       entity_id: sensor.ohad_ble
  #       attribute: distance
  #       below: 5.5

  #   action:
  #     - action: switch.turn_on
  #       entity_id: switch.study_room_ac_beeper

  #     - action: climate.set_hvac_mode
  #       target:
  #         entity_id: climate.study_room_ac
  #       data:
  #         hvac_mode: cool

  #     - action: switch.turn_off
  #       entity_id: switch.study_room_ac_beeper

  #     - action: climate.set_preset_mode
  #       data:
  #         preset_mode: sleep
  #         entity_id: climate.study_room_ac

  #     - action: climate.set_temperature
  #       data:
  #         temperature: 25
  #         entity_id: climate.study_room_ac

  #     - action: climate.set_fan_mode
  #       data:
  #         fan_mode: silent
  #         entity_id: climate.study_room_ac

  #     - action: climate.set_swing_mode
  #       data:
  #         swing_mode: both
  #         entity_id: climate.study_room_ac


  - alias: "Study Room - Close cover on sunset"
    initial_state: true
    id: study_room_close_cover_sunset
    trigger:
      - platform: sun
        event: sunset

    condition:
      - condition: state
        entity_id: input_boolean.away_mode
        state: 'off'

    action:
      - action: cover.close_cover
        entity_id: cover.study_room


  - alias: "Study Room - Open cover in the morning"
    initial_state: true
    id: study_room_open_cover_morning
    trigger:
      - platform: time
        at: "08:00:00"
      - platform: time
        at: "08:30:00"

    condition:
      - condition: state
        entity_id: input_boolean.away_mode
        state: 'off'
      - condition: state
        entity_id: person.ohad_benita
        state: 'home'
      - condition: time
        weekday:
          - sun
          - mon
          - tue
          - wed
          - thu
      - condition: state
        entity_id: binary_sensor.jewish_calendar_issur_melacha_in_effect
        state: 'off'

    action:
      - action: cover.set_cover_position
        data_template:
          entity_id: cover.study_room
          position: >-
            {{ max(state_attr('cover.study_room', 'current_position') | int, 25) }}


  - alias: Turn off Bike Charger when charging is complete
    id: study_room_turn_off_bike_charger_when_complete
    initial_state: true
    trigger:
      platform: numeric_state
      entity_id: sensor.study_room_e_bike_charger_energy_power
      below: 5
      for:
        hours: 1

    condition:
      - condition: state
        entity_id: switch.study_room_e_bike_charger
        state: 'on'

    action:
      - action: switch.turn_off
        entity_id: switch.study_room_e_bike_charger
      - action: notify.send_message
        target:
          entity_id: notify.telegram_bot_659000495_155103022
        data:
          title: Appliances
          message: Bike charge cycle is completed


  - alias: 'Study room - Handle 3D printer stand button actions'
    id: study_room_3d_printer_stand_button_actions
    initial_state: true
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.study_desk_remote_action

    action:
      - choose:
          - conditions:
              - condition: template
                value_template: >
                  {{ trigger.to_state.state in ['button_1_single','button_2_single']
                    and is_state('binary_sensor.study_room_cover_moving','on') }}
            sequence:
              - action: cover.stop_cover
                target:
                  entity_id: cover.study_room

          - conditions:
              - condition: state
                entity_id: sensor.study_desk_remote_action
                state: 'button_2_single'
            sequence:
              - action: cover.set_cover_position
                data_template:
                  entity_id: cover.study_room
                  position: >-
                    {{ max(state_attr('cover.study_room', 'current_position') | int, 80) }}

          - conditions:
              - condition: state
                entity_id: sensor.study_desk_remote_action
                state: 'button_1_single'
            sequence:
              - action: cover.set_cover_position
                data:
                  entity_id: cover.study_room
                  position: 0

          - conditions:
              - condition: state
                entity_id: sensor.study_desk_remote_action
                state: 'button_2_double'
            sequence:
              - action: switch.turn_on
                target:
                  entity_id: switch.creality_printer

          - conditions:
              - condition: state
                entity_id: sensor.study_desk_remote_action
                state: 'button_1_double'
            sequence:
              - action: switch.turn_off
                target:
                  entity_id: switch.creality_printer

          - conditions:
              - condition: state
                entity_id: sensor.study_desk_remote_action
                state: 'button_2_hold'
            sequence:
              - action: lock.lock
                entity_id: lock.home_only_doors

          - conditions:
              - condition: state
                entity_id: sensor.study_desk_remote_action
                state: 'button_4_double'
            sequence:
              - choose:
                  - conditions:
                      - condition: numeric_state
                        entity_id: sensor.openweathermap_feels_like_temperature
                        above: 23
                    sequence:
                      - service: climate.set_hvac_mode
                        target:
                          entity_id: climate.study_room_ac
                        data:
                          hvac_mode: 'cool'
                default:
                  - service: climate.set_hvac_mode
                    target:
                      entity_id: climate.study_room_ac
                    data:
                      hvac_mode: 'heat'

          - conditions:
              - condition: state
                entity_id: sensor.study_desk_remote_action
                state: 'button_3_double'
            sequence:
              - action: climate.turn_off
                entity_id: climate.study_room_ac

          - conditions:
              - condition: state
                entity_id: sensor.study_desk_remote_action
                state: 'button_4_single'
            sequence:
              - action: switch.turn_on
                entity_id: switch.shellyplus1pm_e465b8f12024_switch_0

          - conditions:
              - condition: state
                entity_id: sensor.study_desk_remote_action
                state: 'button_3_single'
            sequence:
              - action: switch.turn_off
                entity_id: switch.shellyplus1pm_e465b8f12024_switch_0
