---
automation:
  - alias: "Study Room - Turn AC and lights off when no one is in the room"
    id: study_room_turn_ac_and_lights_off
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.apollo_msr_1_ce7700_radar_target
        to: 'off'
        for:
          minutes: 10

    condition:
      condition: template
      value_template: >-
        {{ not is_state('climate.study_room_ac', 'off') }}

    action:
      - action: switch.turn_on
        entity_id: switch.study_room_ac_beeper

      - action: climate.turn_off
        data_template:
          entity_id: climate.study_room_ac

      - action: switch.turn_off
        entity_id: switch.study_room_ac_beeper

      - action: homeassistant.turn_off
        data_template:
          entity_id: switch.shellyplus1pm_e465b8f12024_switch_0


  - alias: "Study Room - Turn AC and lights when no one is in the room"
    initial_state: false
    id: study_room_turn_ac_and_lights_on
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.apollo_msr_1_ce7700_radar_target
        to: 'on'

    action:
      - action: switch.turn_on
        entity_id: switch.study_room_ac_beeper

      - action: climate.set_hvac_mode
        target:
          entity_id: climate.study_room_ac
        data:
          hvac_mode: cool

      - action: switch.turn_off
        entity_id: switch.study_room_ac_beeper

      - action: climate.set_preset_mode
        data:
          preset_mode: sleep
          entity_id: climate.roi_room_ac
      - action: climate.set_temperature
        data:
          temperature: 24
          entity_id: climate.roi_room_ac
      - action: climate.set_fan_mode
        data:
          fan_mode: silent
          entity_id: climate.roi_room_ac
      - action: climate.set_swing_mode
        data:
          swing_mode: both
          entity_id: climate.roi_room_ac

      - action: homeassistant.turn_on
        data_template:
          entity_id: switch.shellyplus1pm_e465b8f12024_switch_0
