---
group:
  irrigation_switches:
    name: Irrigation switches
    entities:
      - switch.irrigation_l5
      - switch.irrigation_l4
      - switch.irrigation_l2
      - switch.irrigation_l3

automation:
  - alias: Weekly Irrigation Cycle
    id: irrigation_simple_weekly_schedule
    initial_state: true
    trigger:
      - platform: sun
        event: sunrise

    condition:
      condition: time
      weekday:
        - sun
        - tue
        - thu

    action:
      - action: switch.turn_on
        entity_id: switch.irrigation_l6  # master
      - delay: "00:00:05"
      - action: switch.turn_on
        entity_id: group.irrigation_switches

      - delay: "01:00:00"

      - action: switch.turn_off
        entity_id: group.irrigation_switches
      - delay: "00:00:05"
      - action: switch.turn_off
        entity_id: switch.irrigation_l6  # master


  - alias: Irrigation Watchdog
    id: irrigation_watchdog_shutdown
    initial_state: true
    trigger:
      - platform: time_pattern
        minutes: "/30"
        seconds: "*"

    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: switch.irrigation_l6
          state: 'on'
          for:
            minutes: 70

    action:
      - action: switch.turn_off
        entity_id: switch.irrigation_l6
      - action: switch.turn_off
        entity_id: group.irrigation_switches

      - wait_for_trigger:
          - platform: state
            entity_id: switch.irrigation_l6
            to: 'off'
        timeout:
          minutes: 2
        continue_on_timeout: false

      - action: notify.ohad_telegram
        data:
          message: 'Irrigation Watchdog had to stop the irrigation, please check the issue with the automation'


  - alias: "Yard - Turn off roof lights in the night"
    id: yard_turn_off_roof_lights_in_the_night
    initial_state: true
    trigger:
      - platform: time
        at: "23:00:00"

    action:
      - action: homeassistant.turn_off
        entity_id:
          - `  # roof flood light #1
          - switch.shellyswitch25_6869e3_channel_2  # roof flood light #2


  - alias: "Yard - Turn off path lights in the night"
    id: yard_turn_off_path_lights_in_the_night
    initial_state: true
    trigger:
      - platform: time
        at: "01:00:00"

    action:
      - action: homeassistant.turn_off
        entity_id:
          - switch.shellyplus2pm_d48afc581860_switch_1  # kitchen outdoor light
          - switch.shellyplus2pm_fcb467a557a0_switch_1  # kids bathroom outdoor light
