---
script:
  turn_on_all_yard_lights:
    sequence:
      - action: homeassistant.turn_on
        target:
          entity_id:
            - switch.shellyplus2pm_fcb467a557a0_switch_0
            - switch.shellyplus2pm_d48afc581860_switch_1
            - switch.shellyswitch25_6869e3_channel_1
            - switch.shellyswitch25_6869e3_channel_2
            - switch.shelly1pmminig3_34b7dac88574_switch_0
            - switch.clinic_door_floodlight_switch_0
            - switch.shelly1pmminig3_34b7dac9ea68_switch_0
      - wait_template: >-
          {{ is_state('switch.clinic_door_floodlight_switch_0', 'off') }}
        timeout:
          minutes: 1
        continue_on_timeout: false

      - action: homeassistant.turn_on
        target:
          entity_id:
            - switch.clinic_door_floodlight_switch_0

light:
  - platform: template
    lights:
      all_yard_lights:
        value_template: >-
          {{
            is_state('switch.shellyplus2pm_fcb467a557a0_switch_0', 'on') and
            is_state('switch.shellyplus2pm_d48afc581860_switch_1', 'on') and
            is_state('switch.shellyswitch25_6869e3_channel_1', 'on') and
            is_state('switch.shellyswitch25_6869e3_channel_2', 'on') and
            is_state('switch.shelly1pmminig3_34b7dac88574_switch_0', 'on') and
            is_state('switch.clinic_door_floodlight_switch_0', 'on') and
            is_state('switch.shelly1pmminig3_34b7dac9ea68_switch_0', 'on') and
            is_state('switch.backyard_flood_light_near_clinic', 'on')
          }}
        turn_on:
          action: script.turn_on_all_yard_lights
        turn_off:
          action: homeassistant.turn_off
          data:
            entity_id:
              - switch.shellyplus2pm_fcb467a557a0_switch_0
              - switch.shellyplus2pm_d48afc581860_switch_1
              - switch.shellyswitch25_6869e3_channel_1
              - switch.shellyswitch25_6869e3_channel_2
              - switch.shelly1pmminig3_34b7dac88574_switch_0
              - switch.clinic_door_floodlight_switch_0
              - switch.shelly1pmminig3_34b7dac9ea68_switch_0
              - switch.backyard_flood_light_near_clinic

rest_command:
  analyze_laundry:
    url: !secret analyze_laundry_image_url
    method: GET

automation:
  - alias: "Yard - Turn off roof lights in the night"
    id: yard_turn_off_roof_lights_in_the_night
    initial_state: true
    trigger:
      - platform: time
        at: "23:00:00"

    action:
      - action: homeassistant.turn_off
        entity_id:
          - switch.shellyswitch25_6869e3_channel_1 # roof flood light #1
          - switch.shellyswitch25_6869e3_channel_2 # roof flood light #2

  - alias: "Yard - Turn off path lights in the night"
    id: yard_turn_off_path_lights_in_the_night
    initial_state: true
    trigger:
      - platform: time
        at: "22:00:00"

    action:
      - action: homeassistant.turn_off
        entity_id:
          - switch.clinic_door_floodlight_switch_0 # clinic door
          - switch.shellyplus2pm_d48afc581860_switch_1 # kitchen outdoor light
          - switch.shellyplus2pm_fcb467a557a0_switch_0 # kids bathroom outdoor light
          - switch.shelly1pmminig3_34b7dac88574_switch_0 # Parking and outdoor fan

  - alias: "Turn on kids bathroom path and clinic lights"
    id: yard_turn_on_kids_bathroom_path_clinic_lights
    initial_state: true
    mode: single
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.kids_bathroom_door_contact
          - binary_sensor.kitchen_path_person
          - binary_sensor.kids_bathroom_door_external_occupancy
        to: "on"
      - platform: homeassistant
        event: start

    condition:
      condition: and
      conditions:
        - condition: or
          conditions:
            - condition: sun
              before: sunrise
              before_offset: "00:15:00"
            - condition: sun
              after: sunset
              after_offset: "-00:15:00"
        - condition: or
          conditions:
            - condition: state
              entity_id: binary_sensor.kitchen_door_contact
              state: "on"
            - condition: state
              entity_id: binary_sensor.kids_bathroom_door_contact
              state: "on"
            - condition: state
              entity_id: binary_sensor.kids_bathroom_door_external_occupancy
              state: "on"

    action:
      - action: homeassistant.turn_on
        entity_id:
          - switch.shellyplus2pm_fcb467a557a0_switch_0 # Bathroom door
          - switch.clinic_door_floodlight_switch_0

  - alias: "Turn off kids bathroom path lights"
    id: yard_turn_off_kids_bathroom_path_light
    initial_state: true
    mode: single
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.kids_bathroom_door_contact
          - binary_sensor.kitchen_path_person
          - binary_sensor.kids_bathroom_door_external_occupancy
        to: "off"
        for:
          minutes: 5
      - platform: homeassistant
        event: start

    condition:
      - condition: state
        entity_id: binary_sensor.kids_bathroom_door_contact
        state: "off"
      - condition: state
        entity_id: binary_sensor.kitchen_path_person
        state: "off"
      - condition: state
        entity_id: binary_sensor.kids_bathroom_door_external_occupancy
        state: "off"

    action:
      - action: homeassistant.turn_off
        entity_id:
          - switch.shellyplus2pm_fcb467a557a0_switch_0 # Bathroom door
          - switch.clinic_door_floodlight_switch_0 # Clinic door


  - alias: "Turn on kitchen door light"
    id: yard_turn_on_kitchen_door_light
    initial_state: true
    mode: single
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.kitchen_door_01_occupancy
          - binary_sensor.kitchen_door_02_occupancy
          - binary_sensor.kitchen_door_contact
        to: "on"
      - platform: homeassistant
        event: start

    condition:
      condition: and
      conditions:
        - condition: or
          conditions:
            - condition: sun
              before: sunrise
              before_offset: "00:15:00"
            - condition: sun
              after: sunset
              after_offset: "-00:15:00"
        - condition: or
          conditions:
            - condition: state
              entity_id: binary_sensor.kitchen_door_01_occupancy
              state: "on"
            - condition: state
              entity_id: binary_sensor.kitchen_door_02_occupancy
              state: "on"
            - condition: state
              entity_id: binary_sensor.kitchen_door_contact
              state: "on"

    action:
      - action: homeassistant.turn_on
        entity_id: switch.shellyplus2pm_d48afc581860_switch_1

  - alias: "Turn off kitchen door light"
    id: yard_turn_off_kitchen_door_light
    initial_state: true
    mode: single
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.kitchen_door_01_occupancy
          - binary_sensor.kitchen_door_02_occupancy
          - binary_sensor.kitchen_door_contact
        to: "off"
        for:
          minutes: 5

      - platform: homeassistant
        event: start

    condition:
      - condition: state
        entity_id: switch.shellyplus2pm_d48afc581860_switch_1
        state: "on"
      - condition: state
        entity_id: binary_sensor.kitchen_door_contact
        state: "off"
      - condition: state
        entity_id: binary_sensor.kitchen_door_01_occupancy
        state: "off"
      - condition: state
        entity_id: binary_sensor.kitchen_door_02_occupancy
        state: "off"

    action:
      - action: homeassistant.turn_off
        entity_id: switch.shellyplus2pm_d48afc581860_switch_1 # Kitchen path flood light

  - alias: "Turn off kids bathroom door path light when door is closed"
    id: yard_turn_on_kids_bathroom_door_path_light_when_door_is_closed
    initial_state: true
    mode: single
    trigger:
      - platform: state
        entity_id: binary_sensor.kids_bathroom_door_contact
        to: "off"
        for:
          minutes: 10
      - platform: homeassistant
        event: start

    condition:
      - condition: state
        entity_id: binary_sensor.kids_bathroom_door_contact
        state: "off"
      - condition: state
        entity_id: switch.shellyplus2pm_fcb467a557a0_switch_0
        state: "on"
      - condition: state
        entity_id: binary_sensor.kitchen_path_person
        state: "off"

    action:
      - action: homeassistant.turn_off
        entity_id: switch.shellyplus2pm_fcb467a557a0_switch_0

  - alias: "Alert on high expected water consumption"
    id: yard_cost_alert_on_high_expected_water_consumption
    initial_state: true
    mode: single
    trigger:
      - platform: numeric_state
        entity_id: sensor.meter_1018_monthly_forecast
        above: 55
      - platform: homeassistant
        event: start

    condition:
      - condition: numeric_state
        entity_id: sensor.meter_1018_monthly_forecast
        above: 55
      - condition: template # once a week
        value_template: "{{ (now() | as_timestamp) - (state_attr('automation.alert_on_high_expected_water_consumption', 'last_triggered') | default(0) | as_timestamp) > 604800 }}"

    action:
      - action: notify.ohad_telegram
        data:
          title: "Alert: High water consumption forecast"
          message: >-
            The current forecasted monthly water consumption is {{ states('sensor.meter_1018_monthly_forecast') | int }} m³.
            Please check whether there's a water leak.

  - alias: "Clnic door entrance - Handle button actions"
    id: clinic_entrance_button_actions
    initial_state: true
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.clinic_door_entrance_action

    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: sensor.clinic_door_entrance_action
                state: "button_1_single"
            sequence:
              - action: homeassistant.turn_on
                target:
                  entity_id: switch.clinic_door_floodlight_switch_0

          - conditions:
              - condition: state
                entity_id: sensor.clinic_door_entrance_action
                state: "button_2_single"
            sequence:
              - action: homeassistant.turn_off
                target:
                  entity_id: switch.clinic_door_floodlight_switch_0

          - conditions:
              - condition: state
                entity_id: sensor.clinic_door_entrance_action
                state: "button_1_double"
            sequence:
              - action: switch.turn_on
                target:
                  entity_id:
                    - switch.clinic_door_floodlight_switch_0
                    - switch.shellyplus2pm_fcb467a557a0_switch_0

          - conditions:
              - condition: state
                entity_id: sensor.clinic_door_entrance_action
                state: "button_2_double"
            sequence:
              - action: switch.turn_off
                target:
                  entity_id:
                    - switch.clinic_door_floodlight_switch_0
                    - switch.shellyplus2pm_fcb467a557a0_switch_0

  - alias: "Turn off clinic door flood light when the door is locked"
    id: yard_turn_off_clinic_door_flight_light_when_door_locked
    initial_state: true
    mode: single
    trigger:
      - platform: state
        entity_id: lock.clinic_door
        to: "locked"
        for:
          minutes: 5

    condition:
      - condition: state
        entity_id: switch.clinic_door_floodlight_switch_0 # clinic door
        state: "on"

    action:
      - action: homeassistant.turn_off
        entity_id:
          - switch.clinic_door_floodlight_switch_0 # Clinic door

  - alias: Turn off clinic floodlight during daylight hours
    id: yard_turn_off_clinic_door_light_during_daylight_hours
    trigger:
      - platform: state
        entity_id: switch.clinic_door_floodlight_switch_0
        to: "on"
        for:
          minutes: 2

    condition:
      - condition: sun
        after: sunrise
        after_offset: "00:15:00"
        before: sunset
        before_offset: "-00:15:00"

    action:
      - action: homeassistant.turn_off
        entity_id: switch.clinic_door_floodlight_switch_0

  - alias: Sunset and Sunrise house sign control
    id: yard_house_sign_control
    description: Control house sign on sunset and sunrise
    mode: single
    trigger:
      - platform: sun
        event: sunset
      - platform: sun
        event: sunrise
    action:
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ trigger.event == 'sunset' }}"
            sequence:
              - action: switch.turn_on
                target:
                  entity_id: switch.shelly1pmminig3_34b7da8f8b78_switch_0
          - conditions:
              - condition: template
                value_template: "{{ trigger.event == 'sunrise' }}"
            sequence:
              - action: switch.turn_off
                target:
                  entity_id: switch.shelly1pmminig3_34b7da8f8b78_switch_0


  - alias: Re-enable Parking Flood Lights Automation after being disabled for 1 hour
    id: yard_re_enable_parking_flood_lights_automation
    description: "Re-enables the turn_off_parking_flood_lights_when_no_motion_is_detected automation 1 hour after it is disabled."
    trigger:
      - platform: state
        entity_id: automation.turn_off_parking_flood_lights_when_no_motion_is_detected
        to: 'off'
        for: '01:00:00'
    action:
      - action: automation.turn_on
        entity_id: automation.turn_off_parking_flood_lights_when_no_motion_is_detected


  - alias: "Sync front lawn flood light with roof 2 switch"
    id: yard_sync_front_lawn_flood_light_with_roof_2_switch
    initial_state: true
    trigger:
      - platform: state
        entity_id: switch.shellyswitch25_6869e3_channel_2

    action:
      - action: switch.toggle
        entity_id: switch.shelly1pmminig3_34b7dac9ea68_switch_0


  - alias: "Analyze laundry when the sun sets"
    id: yard_analyze_laundry_sunset
    initial_state: true
    trigger:
      - platform: sun
        event: sunset
      - platform: homeassistant
        event: start

    action:
      - delay: '00:00:20'

      - action: rest_command.analyze_laundry

  - alias: "Alert if laundry is out during the night"
    id: yard_alert_if_laundry_is_out
    initial_state: true
    trigger:
      platform: sun
      event: sunset
      offset: "01:00:00"

    condition:
      - condition: state
        entity_id: binary_sensor.is_laundry_hanging
        state: 'on'
      - alias: "Alert only if humidity is high"
        condition: numeric_state
        entity_id: sensor.openweathermap_humidity
        above: 50

    action:
      - action: camera.snapshot
        data:
          entity_id: camera.kitchen_path_snapshots_clear
          filename: "/config/www/snapshots/kitchen_path_camera_clear_snapshot.jpg"

      - delay: '00:00:02'

      - action: notify.ohad_telegram
        data:
          title: "Alert: Laundry is out"
          message: >-
            please consider bringing it into the house
          data:
            photo:
              - file: "/config/www/snapshots/kitchen_path_camera_clear_snapshot.jpg"
                caption: >-
                  **Alert**: Laundry is out - [View Live Feed]({{ states('sensor.ha_base_url') }}/api/camera_proxy/camera.kitchen_path_snapshots_clear?token={{ state_attr('camera.kitchen_path_snapshots_clear', 'access_token') }})
                parse_mode: markdown


  - alias: "Turn backyard light on when a person is detected"
    id: yard_turn_on_backyard_light_person_detected
    initial_state: true
    mode: single
    trigger:
      - platform: state
        entity_id: binary_sensor.south_yard_person
        to: "on"
      - platform: homeassistant
        event: start

    condition:
      condition: and
      conditions:
        - condition: or
          conditions:
            - condition: sun
              before: sunrise
              before_offset: "00:15:00"
            - condition: sun
              after: sunset
              after_offset: "-00:15:00"
        - condition: or
          conditions:
            - condition: state
              entity_id: binary_sensor.south_yard_person
              state: "on"

    action:
      - action: homeassistant.turn_on
        entity_id: switch.backyard_flood_light_near_clinic


  - alias: "Turn backyard light when no one is detected"
    id: yard_turn_off_backyard_light_no_person_detected
    initial_state: true
    mode: single
    trigger:
      - platform: state
        entity_id: binary_sensor.south_yard_person
        to: "off"
        for:
          minutes: 5

      - platform: homeassistant
        event: start

    condition:
      - condition: state
        entity_id: binary_sensor.south_yard_person
        state: "off"

    action:
      - action: homeassistant.turn_off
        entity_id: switch.backyard_flood_light_near_clinic
