---
name: Home Assistant CI

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Lint configuration files
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tool: [yamllint, jsonlint]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          if [ "${{ matrix.tool }}" == "yamllint" ]; then
            pip install yamllint
          else
            npm install -g jsonlint
          fi

      - name: Run linter
        run: |
          if [ "${{ matrix.tool }}" == "yamllint" ]; then
            yamllint .
          else
            find . -name "*.json" -exec jsonlint -q {} \;
          fi

  validate:
    name: Validate HASS configuration
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull Home Assistant Docker image
        run: docker pull ghcr.io/home-assistant/home-assistant:stable

      - name: Validate Configuration
        run: |
          docker run --rm -v $PWD:/config \
            ghcr.io/home-assistant/home-assistant:stable \
            python /usr/src/homeassistant/homeassistant/scripts/check_config.py -c /config
