name: Validate Home Assistant Configuration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check:
    name: Home Assistant config check
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: check config
        uses: glitchcrab/action-hass-check-config@main