name: Config Validation

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  validate:
    name: Validate HASS configuration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull Home Assistant Docker image
        run: docker pull ghcr.io/home-assistant/home-assistant:stable

      - name: Validate Configuration
        run: |
          docker run --rm -v $PWD:/config ghcr.io/home-assistant/home-assistant:stable python /usr/src/homeassistant/homeassistant/scripts/check_config.py -c /config